### ISSUE TITLE
Convert to multi-module maven project

### ISSUE THREAD

**Issue by sne11ius** [pf4j/pf4j#115]
I think this project would benefit from pulling all extensions (like the spring integration) into into the github.com/decebals/pf4j source tree and beeing converted into a multi module maven project.

I am trying out the framework currently and the first thing I did was to add a property to my pom (like this: `<pf4j.version>...</pf4j.version>`). Now since this will be a spring boot project, I also want the spring extension.

Is this the same version? If not: which version of the spring extension do I need for which pf4j version?

These question would simply not come up if you would convert the project. I could always be sure that (ideally) everything works just fine for a given version.

What do you think?

**Comment by decebals** [comment]
> I think this project would benefit from pulling all extensions (like the spring integration) into into the github.com/decebals/pf4j source tree and beeing converted into a multi module maven project.

I don't know what to say. Each variant has advantages and disadvantages. For example, `pf4j-spring` is a project that is rarely changed an for this reason I prefer to use a separate repository.
We will see in the featur, after some investigation if it's a good idea to move `pf4j-spring` in pf4j repository as a new module.

> I am trying out the framework currently and the first thing I did was to add a property to my pom (like this: <pf4j.version>...</pf4j.version>). Now since this will be a spring boot project, I also want the spring extension.

In your situation I would go with:
- define `pf4j.version` property in pom.xml (the value is the last pf4j available version)
- add pf4j-spring as dependency (the last pf4j-spring available version)
- add spring/spring-boot with what version you want

Pf4j-spring does not use too much classes from spring, so I think that you don't have a problem with the "embedded" Spring version.
If Maven is in trouble, then you must exclude spring from the pf4j-spring dependency.
