### ISSUE TITLE
Restrict a plugin to read and write files

### ISSUE THREAD

**Issue by micha2017** [pf4j/pf4j#127]
Hello,
First of all: Thank you for sharing this great framework. :-)

I want to discuss if it's possible to restrict a plugin from read or write something from/to the filesystem. For example, a plugin called 'calculator-plugin' should not have access rights to the filesystem. If this plugin is created by someone else, I will not check the whole source code to extend the application. It would be great to have some kind of a simple file in the 'calculator-plugin-1.0.0.zip' defining the required permissions which is read and applied by the plugin loader.

permissions could looks like this:
READ -> only inside the unzipped plugin dir -or- global access
WRITE -> only inside the unzipped plugin dir -or- global access

What do you think?

**Comment by decebals** [comment]
Maybe the correct approach is to use a [SecurityManager](https://docs.oracle.com/javase/tutorial/essential/environment/security.html) together with a policy file for yours plugins. It's the most standard approach.

**Comment by decebals** [comment]
@micha2017 Any news? How did you resolved the problem?

**Comment by micha2017** [comment]
@decebals I agree with you to use the SecurityManager as preferred way. I'm still looking how to integrate the SecurityManager into pf4j, any suggestion is welcome. Also, I suggest to consider this ticket as feature request.

**Comment by decebals** [comment]
Close it due to lack of activity. You can reopen it with a new comment.
