### ISSUE TITLE
Extract the pluginId and pluginVersion from file name

### ISSUE THREAD

**Issue by decebals** [pf4j/pf4j#152]
The idea is that now, you are forced to put information about the plugin id and plugin version in `MANIFEST.MF` or `plugin.properties` (see current implementations for `PluginDescriptorFinder`).
I think that we can extract this information form the plugin filename.
For example if the plugin file is a jar file (the same logic for zip file) with name `myapp.myplugin-1.0.3.jar` and the information about plugin id and version is not available explicit, then we can assume that the plugin id is "myapp.myplugin" and the version is "1.0.3".  With this feature we can have (all) plugins without any descriptor and I think that it's good for small application. 
It's only an idea, I am not so sure that it resolves a real problem.

**Comment by janhoy** [comment]
The simplicity is appealing, but can also lead to a bit too much magic :-) So this feature should be configurable on/off, and perhaps also pluggable regex pattern for filename pattern.

It could be implemented as a new `PluginDescriptorFinder`, right?

**Comment by decebals** [comment]
I see the same behavior in Java 9 Modules. We can leave it for the moment. I wanted only to have a track on this subject.

**Comment by wolframhaussig** [comment]
Reading it from the filename is a bad idea in my book as renaming the file would break the plugin or cause it to be recognised as something which it is not...

Instead, I would prefer that pf4j would fallback to more general names if `Plugin-Id` and `Plugin-Version` is not found. I am thinking of the default entries that the `maven-jar-plugin` creates: `Implementation-Title` and `Implementation-Version`. Also, `Plugin-Provider` could be read from `Implementation-Vendor`.
