### ISSUE TITLE
Move project to the "pf4j" organization

### ISSUE THREAD

**Issue by janhoy** [pf4j/pf4j#164]
The org is already created but old/stale. I think the best is to delete the pf4j/pf4j project and follow this guide to move this project over: https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/ It will retain all history, issues, forks etc.

Do the same for the sub projects and update documentation.

**Comment by decebals** [comment]
I prefer to do this move in small steps:
- [x] buy [pf4j.org](http://www.pf4j.org/) domain
- [x] create a separate GitHub repository (https://github.com/decebals/pf4j-site) that contains the documentation and use gh-pages to bind the documentation to pf4j.org
- [ ] split readme file in multiple sections and move these section in pf4j-site to be available on pf4j
- [ ] change the groupId from `ro.fortsoft.pf4j` to `org.pf4j` in Sonatype (Maven Central Repository)
- [ ] replace `ro.fortsoft.pf4j` to `org.pf4j` in project (package name, ...)
- [ ] move to "pf4j" organization

**Comment by janhoy** [comment]
+1

**Comment by srbala** [comment]
@decebals I have added you the pf4j github.com org group. I have also deleted old versions, so that you can move the current versions.

**Comment by decebals** [comment]
@janhoy 
> The org is already created but old/stale. 

Who created this organisation?

@srbala 
> I have added you the pf4j github.com org group. I have also deleted old versions, so that you can move the current versions.

Maybe I am wrong but it's for the first time when I see your name (I apologize if I'm wrong). It's not clear for me how work the organisation concept in GitHub, the security mechanism in particular. 
I see no public members in organisation. Who is owner on this organisation, who accepts new members? I will read more about this subject.

I think that transferring PF4J to an organisation is valuable in some circumstance. At the moment I'm the only active person contributing code, so I wish to spend my time with issues/features and not with infrastructure.
I do not want to be misunderstood, I am ready to transfer the PF4J's projects to any organisation but I want to see the value of such a move (more visibility, increased adoption, solid brand like Apache or Eclipse Foundation).

**Comment by srbala** [comment]
@decebals 
I have created organisation some time ago. At that time, I have cloned 0.9 version of PF4J. I have deleted old repo to make room for current version. 

I have added you as owner to organisation, so that you can make changes as necessary. currently I am also member of the organisation and updated my status to public.
<img width="789" alt="screen shot 2018-03-22 at 5 41 18 pm" src="https://user-images.githubusercontent.com/1273137/37800683-1183077a-2dfa-11e8-8a6d-a96c7588783e.png">

Moving PF4J to organisation is really valueable as you mentioned, since it has home of it's own, gives the ability add members as the project grow.

**Comment by decebals** [comment]
Done

**Comment by janhoy** [comment]
Cool, thanks!

**Comment by decebals** [comment]
@janhoy I sent you (yesterday) a join invitation.

**Comment by rmrodrigues** [comment]
@decebals Could you add me too?

**Comment by decebals** [comment]
@rmrodrigues Done
