### ISSUE TITLE
Do we need demo_gradle module?

### ISSUE THREAD

**Issue by decebals** [pf4j/pf4j#169]
I prefer to eliminate `demo_gradle` module, to "merge" this module (build scripts and the kotlin part) with `demo` module.
The code in demo_gradle is redundant in my opinion.

**Comment by decebals** [comment]
I don't use Gradle in my project and from this reason it's hard for me to maintain it (I admit that I don't know to much about Gradle).

**Comment by acesar** [comment]
@decebals I started using PF4J a couple of months ago and I am using Gradle, the demo was a big help for me. 
I opened https://github.com/decebals/pf4j/pull/177 to fix the demo and update PF4J to the latest version.
Please have a look.
(We can place it inside the `demo` folder)

**Comment by decebals** [comment]
@acesar 
Thanks for your contribution!
I don't realize yet if it's better to move the gradle scripts in `demo` directory and to remove `demo_gradle`.

**Comment by decebals** [comment]
> > I don't realize yet if it's better to move the gradle scripts in `demo` directory and to remove `demo_gradle`.
> 
> I'd definitely vote for having `demo/maven` and `demo/gradle`.

@sschuberth Can you add a PR with your propose?

**Comment by sschuberth** [comment]
> @sschuberth Can you add a PR with your propose?

Here you go: https://github.com/pf4j/pf4j/pull/584
