### ISSUE TITLE
Change the copyright text from the head of files

### ISSUE THREAD

**Issue by decebals** [pf4j/pf4j#171]
See [file](https://github.com/decebals/pf4j/blob/master/pf4j/src/main/java/org/pf4j/Extension.java).

Change from
```
Copyright 2012 Decebal Suiu
```

to 
```
Copyright (C) 2012 the original author or authors.
```

**Comment by srbala** [comment]
How about updating to organisation name

```
Copyright 2012-2018 Plugin Framework for Java.
```

**Comment by decebals** [comment]
@srbala I prefer my variant (at least in the first phase). I don't think that it's a problem for adoption/contributions. 
Many popular projects (including [Spring Framework](https://github.com/spring-projects/spring-framework/blob/master/spring-core/src/main/java/org/springframework/core/SpringVersion.java#L2)) use this sentence for copyright.

Probably it's good to have `2012-2018` (and not a year) but I prefer to not modify each file on new year. Maybe `2012-present` is a better option.

**Comment by srbala** [comment]
@decebals Your new proposal sounds good. I will update to pf4j-web project files

```
Copyright 2012-present the original author or authors.
```

**Comment by decebals** [comment]
Please add `(C)` also, thanks!

**Comment by srbala** [comment]
Ok, that would result to as follows,  I'll update the pull request

```
Copyright (C) 2012-present the original author or authors.
```

**Comment by decebals** [comment]
@srbala Can you finish this issue (a pull request please)?

**Comment by srbala** [comment]
Sure, assigning this issue to myself
