### ISSUE TITLE
Support multiple plugin directories

### ISSUE THREAD

**Issue by shirishpandharikar** [pf4j/pf4j#206]
Currently, only a single plugins directory is supported as the pluginRoot. This directory is set to `../plugins` in the development mode `plugins` in the production mode. The `DefaultPluginManager` also accepts the pluginRoot path as an argument but default to the above if not specified. It would be good to support multiple plugins directories as pluginRoot. The primary purpose would be to segregate different types of plugins into different directory locations.

**Comment by janhoy** [comment]
Please explain a more concrete example. I don’t Really see the benefit. Also, if using pf4j-update, which of the roots would plugins be installed to?

**Comment by shirishpandharikar** [comment]
Ahh...I guess I completely overlooked the pf4j-update aspect of it. But I guess the way pf4j-update supports multiple repositories in a similar way if pf4j can support multiple plugin root folders it would be great. The use case we are trying to solve is to have a plugin mechanism for both the core system as well as the user modules which are self-contained [UI + API] and use common API's or services from the core platform. We want to keep these two set of plugins separate. Let me think about how we can achieve this. Any suggestions on how we can achieve this would be really helpful.

**Comment by shirishpandharikar** [comment]
The `PluginManager` implementation accepts pluginRoot as a constructor argument and if not specified falls back to resolving it from the `pf4j.pluginsDir` system property. It should be possible to define two separate plugin managers with two separate plugin roots and be used separately. The pf4j-update can then selectively use two different repositories for managing the plugin updates. Could you please confirm if I am thinking in the right direction and this is achievable?
The only issue I see is in the [AbstractPluginManager.initialize](https://github.com/pf4j/pf4j/blob/af42980644633927a4132ecda6f6d8f6ddd606d3/pf4j/src/main/java/org/pf4j/AbstractPluginManager.java#L697) method where the `pf4j.pluginsDir` is again set back as a system property. I do not see its usage anywhere else in the source. It is only used when plugin root is not explicitly set.

**Comment by decebals** [comment]
I think that this feature (multiple plugin directories) will be very rare used because is a very particular case.
Of course, if we have more requests in this regard we should find a solution.
I will take a look to see the impact (API modifications, implementation) and I will come with a response.
As an implementation detail, the `pf4j.pluginsDir` system property is used in some circumstance to pass pluginsDir to other classes, where is not possible to set this variable in constructor or something like this.

**Comment by shirishpandharikar** [comment]
Thanks for the reply. I understand that the use case is not very common. Setting the plugin root directory programmatically does work in my case. The issue is that `pf4j.pluginsDir` system property gets overwritten. Please refer to the code below:
```
PluginManager pm1 = new DefaultPluginManger("/somepath");
PluginManager pm2 = new DefaultPluginManger();

assertEquals("plugins", pm2.getPluginsRoot());
```
The assert fails because the actual plugin root for pm2 should be `plugins` directory in the deployment mode but now points to plugin root of pm1

**Comment by decebals** [comment]
> Also could you please let me know where is pf4j.pluginsDir used. I could not find it in the pf4j source code elsewhere.

I think that you are [right](https://github.com/pf4j/pf4j/search?utf8=%E2%9C%93&q=pf4j.pluginsDir&type=). It was used in the past.
In this case, try to remove the [line](https://github.com/pf4j/pf4j/blob/7eeea8e7f01b39811de20280f5e9ba51a456252a/pf4j/src/main/java/org/pf4j/AbstractPluginManager.java#L697) where this system property is overwritten and see the result (see if it's OK for your application).

**Comment by shirishpandharikar** [comment]
It works perfectly fine. Since I am initializing both the `PluginManager` instances with paths I don't expect to run into an issue. But in case someone tries to define, as shown above, they will run into issues. It would be good if we can remove the line. I will submit pull-request to remove the line if that is ok with you.
