### ISSUE TITLE
Why "plugin.properties" is required?

### ISSUE THREAD

**Issue by mkargar** [pf4j/pf4j#209]
Considering that all properties in "plugin.properties" file are also defined in the pom.xml file of the plugin project, I'm wondering why this is a required artifact? If I don't include the file I get the log below in the console, but other than that everything else seems to be working fine.

```
ERROR 22111 --- [io-8080-exec-10] org.pf4j.CompoundPluginDescriptorFinder  : Cannot find 'plugin.properties' path
```

**Comment by decebals** [comment]
If the plugin's properties are defined in `MANIFEST.MF` (via pom.xml) you don't need `plugin.properties`.
`CompoundPluginDescriptorFinder` tries to find the plugin's properties (descriptor) first in properties file and after this in MANIFEST.MF. Log ` Cannot find 'plugin.properties' path` as an error is an mistake in this case, a debug message is better. I will try to improve this aspect in the future.

**Comment by nonnamon** [comment]
Also, if a sub directory exists in plugins dir same error reported i.e. attempts to find a plugin.properties for the sub dir

**Comment by nonnamon** [comment]
if the plugins directory contains a subdirectory that subdirectory seems to be attempted to be loaded as a plugin, leading to the missing plugin.properties file error log. e.g.: given filesystem .\plugins\subdir\

` 
 public static void main(String[] args) {
        PluginManager pm = new DefaultPluginManager(Paths.get("plugins"));
        pm.loadPlugins();
    }

`
gives log:

`
2018-05-08 10:20:30,635 [INFO |   main|PluginStatusProvider] - Enabled plugins: []
2018-05-08 10:20:30,635 [INFO |   main|PluginStatusProvider] - Disabled plugins: []
2018-05-08 10:20:30,635 [INFO |   main|DefaultPluginManager] - PF4J version 2.2.0 in 'deployment' mode
2018-05-08 10:21:49,725 [ERROR|   main|uginDescriptorFinder] - Cannot find 'plugins\subdir\plugin.properties' path
2018-05-08 10:21:49,725 [ERROR|   main|uginDescriptorFinder] - Cannot find the manifest path
2018-05-08 10:21:49,725 [ERROR|   main|bstractPluginManager] - No PluginDescriptorFinder for plugin 'plugins\subdir'
org.pf4j.PluginException: No PluginDescriptorFinder for plugin 'plugins\subdir'
	at org.pf4j.CompoundPluginDescriptorFinder.find(CompoundPluginDescriptorFinder.java:78)
	at org.pf4j.AbstractPluginManager.loadPluginFromPath(AbstractPluginManager.java:820)
	at org.pf4j.DefaultPluginManager.loadPluginFromPath(DefaultPluginManager.java:141)
	at org.pf4j.AbstractPluginManager.loadPlugins(AbstractPluginManager.java:227)
	at scratch2.Scratch2.main(Scratch2.java:23)
`

[scratch2.zip](https://github.com/pf4j/pf4j/files/1981952/scratch2.zip)

**Comment by decebals** [comment]
@nonnamon 
> if the plugins directory contains a subdirectory that subdirectory seems to be attempted to be loaded as a plugin, leading to the missing plugin.properties file error log

In such particular situations please use a concrete `PluginDescriptorFinder` like I described in my previous comment. If you are not happy with the built in implementations you can override it or write an implementation from scratch.

**Comment by nonnamon** [comment]
while it's good that the built in implementation can be over riden, could you clarify why the default should be to attempt to load directories as a plugins - is it at all possible for a directory to be a plugin? Why does DefaultPluginRepository.pluginsFilter include a DirectoryFileFilter?

**Comment by decebals** [comment]
> Could you clarify why the default should be to attempt to load directories as a plugins - is it at all possible for a directory to be a plugin? Why does DefaultPluginRepository.pluginsFilter include a DirectoryFileFilter?

Yes, it's possible and very useful in `development` mode (start application with `-Dpf4j.mode=development`) when I can run the application along with all plugins if I have the structure presented in demo application (all plugins are under `plugins` directory).

**Comment by decebals** [comment]
If you use only jars as plugins (no zip files, no directories), then you should use something like

```java
PluginManager pluginManager = new DefaultPluginManager() {

    @Override
    protected PluginLoader createPluginLoader() {
        // load only jar plugins 
        return new JarPluginLoader(this);
    }

    @Override
    protected PluginDescriptorFinder createPluginDescriptorFinder() {
        // read plugin descriptor from jar's manifest 
        return new ManifestPluginDescriptorFinder();
    }

};
```

**Comment by PawanDalal** [comment]
Reached here as I saw this in my error log. In my case, the plugin description is added in manifest and plugin.properties is not used.
