### ISSUE TITLE
Calling a JavaFX-Application with FXML as Plugin

### ISSUE THREAD

**Issue by michooo** [pf4j/pf4j#212]
Hello Community,

First of all thank you for this great framework!

I’m trying to load a JavaFX-Application as plugin. The JavaFX Project is with a FXML-File and a Controller Class (MVC-Pattern). Java 8u162.

When I’m trying to load the FXML-File from the Plugin (FXML located in the JAR), then the Exception `javafx.fxml.LoadException` is thrown. The exceptions says that the Controller-Class (defined in the FXML-File) cannot be found. It seems that my Plugin is not added to the Classpath and that’s why the FXML-Loader cannot initiate the Controller-Class.

So I tried to add the Plugin-Jar manually to the Classpath with the following hack:
```
Method method = URLClassLoader.class.getDeclaredMethod("addURL", new Class[] { URL.class });
method.setAccessible(true);
method.invoke(ClassLoader.getSystemClassLoader(), new Object[] { pluginManager.getPlugins().get(0).getPluginPath().toFile().toURI().toURL() });
```

After that, the Plugin can find all Controller-Classes. Now the plugin can be started without any exceptions.

So far all great.  I can load the FXML-File and instantiate the Controller-Class. But when I now try to cast the instantiate Controller-Object to the implemented Object, then a ClassCastException is thrown.

Like:
```
Object o = fxmlLoader.getController();
TestViewController t = (TestViewController) o; 
```
Output the object to console: `System.out.println(o);`
`Object o: ch.test.javafx.content.controller.TestViewController@b2dc9d9`

Exception of the Class Cast: 
```
Caused by: java.lang.ClassCastException:
ch.test.javafx.content.controller.TestViewController cannot be cast to ch.test.javafx.content.controller.TestViewController
```

Any idea about that behavior??

My questions according the Classpath: Why is the plugin-jar not automatically added to the Classpath? Do you provide any methods to do that automatically by your framework?

Do you provide any examples to generate a ZIP instead of a JAR? Or must this be generated by IDE? By the way, I'm using Gradle for JAR generating and that works perfectly!

**Comment by michooo** [comment]
So I just want to inform that I have found a perfect solution, thanks to the Class `PluginWrapper`.

For those who need to load files inside the Plugin-JAR with JavaFX:

```
FXMLLoader fxmlLoader = new FXMLLoader(getClass().getResource("/fxml/test.fxml"));
fxmlLoader.setClassLoader(pluginWrapper.getPluginClassLoader());
fxmlLoader.setResources(ResourceBundle.getBundle("language.messages", new Locale("DE")));

try {
   VBox node = (VBox) fxmlLoader.load();
   // When Controller-Class is specified inside FXML
   TestController controller = fxmlLoader.getController();
} catch (IOException e) {
   e.printStackTrace();
}
```

**Comment by decebals** [comment]
> Do you provide any examples to generate a ZIP instead of a JAR? Or must this be generated by IDE? By the way, I'm using Gradle for JAR generating and that works perfectly!

https://github.com/pf4j/pf4j/tree/master/demo_gradle

**Comment by decebals** [comment]
@michooo
Do you have a resolution for this issue? Can we close it?
