### ISSUE TITLE
External Dependency within Plugin

### ISSUE THREAD

**Issue by H43r1c** [pf4j/pf4j#214]
I've attempted to extend plugin2 of the demo app to use a MySQL connector, however, even though the plugin has a lib folder with the appropriate connector, the host application can not find the lib at run time.

I have written at test application that does not include the plugin and of course the driver is found.  The documentation is unclear about how to integrate libraries that are only used by the plugins and not the host application.

Included is both the plugin extension and the trace output from the host.   Can anyone see why the plugin is not able to see the MySQL library at run-time?  It does show in the log that it finds it in the lib folder per the documentation.

(I don't care about the ".settings" plugin failure as that shouldn't have a bearing on this issue)

[HelloPlugin.java.txt](https://github.com/pf4j/pf4j/files/1947103/HelloPlugin.java.txt)

[pf4j.mysql.txt](https://github.com/pf4j/pf4j/files/1947080/pf4j.mysql.txt)

**Comment by decebals** [comment]
You need to load MySql driver before open a connection to database
```java
Class.forName("com.mysql.jdbc.Driver");
```

**Comment by H43r1c** [comment]
Thank you, decebals, that stopped the exception but can you elaborate on why I would need to do that?

For others who, like myself, are new to plugin frameworks this behavior is not intuitive and the documentation is very slim when it comes to using external libraries.

Is there some aspect of this that is being taken for granted as common knowledge?

**Comment by decebals** [comment]
@H43r1c 
It's not related to PF4J.
https://stackoverflow.com/questions/22384710/java-sql-sqlexception-no-suitable-driver-found-for-jdbcmysql-localhost3306

**Comment by H43r1c** [comment]
Ok, thank you.
