### ISSUE TITLE
java.lang.ClassCastException: com.example.Entity cannot be cast to com.example.Entity

### ISSUE THREAD

**Issue by fddOs** [pf4j/pf4j#216]
I used pf4j-spring-0.4.0, I used springboot and mybatis in the plugin package, and there was a ClassCastException when using the object returned by mybatis. Here is my code.

ExtensionPoint:
```
public interface JobPlugin extends ExtensionPoint {
	void execute(String jobName) throws Exception;
}

```
plugin:
```
public class JobExecute extends SpringPlugin {
	private static Logger logger = LoggerFactory.getLogger(JobExecute.class);

	public JobExecute(PluginWrapper wrapper) {
		super(wrapper);
	}

	@Override
	public void start() {
		logger.info("HelloPlugin.start()");
	}

	@Override
	public void stop() {
		logger.info("HelloPlugin.stop()");
		super.stop();
	}

	@Override
	protected ApplicationContext createApplicationContext() {
		AnnotationConfigApplicationContext applicationContext = new AnnotationConfigApplicationContext();
		applicationContext.setClassLoader(getWrapper().getPluginClassLoader());
		applicationContext.scan("com.package");
		applicationContext.refresh();
		return applicationContext;
	}

	@Extension(ordinal = 1)
	public static class JobPluginImpl implements JobPlugin {

		@Autowired
		private Jobs jobs;

		@Override
		public void execute(String jobName) throws Exception {
			try {
				Method method = jobs.getClass().getMethod(jobName);
				ReflectionUtils.invokeMethod(method, jobs);
			} catch (Exception e) {
				logger.error(jobName, e);
				throw e;
			}
		}

	}

}
```

Mybatis config:I set mybatis' default class loader to this.getClass().getClassLoad(). If I don't set MyBatis to use Thread.currentThread().getContextClassLoader(), ClassNotFoundException will appear, and the POJO in the plugin package cannot be found.
```
@Configuration
@MapperScan("com.package.mapper")
public class MybatisConfigurer {
	@Bean
	public SqlSessionFactory sqlSessionFactoryBean(DataSource dataSource) throws Exception {
		Resources.setDefaultClassLoader(this.getClass().getClassLoader());
		SqlSessionFactoryBean factory = new SqlSessionFactoryBean();
		factory.setVfs(SpringBootExecutableJarVFS.class);
		ResourcePatternResolver resolver = new PathMatchingResourcePatternResolver();
		factory.setDataSource(dataSource);
		factory.setMapperLocations(
				resolver.getResources(getClass().getClassLoader().getResource("mysql/mapper/") + "*.xml"));
		return factory.getObject();
	}
}
```
I use the plugin package code:
```
PluginManager pluginManager = new SpringPluginManager();
		pluginManager.loadPlugin(path);
		pluginManager.startPlugins();
		List<JobPlugin> jobPlugins = pluginManager.getExtensions(JobPlugin.class);
		try {
			jobPlugins.get(0).execute(params[1]);
			return ReturnT.SUCCESS;
		} catch (Exception e) {
			Logger.log(ExceptionUtils.getFullStackTrace(e));
			return ReturnT.FAIL;
		} finally {
			pluginManager.stopPlugins();
			pluginManager.unloadPlugin(pluginManager.getPlugins().get(0).getPluginId());
		}
```

Thrown an exception code:
```
public void cancelTimeoutOrder() {
                //Mybatis generates the query result object
		List<OrderOperator> orderList = orderoperatorMapper.selectBookTimeoutOrder();
		orderList.forEach(orderOperator-> {
			//This throws a ClassCastException:com.package.entity.OrderOperator can not cast to com.package.entity.OrderOperator
		 #});
	}
```

**The above problem occurs when I call the plugin package multiple times at the same time in the code.**
**I found this answer on StackOverflow:https://stackoverflow.com/a/20199355**
But I don't know how to solve it. . . can you help me?
@decebals

**Comment by decebals** [comment]
I think that your problem is described in https://github.com/pf4j/pf4j/issues/82.
In few words, you have a jar in the main app class loader and in a plugin class loader also.

**Comment by fddOs** [comment]
I saw gitblit's answer in #82 : If you have a type Foo referenced by two classloaders, Foo is not instance-compatible between the two classloaders - leading to your not assignable error. The only time this works is when the second classloader is a child of the first one AND it inherits/shares the parent classloader. So,should I make all class loaders in the plugin package inherit the pf4j class loader? @decebals

**Comment by decebals** [comment]
>So,should I make all class loaders in the plugin package inherit the pf4j class loader?

I don't understand entirely your above sentence.
In your app, when you need to deal with class loader, you can use one of three types of class loaders:
- app's class loader
- plugin's class loader (a plugin's class loader has as parent the app's class loader)
- a compound/uber/global class loader that aggregates all the plugin's class loader

From the title of the issues I understand that you have the same jar (app.jar) in app\lib and also in plugin1\lib and that is not good.
