### ISSUE TITLE
Cannot remove plugin jar file after unloading

### ISSUE THREAD

**Issue by jgomer2001** [pf4j/pf4j#217]
Hi, 
I'm using pf4j 2.2.0 maven dependency in my project. My web app allows an administrator user to add and drop plugins at runtime. These are the steps to "add" a plugin:

1. A .jar file is selected in the UI and uploaded to server
1. A call to `loadPlugin` is issued by passing the path where jar was stored
1. Plugin features are shown in the UI (basically the info found in the plugin descriptor)
1. The admin determines whether to onboard this plugin or reject it.

When the plugin is accepted I simply call `start` method and all is fine. When the user rejects it, I do call `unloadPlugin`, but then I need to remove the corresponding jar file. Here's what I am getting:

```
java.nio.file.FileSystemException: ...file.jar: The process has no access to the file because it's being used by another process
	...
	at java.nio.file.Files.delete(Files.java:1126) ~[?:1.8.0_65]
```

Seems very similar to [this](https://github.com/pf4j/pf4j/pull/197) which was closed months ago. 

Any idea on how to workaround it?

Thanks.

**Comment by jgomer2001** [comment]
Similarly, if I already have a plugin started and make a call to `stop` and finally to `delete` , I get the same error.

**Comment by decebals** [comment]
Sorry for delay. I will investigate your problem. Can you isolate the issue in a simple (quickstart) application/project? I try to reproduce the issue.

**Comment by jgomer2001** [comment]
Hi, I coded  a minimalistic example, and it's embarrassing... it works perfectly

In my app I am doing some other custom manipulation of plugin jars for a variety of reasons, however it seems I need to double check if some stream is not getting closed there.  I think you may close this issue.

Thanks for your help

**Comment by decebals** [comment]
I suppose that your application runs on an Windows machine. Is it correct?

**Comment by jgomer2001** [comment]
yes... any tip to workaround this weird behaviour?

I skipped in my code the part where I was reading the jar file. Now the call to `Files.delete` does not complain, but the file is not deleted actually!. Only after I stop the webapp the file disappears :O

**Comment by decebals** [comment]
> Hi, I coded a minimalistic example, and it's embarrassing... it works perfectly

Is it still valid this affirmation?

Do you use somehow the new jar file in your scenario (load classes from jar)?

**Comment by decebals** [comment]
What servlet container (Jetty, Servlet, ...) and web framework are you using?

**Comment by jgomer2001** [comment]
jetty 9.4, ZK framework

**Comment by decebals** [comment]
Thanks! I think that you application is https://github.com/GluuFederation/cred-manager.
Can you put PF4J's log level on DEBUG (or better on TRACE)? In this mode you have enough information. After this change in log config, please take a look of your log and pay attention to threads (what thread deals with PF4J actions - load, start, stop).

**Comment by decebals** [comment]
> In the case of the webapp the load/unload/delete jar does not throw any exception (if the operations are executed in that sequence in the code), but the file only disappears when the servlet container is stopped. 

In the end I think that this behavior could be OK or or in the worst case acceptable. 
Many applications like Eclipse and Jenkins is restarted automatically after a plugin is installed and uninstalled. 
Only OSGI claims that it can started, stopped, updated, and uninstalled plugins (bundles) without requiring a reboot.

**Comment by jgomer2001** [comment]
Thanks a lot for your suggestions

**Comment by decebals** [comment]
> This is achievable in cred-manager too as pf4j allows me to unload plugins with no problem. I simply dont' delete any files but maintain a mapping of pluginid/filename with the alive plugins so far. When the app is restarted I remove all unknown jar files. And when uploading a plugin (which is done via UI - a file chooser), I copy the jar to the server adding a small random suffix to file name.
> 
> This workarounds the problem and works very nice.

Interesting your approach. 👍

**Comment by jgomer2001** [comment]
Let me close it...
