### ISSUE TITLE
It should not return null after it detects that the plugin has been loaded

### ISSUE THREAD

**Issue by JiaRG** [pf4j/pf4j#218]
https://github.com/pf4j/pf4j/blob/f80bc959c133ea10edb38510e0f3a4580b9358ac/pf4j/src/main/java/org/pf4j/AbstractPluginManager.java#L811
If null is returned, a null pointer exception will occur here
https://github.com/pf4j/pf4j/blob/f80bc959c133ea10edb38510e0f3a4580b9358ac/pf4j/src/main/java/org/pf4j/AbstractPluginManager.java#L193

Should the return loaded PluginWrapper using getPlugin(String pluginId) method?

**Comment by decebals** [comment]
I understand what you say, but if we do the modifications according to your recommendation (return `PluginWrapper` in `loadPluginFromPath` when someone try to load a plugin multiple time), we don't have a "real" feedback if we loaded or not the plugin from path. The behavior is the same if you loaded a new plugin from a disk path or you tried to load a plugin multiple times.
What about if we throw a `PluginException` with the message `"Plugin '{}' already loaded with id '{}'", pluginPath, pluginId`?
Also, I am curios to know other opinions from other people.

**Comment by JiaRG** [comment]
Well, I agree with you and throw a PluginException, such as RepeatLoadPluginException.

**Comment by decebals** [comment]
I added `PluginAlreadyLoadedException`. 
We can evolve this `PluginException` hierarchy and add other subclasses like: `PluginNotFoundException`, `InvalidPlugin(Descriptor)Extension`, ... 
I don't know, it can be a good idea.
