### ISSUE TITLE
Usage of API interfaces in plugin project

### ISSUE THREAD

**Issue by jvaca92** [pf4j/pf4j#220]
Hello,

I am the new newbie at your project and have to say that I really like. In your demos I can see that your project hierarchy consist from api, app and plugins where I consider that the project app is just optional. If I do copy of your demo and run maven build, the extensions are correctly generated in extenisons.idx file, which work great. But when I move all interfaces from the project api into plugin project and want generated extensions which their interfaces are actually located in plugin project and not in api project, then the extensions.idx file is empty but exist and is genereated with the comment in META-INF of the plugin jar. Have to be done some configuration of POM file or the projects hierarchy is stricly assemble for this kind generating process of the extensions ? 

Thank you very much.

**Comment by decebals** [comment]
>  I consider that the project app is just optional. 

Do you want to say "api" project?

Can you make public (on your Github's account) your project derived from demos? It's much easy for me to understand and test. Thanks!

**Comment by jvaca92** [comment]
I have prepared the test repo see [pf4j-extension-test](https://github.com/jvaca92/pf4j-extension-test) where I have used your demo. In project of plugin 2 I have created new package with name [test](https://github.com/jvaca92/pf4j-extension-test/tree/master/plugins/plugin2/src/main/java/org/pf4j/demo/hello) where I put my own test extension. But when I run maven build, my extension is not generated into extension.idx. My goal is to reach if possible to generated extension which have own implementation and interface in any plugin project.

**Comment by decebals** [comment]
I think that your problem is that `InfoService` doesn't extends `ExtensionPoint` so, your interface is not marked as extension point.

**Comment by decebals** [comment]
Any resolution? Do you need more help? Can you close this issue?

**Comment by jvaca92** [comment]
I have apologized for the delayed. I can confirm that the interface InfoService need to be extended with the interface ExtensionPoint. After run maven install the InfoServiceImpl is generated into the extension.idx file. 
Thank you very much for your help. Really appreciate it.
