### ISSUE TITLE
Possible bug in ExtensionAnnotationProcessor | copying data to from an old map

### ISSUE THREAD

**Issue by A4Vision** [pf4j/pf4j#224]
At this line:
https://github.com/pf4j/pf4j/blob/c421a3b4e02822d65252b868ecbef3d1a0b09fd8/pf4j/src/main/java/org/pf4j/processor/ExtensionAnnotationProcessor.java#L126
We copy data from an old map to a new map.
We copy a pointer to ```Set<String>```. Therefore, when the new map is updated,
then the old map is updated as well. The old map is accessible here
https://github.com/pf4j/pf4j/blob/c421a3b4e02822d65252b868ecbef3d1a0b09fd8/pf4j/src/main/java/org/pf4j/processor/ExtensionAnnotationProcessor.java#L164

**Comment by decebals** [comment]
This is the kind a situation that I wish to avoid.
We talked in particular, in context of https://github.com/pf4j/pf4j/pull/225. 
You (or an automatic process) propose some modifications without to know the context. It's something statically. Sure, the rule used by you make sense from theoretical point of view but in this particular example, the map will never be updated. The map is used only to read some values.
