### ISSUE TITLE
Dynamic load/unload of Plugins

### ISSUE THREAD

**Issue by sashank** [pf4j/pf4j#226]
Am considering using pf4j for one of my project , it really looks simple and great way of building plugin based apps ! 

Is there a dynamic load/unload of plugins possible ? without restarting the application  ?
I read some work being done on this area 
https://groups.google.com/forum/#!topic/pf4j/Mc4ogfGHGmA

but any updates on the same ?

**Comment by decebals** [comment]
Useful links:
- https://github.com/pf4j/pf4j/issues/217#issuecomment-391326877
- https://github.com/pf4j/pf4j-update/issues/35
- https://github.com/pf4j/pf4j-update/issues/27

I always force a restart application after I add/remove/update a plugin. Some people succeed without restart (see last comments from https://github.com/pf4j/pf4j/issues/217).

**Comment by sashank** [comment]
Thanks will experiment a bit and get back
