### ISSUE TITLE
Transferring Plugin results back to App

### ISSUE THREAD

**Issue by sashank** [pf4j/pf4j#227]
Any recommendations / best practices for returning the results of each plugin ? for example a plugin parses web page to retrieve product information , what are the choices to get those "products" info in our application ?

**Comment by decebals** [comment]
> Any recommendations / best practices for returning the results of each plugin ?

I don't understand your question.

> for example a plugin parses web page to retrieve product information

A plugin from PF4J is like a module from other systems. The plugin comes with contributions (extensions) to your application. A plugin cannot parse a web page. It can come with an extension (an implementation of your `PageParser`) that parse a web page. 
```java
public interface PageParser implemnts ExtensionPoint {
    Result parse(InputStream input);
}
```
In your application you can retrieve the implementation via `pluginManager#getExtensions(PageParser.class)`, call `pageParser#parse` and use the result as you wish.

By the way, I think that [Sparkler](https://github.com/USCDataScience/sparkler) a web crawler uses PF4J, so you can take a look maybe can help you.

**Comment by sashank** [comment]
Yeah got it thanks !  spent some more time on plugins with my team , its clear now :-)
