### ISSUE TITLE
Can't find plugin.properties file inside .jar

### ISSUE THREAD

**Issue by dustContributor** [pf4j/pf4j#229]
I got a plugin .jar that looks like:

```
META-INF
main/Main.class
plugin.properties
.classpath
```

pf4j finds the .jar inside my plugins folder just fine, then tries to run the descriptor finders. First one is the properties descriptor finder, which is the one I want, but when it's time to fetch the descriptor, it fails in this line:

https://github.com/pf4j/pf4j/blob/master/pf4j/src/main/java/org/pf4j/util/FileUtils.java#L231

With a file system not found exception. The passed URI looks like this:
```
jar:file:/res/plugins/testPlugin.jar
```
Which is correct, relative to the project's execution path.

Since that one fails, it runs the manifest finder, which also fails since I'm trying to use plugin.properties instead.

**Comment by decebals** [comment]
I will take a look. Maybe we can create a test unit for regression.

**Comment by decebals** [comment]
I cannot reproduce the problem.
Actually, we have a [unit test](https://github.com/pf4j/pf4j/blob/c421a3b4e02822d65252b868ecbef3d1a0b09fd8/pf4j/src/test/java/org/pf4j/PropertiesPluginDescriptorFinderTest.java#L109) for this kind of problem, which passes successfully.
Can you add more information like the log file (with pf4j on debug)?

**Comment by decebals** [comment]
> jar:file:/res/plugins/testPlugin.jar

Does the `/res/plugins` folder exist? Is that the absolute path?

**Comment by dustContributor** [comment]
Hm, now I  went on and tried other things in the middle so I lost exactly what I was doing there. But I'm pretty sure I set up the contents of the .jar were wrong, I've set it up correctly (I think) and now the .jar works fine, I can load extensions from it correctly.

... But I have other issue now :smile: It fails exactly in the same line, for other reasons:

```java
var pluginManager = new DefaultPluginManager( pluginsRoot );
pluginManager.loadPlugins();
pluginManager.startPlugins();

var plugin = pluginManager.getPlugins().get( 0 );

pluginManager.getExtensions( TestExtension.class )
		.stream()
		.map( TestExtension::name )
		.forEach( System.out::println );

pluginManager.stopPlugin( plugin.getPluginId() );
pluginManager.unloadPlugin( plugin.getPluginId() );

pluginManager.loadPlugins(); // <-- fails here
pluginManager.startPlugins();

pluginManager.getExtensions( TestExtension.class )
		.stream()
		.map( TestExtension::name )
		.forEach( System.out::println );
```
This is loading a plugin, doing things with it, unloading it, and loading it again.

On second load, everything goes fine until that same exact line:

https://github.com/pf4j/pf4j/blob/master/pf4j/src/main/java/org/pf4j/util/FileUtils.java#L231

Except this time it fails with FileSystemAlreadyExistsException, since it has been created before on the first load.

I think in this case something like this can be more reliable:

```java
public static Path getPath(URI uri, String first, String... more) throws IOException {
	FileSystem fileSystem = null;
	try {
		// Check if the file system was already loaded for this URI.
		fileSystem = FileSystems.getFileSystem(uri);
	} catch (FileSystemNotFoundException e) {
		// Ignore.
	}
	if(fileSystem == null) {
		// File system wasn't loaded, try make a new one.
		fileSystem = FileSystems.newFileSystem(uri, Collections.<String, String>emptyMap());
	}
	return fileSystem.getPath(first, more);
}
```

What do you think?

**Comment by decebals** [comment]
@dustContributor 
First of all I want to say that it's not OK to call two time `loadPlugins` and `startPlugins`:
```java
pluginManager.loadPlugins(); // <-- fails here
pluginManager.startPlugins();
```

PF4J is not designed to work in this mode. I think that I will add some protection (flags) to avoid this situation.

The correct sequence is:
```java
// load and start (all) plugins
pluginManager.loadPlugins();
pluginManager.startPlugins();

// unload a plugin
pluginManager.stopPlugin(plugin.getPluginId()); // this line is optional; unloadPlugin() calls automatically stopPlugin
pluginManager.unloadPlugin(plugin.getPluginId());

// load and start a plugin
pluginManager.loadPlugin(plugin.getPluginPath());
pluginManager.startPlugin(plugin,getPluginId());
```

**Comment by dustContributor** [comment]
Hm, it still fails in the same place. The FileSystem already exists for that .jar so the  FileSystems.newFileSystem call fails anyway.

**Comment by decebals** [comment]
I will add in few minutes the fix proposed by you, because it's useful.

**Comment by dustContributor** [comment]
Cool, thanks!

**Comment by dustContributor** [comment]
For anyone else that isn't using Maven like me, snapshots:

https://oss.sonatype.org/content/repositories/snapshots/org/pf4j/pf4j/

Seems to be working now, I can load the plugin, call some stuff on an extension, unload the plugin, load it again, and call stuff on the extension again just fine. I think this issue can be closed.

Thanks!

**Comment by svarma11** [comment]
Hi Its not able to find the plugin descriptor , but its the part of the jar, not moreover i am providing my path from where it has to look the plugin and it able to load but while trying to access the properties its looking into the c:/ and path which  i have provided
let's say i have given the path ./plugins  to the plugin manager and it is looking into c:/.plugins/ it should read it with the relative path

**Comment by svarma11** [comment]
> > jar:file:/res/plugins/testPlugin.jar
> 
> Does the `/res/plugins` folder exist? Is that the absolute path?

for me it's the relative path and folder and jar exist but instead looking into the relative path its looking into c://relative path

**Comment by decebals** [comment]
@svarma11 
What version of PF4J are you using?

**Comment by svarma11** [comment]
<groupId>org.pf4j</groupId>
			<artifactId>pf4j-spring</artifactId>
			<version>0.5.0</version>

**Comment by decebals** [comment]
> org.pf4j
pf4j-spring
0.5.0
I have added this dependency in my application

PF4J 2.x or 3.x?

**Comment by svarma11** [comment]
PF4j 2.3.0

**Comment by decebals** [comment]
Can you check please with PF4J 3.0.1 and pf4j-spring 0.6.0-SNAPSHOT?

**Comment by svarma11** [comment]
Thanks it's worked now able to load the properties
Thankyou decebals
