### ISSUE TITLE
Plugin with Oracle JDBC driver doesn't find lib

### ISSUE THREAD

**Issue by andip** [pf4j/pf4j#231]
I've created a plugin that uses Oracle JDBC driver (ojdbc8) for retrieving data from an Oracle database, but obviously pf4j doesn't load that driver from my plugins lib folder. Its the same issue as https://github.com/pf4j/pf4j/issues/214. I tried solution from given answer using `Class.forName ("oracle.jdbc.OracleDriver") ` and also `DriverManager.registerDriver (new oracle.jdbc.OracleDriver());` (from Oracle's JDBC documentation) inside my plugin, but don't have success using both. Still getting an error 
`java.sql.SQLException: No suitable driver found for "<connection string>"`. 
Is there a way to check if libraries were loaded properly? Does anyone else have same issue using Oracle driver?
If I execute the code inside my plugin project I don't run into this error.

**Comment by decebals** [comment]
Can you share a snippet from your code that uses the jdbc driver? The log file is useful also.
A tiny quickstart project that reproduce the problem will speed up finding a solution.

**Comment by decebals** [comment]
> Is there a way to check if libraries were loaded properly?

If you put the log of `PluginClassLoader` on debug you will see what jars/directories are added for a plugin. If you put the log of `PluginClassLoader` on trace you will see in details what classes is loaded.

**Comment by andip** [comment]
In following code snippet it runs into catch block. 
		`
                DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
		try (Connection conn = DriverManager.getConnection(connString, user, password)) {
                // processing data
		} catch (SQLException e) {
			LOGGER.debug("An error ocurred while trying to get data from source:", e.getMessage());
			e.printStackTrace();
		}
`

Unfortunately I have an issue getting log output from pf4j, obviously since I use **log4j2** as a logger. 
I get following output on my console (additionally to my applications log output):
`SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.`

**Comment by andip** [comment]
Issue can be closed, sorry! 
In main application I read the database parameters from properties file (user, password, connection string) and put the string into quotation marks. It seemed that it interpreted the quotation marks as part of the configuration parameters value which lead to this issue. In my plugin project I set the configuration parameters in my code for testing purposes, thus I didn't run into this issue.
