### ISSUE TITLE
DefaultPluginManager.deletePlugin(String pluginId) can't delete a plugin

### ISSUE THREAD

**Issue by HJacco** [pf4j/pf4j#238]
I am studying this wonderful framework, and I find that when I call DefaultManager's deletePlugin method, the program throw a excetion that describe "java.nio.file.FileSystemException: another processor is using this file",  I think it must be the classloader didn't release the resource really

**Comment by decebals** [comment]
What version of PF4J are you using?
Maybe https://github.com/pf4j/pf4j/issues/217 can help.

**Comment by HJacco** [comment]
I run the demo app, and I call delete method at the end of Main method, it throw the exception;
I scan the issue #217 , I got a piece of information that when the app run on windows, it can't call delete method?

**Comment by decebals** [comment]
I will try to reproduce the problem based on your last comment (I will call delete method at the end of main method). Can you share the snippet code with your modifications, to be sure that I do the same modifications? I develop on Linux so it's possible to not reproduce the problem.

**Comment by HJacco** [comment]
![3 6 5xtgksrl xo i4wc862](https://user-images.githubusercontent.com/11569147/44070431-69322f36-9fb6-11e8-9cf9-aa68a7db9f79.png)
please see this picture

**Comment by loblanch** [comment]
I have an use case : if the plugin isn't loaded initially, I can install and uninstall without error, if the plugin is loader when the application start, the file is lock and I got the error. I use Spring-boot-2.0.5.RELEASE, pf4j-Spring-0.5.0.Snapshot, pf4j-2.4.0 on Windows 10 ;-) .

**Comment by decebals** [comment]
@loblanch On demo project also? Can you attach a quickstart project (a runnable tiny project in a zip file)?
I work on Linux but I think that I can find a Windows box. The problem is that I don't have to much time, so make something easy to run (if it's not demo project, of course).

**Comment by loblanch** [comment]
hum I founded something interresting, I remove the load/start from the init() of SpringPluginManager class, and put these 2 lines in a worker thread on the side after the postConstruction step. All work fine, I'm able to uninstall plugin in loading repository.... I'll do the PR in the pj4j-Spring.

**Comment by decebals** [comment]
@HJacco 
> please see this picture

Don't run the modification on Linux because it will remove the `plugin1` directory entirely :smile: .

**Comment by hptvl** [comment]
Is there any update for this issue? I got same problem in latest version. Currently I am using spring boot 2.0.4, pf4j 2.4 without pf4j-spring, testing on Windows 10. I also tried load/start plugin from init() of spring bean and even load/start when running thread but didn't work. The plugin jar file will be deleted when I terminate java app.

**Comment by hptvl** [comment]
> @hptvl
> 
> > ... but didn't work.
> 
> Is this means that you got an exception?
It's not an exception. Actually, it run successfully however, the plugin file is still there and I could not replace it by new one  (same name).

> 
> > The plugin jar file will be deleted when I terminate java app.
> 
> That means that it's work, no? The `deletePlugin` method deletes the jar in the end.

Is there any way to delete it right after running `deletePlugin`? In my project, I have to update the new plugin version by replacing new file and for sure, the main app could not be restarted when updating new plugin.

**Comment by jgomer2001** [comment]
@hptvl 

My best bet this is an issue of Java in Windows not pf4j. I faced similar (#217) but once in test/production linux environment, it simply does not show up.

**Comment by marcelotomazini** [comment]
Windows 10 doesn't allow you to remove an opened file.
Try to close your jar file before.

`Path pluginPath = plugin.getPluginPath();
File file = pluginPath.toFile();
		
URL jarUrl = new URL("jar", "", -1, file.toURI().toString() + "!/");
URLConnection connection = jarUrl.openConnection();
((JarURLConnection)connection).getJarFile().close();`

**Comment by decebals** [comment]
The problem was solved in PF4J 3.
