### ISSUE TITLE
Doc bug for ClassLoader to address singleton issue.

### ISSUE THREAD

**Issue by p4paul** [pf4j/pf4j#241]
I am getting multiple instance of my singleton loaded for each plugin. I was looking to see if I could change the class loader to resolve this, however the example in documentation is not valid (perhaps out of date):

https://pf4j.org/doc/class-loading.html

**Comment by decebals** [comment]
Yes, I are right.
It's a method [loadPlugin](https://github.com/pf4j/pf4j/blob/c421a3b4e02822d65252b868ecbef3d1a0b09fd8/pf4j/src/main/java/org/pf4j/PluginLoader.java#L35) in PluginLoader. This method must return the same `ClassLoader` for any plugin.

You must override [DefaultPluginManager.createPluginLoader](https://github.com/pf4j/pf4j/blob/5587adb63ae7a51397196f28d3a97d579b04542a/pf4j/src/main/java/org/pf4j/DefaultPluginManager.java#L92).

You can override [DefaultPluginLoader.createClassLoader](https://github.com/pf4j/pf4j/blob/c421a3b4e02822d65252b868ecbef3d1a0b09fd8/pf4j/src/main/java/org/pf4j/DefaultPluginLoader.java#L57) method also.

**Comment by p4paul** [comment]
Thanks for the quick reply - I'll give that override a go.

**Comment by decebals** [comment]
@p4paul 
Please share with us the result and your experience. Any idea about how to make PF4J more powerful and user friendly is welcome.

**Comment by decebals** [comment]
@p4paul 
I know that you solved the problem. Do you need more information? If the response is no, close this issue please.

**Comment by p4paul** [comment]
Thank you - nothing to add so closing the issue.
