### ISSUE TITLE
can extension add name attribute

### ISSUE THREAD

**Issue by zhaoyta** [pf4j/pf4j#245]
can extension add name attribute.
some times i have multi extension implement.
i select use which extension  on runtime . every time i have to scan extension class name to select.

it is very inconvenience.

**Comment by decebals** [comment]
Can you add more information please? Maybe some pseudo code.
In some of my application I have (probably) de same case as you.
In UI (user interface) I present a drop down (combo box) with a all extensions available for an extension point.
But it's the responsability of UI (rendering layer) to present a nice name.
For example, for demo project that comes with PF4J, for `Greeting` extension point we have three extensions available:
- `WelcomeGreeting` (from `plugin1`)
- `HelloGreeting` (from `plugin2`)

You can use [PluginManager#getExtensionClasses](https://github.com/pf4j/pf4j/blob/master/pf4j/src/main/java/org/pf4j/PluginManager.java#L136) to achive all extension classes for `Greeting` extension point.
Now, to display a nice list with all extensions you can use as extension name something like this (pseudo code):
```
extensionClass.getSimpleName().removeSuffix("Greeting");
```

In this case the displayed labels in list are: `Welcome` and `Hello`.
So, it's all about convention. In some projects I used "Extension" as suffix.

If the solution presented above it's not what you want, please add more information about your use case.

**Comment by zhaoyta** [comment]
my current way is similar to you .but user may be write some code to manage this extension.  these code can omit for user if framework supply to direct to extension method by simple name .

**Comment by decebals** [comment]
@zhaoyta 
And, do you have a clear technical proposal? Can you create a PR to talk more concrete?

**Comment by decebals** [comment]
In the end I think that the convention to have the extension ID (something unique in an application) equals with the class name (including the package name) is perfect. I think that a configuration approach vs convention is not a good idea in this case (it comes with a complexity that is not necessary).
A complete new `name` attribute can be a solution in some cases. In my projects that uses PF4J I didn't identified a such case. In the end, to display the extension name in UI maybe you need some i18n support.
