### ISSUE TITLE
Swing  and spring-boot example

### ISSUE THREAD

**Issue by jimmyMaci** [pf4j/pf4j#247]
Is there an example with a swing application and spring-boot?

**Comment by decebals** [comment]
@jimmyMaci 
Search in (closed) [issues](https://github.com/pf4j/pf4j-spring/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+boot) of [pf4j-spring](https://github.com/pf4j/pf4j-spring).
`pf4j-spring` is am extension of `PF4J`, it's a plugin framework for Spring based on PF4J.

**Comment by jimmyMaci** [comment]
@decebals thank you for the fast response.
For spring-boot there is an example. 
Is there a simple example with only Swing available?

**Comment by decebals** [comment]
@jimmyMaci 
We don't have an example (demo) with Swing but I do not see any difficulty in integrating PF4J with Swing. I think that someone posted that he succeeded to integrate PF4J with JavaFX.
