### ISSUE TITLE
OpenJDK and Java 11?

### ISSUE THREAD

**Issue by aadrian** [pf4j/pf4j#251]
Hi,

Does the project support OpenJDK and also Java 11?
If yes, could those please be added to the `travis.yml` file too?

Thank you.
P.S. The Travis build seems broken for the last month.

**Comment by decebals** [comment]
> Does the project support OpenJDK and also Java 11?

What exactly means support Java 11? To pass the compilation?
Is it the same question like ttps://github.com/pf4j/pf4j/issues/200 but for Java11?

**Comment by aadrian** [comment]
@decebals 
> What exactly means support Java 11? 

To work with Oracle JDK 11 and Open JDK 11 - since 11 is now the "latest stable LTS version of the JDK.

**Comment by decebals** [comment]
@aadrian 
I didn't tried. I use JDK 8 in my projects (personal and @work).
Maybe other persons can confirm for JDK9+;
If I have time I will install Open JDK 11 on my dev machine and I will try to [run demo](https://pf4j.org/doc/demo.html).

**Comment by ramafasa** [comment]
Hi @decebals,

Have you tried to run demo on Open JDK 11? What is the result?

I'm trying to run my project with OpenJDK (Zulu) and it fails on compilation of "extensions.idx".

**Comment by dvsanthosh** [comment]
@decebals , I'm seeing the issue reported by @ramafasa . Can you please look into this.?
Can you please speicify mvn -v and maven-compiler-plugin versions?


> In [#252 (comment)](https://github.com/pf4j/pf4j/issues/252#issuecomment-441600147), @Aquazus says:
> 
> > PF4J works perfectly with OpenJDK 11.

**Comment by Aquazus** [comment]
```
user@clicli:~$ mvn -v
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T20:41:47+02:00)
Maven home: /opt/apache-maven-3.6.0
Java version: 11.0.1, vendor: Oracle Corporation, runtime: /usr/lib/jvm/openjdk-11
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-42-generic", arch: "amd64", family: "unix"
```

maven-compiler-plugin version 3.8.0

**Comment by dvsanthosh** [comment]
Can you please try with the AdpotOpenJDK's jdk11?

**Comment by decebals** [comment]
Can we close this issue? Do you need more information or you encounter problems?
