### ISSUE TITLE
Unit test issue because plugins are loaded by their own classloaders

### ISSUE THREAD

**Issue by zxwing** [pf4j/pf4j#254]
Let me explain this issue by an example:

```java
package my.package;

public class PluginA extends Plugin {

     public String variable1;

}
```

The PluginA is packaged as a uber jar and loaded by PF4j when PluginManager.loadPlugins() called. However, in my unit test I want to access the `variable1` field of PluginA instance. It's like:

```java
import my.package.PluginA;

public class UnitTest {

    @Test
    public void test() {
        PluginA a = (PluginA) pluginManager.getPlugin("pluginId");
    }

}
```
This will lead to a CastException because the PluginA is loaded by its own classloader while `PluginA`  variable in the unit test refers to the class loaded by application classload which is the parent of PluginA's classloader. 

Is there a way to resolve this issue? Othewise I cann't figure out any method to write my unit tests for plugins.

**Comment by decebals** [comment]
@zxwing 
Thanks that you reported this problem. I will take a look and I will come back  with a response.

**Comment by decebals** [comment]
Please reopen the issue if it is still relevant.
