### ISSUE TITLE
setter for runtimeMode missing

### ISSUE THREAD

**Issue by WolfgangFahl** [pf4j/pf4j#257]
`AbstractPluginManager` curently has only `getRuntimeMode()` which expects to read a System.property to determine the runtime mode. 
For testing and debugging it would be much easier to simply set the RuntimeMode as in

```java
 public static class WorkAroundPluginManager extends DefaultPluginManager {

    public WorkAroundPluginManager() {
        setRuntimeMode(RuntimeMode.DEVELOPMENT);
    }

    @Override
    protected PluginLoader createPluginLoader() {
        // load only jar plugins
        return new JarPluginLoader(this);
    }

    @Override
    protected PluginDescriptorFinder createPluginDescriptorFinder() {
        // read plugin descriptor from jar's manifest
        return new ManifestPluginDescriptorFinder();
    }

  }
```

**Comment by decebals** [comment]
> AbstractPluginManager curently has only getRuntimeMode() which expects to read a System.property to determine the runtime mode.

The idea is that `runtimeMode` is immutable after you created the plugin manager. I don't want anyone to has the possibility to modify that flag from outside of PluginManager (for example a plugin developer).
We make some business that depends on this flag (see https://github.com/pf4j/pf4j/blob/master/pf4j/src/main/java/org/pf4j/AbstractPluginManager.java#L734). So, I think that you can do it via system property `pf4j.mode` (in code with `System.setProperty` or command line with `-Dpf4j.mode`) or override `DefaultPluginManager.getRuntimeMode`. Please also read https://pf4j.org/doc/development-mode.html.

**Comment by decebals** [comment]
Other possible solution is to add a non public (protected, ...) `setRuntimeMode` in `AbstractPluginManager`.
