### ISSUE TITLE
Can't open project as maven project in eclipse

### ISSUE THREAD

**Issue by WolfgangFahl** [pf4j/pf4j#258]
With a new fork of pf4j the project will not properly open when using eclipse 2018-09 (4.9.0).
The .classpath files seem not to be  compatible to a multi-module maven project

**Comment by WolfgangFahl** [comment]
Still the p4j module is not handled correctly. The issues seems to be that it has the same name as the main java project and that is not allowd in Eclipse.

**Comment by decebals** [comment]
Thanks! I don't use Eclipse so I don't know too much about Eclipse.

**Comment by meydominic** [comment]
It's the same with Visual Studio Code.
You are always getting the following error message:
![image](https://user-images.githubusercontent.com/2743382/56115254-48d79600-5f63-11e9-9976-acd21d926d4d.png)

So you wont get full IntelliSense feature.
