### ISSUE TITLE
annotation processor creates wrong files under certain conditions

### ISSUE THREAD

**Issue by pinhead84** [pf4j/pf4j#264]
I'm currently migrating my application from [JPF](http://jpf.sourceforge.net/) to pf4j and discovered a problem in the `ExtensionAnnotationProcessor` in combination with the `ServiceProviderExtensionStorage`.

I'm using the following pattern to define extension points and extensions:

![pf4j-extensions](https://user-images.githubusercontent.com/7954406/50482680-381d0780-09e8-11e9-8b47-f6d2a5551a5c.png)

In contrast to your examples there are abstract classes (`MainMenuAdapter`, `BootAdapter`) for each available extension point. The extensions are derived from these abstract classes instead of the extension point interfaces (`MainMenuExtensionPoint`, `BootExtensionPoint`). This gives a bit more flexibility, because later added methods in an extension point can be implemented in the abstract classes without the need of modifying the extension points in all plugins. From my experience in certain projects this is a quite common pattern - similar to the `java.awt.event.WindowListener` / `java.awt.event.WindowAdapter` approach in the Java classpath.

Basically this approach also works with pf4j. But the `ExtensionAnnotationProcessor` in combination with the `ServiceProviderExtensionStorage` doesn't behave as expected in this scenario. For the above scenario the following files are generated:

```
META-INF/services/com.example.api.BootAdapter
META-INF/services/com.example.api.MainMenuAdapter
```

Instead the `ExtensionAnnotationProcessor` should create these files:

```
META-INF/services/com.example.api.BootExtensionPoint
META-INF/services/com.example.api.MainMenuExtensionPoint
```

Because of this problem the `PluginManager` is not able to load the extensions by its interface via `pluginManager.getExtensions(BootExtensionPoint.class)`. Instead I would have to call `pluginManager.getExtensions(BootAdapter.class)`.

I'm going to propose a pull request with a possible workaround for this problem.

**Comment by decebals** [comment]
Thanks again for detailed explanation. Now, the case with adapters doesn't work. The adapters are see as extensions by PF4J.
Your approach proposed in #265 is good. The same approach I use in [Pippo](https://github.com/pippo-java/pippo/blob/b446c6debc8d9136c2b3e9ff4a8ee247dcdaf50f/pippo-server-parent/pippo-undertow/src/main/java/ro/pippo/undertow/UndertowServer.java#L63) to declare extensions.
So, after some reviews and comments, #265 will be merged and the issue will be resolved.
