### ISSUE TITLE
Your project decebals/pf4j is using buggy third-party libraries [WARNING]

### ISSUE THREAD

**Issue by FDU-SE-LAB** [pf4j/pf4j#274]
Hi, there!
We are a research team working on third-party library analysis. We have found that some widely-used third-party libraries in your project have major/critical bugs, which will degrade the quality of your project. We highly recommend you to update those libraries to new versions.    
We have attached the buggy third-party libraries and corresponding jira issue links below for you to have more detailed information.
  1  org.apache.commons commons-lang3 (demo_gradle/api/build.gradle,demo_gradle/plugins/plugin1/build.gradle,...)
  version: 3.5

  Jira issues:
  DateFormatUtilsTest.testSMTP depends on the default Locale
  affectsVersions:3.5
  https://issues.apache.org/jira/projects/LANG/issues/LANG-1126?filter=allopenissues
  Multiple calls of org.apache.commons.lang3.concurrent.LazyInitializer.initialize() are possible
  affectsVersions:3.4;3.5
  https://issues.apache.org/jira/projects/LANG/issues/LANG-1144?filter=allopenissues
  Performance regression due to cyclic hashCode guard
  affectsVersions:3.5
  https://issues.apache.org/jira/projects/LANG/issues/LANG-1229?filter=allopenissues
  StrBuilder#replaceAll ArrayIndexOutOfBoundsException
  affectsVersions:3.2.1;3.4;3.5
  https://issues.apache.org/jira/projects/LANG/issues/LANG-1276?filter=allopenissues
  NullPointerException in FastDateParser$TimeZoneStrategy
  affectsVersions:3.5
  https://issues.apache.org/jira/projects/LANG/issues/LANG-1285?filter=allopenissues
  RandomStringUtils random method can overflow and return characters outside of specified range
  affectsVersions:3.5
  https://issues.apache.org/jira/projects/LANG/issues/LANG-1286?filter=allopenissues
  RandomStringUtils#random can enter infinite loop if end parameter is to small
  affectsVersions:3.5
  https://issues.apache.org/jira/projects/LANG/issues/LANG-1287?filter=allopenissues
  WordUtils.wrap throws StringIndexOutOfBoundsException
  affectsVersions:3.5
  https://issues.apache.org/jira/projects/LANG/issues/LANG-1292?filter=allopenissues
  MethodUtils.invokeMethod throws ArrayStoreException if using varargs arguments and smaller types than the method defines
  affectsVersions:3.5
  https://issues.apache.org/jira/projects/LANG/issues/LANG-1310?filter=allopenissues
  MultilineRecursiveToStringStyle StackOverflowError when object is an array 
  affectsVersions:3.5
  https://issues.apache.org/jira/projects/LANG/issues/LANG-1319?filter=allopenissues
  LocaleUtils#toLocale does not support language followed by UN M.49 numeric-3 area code followed by variant
  affectsVersions:3.5
  https://issues.apache.org/jira/projects/LANG/issues/LANG-1320?filter=allopenissues
  ConstructorUtils.invokeConstructor(Class; Object...) regression
  affectsVersions:3.5;3.6
  https://issues.apache.org/jira/projects/LANG/issues/LANG-1350?filter=allopenissues

  2  commons-lang commons-lang (demo/plugins/plugin1/pom.xml)
  version: 2.6

  Jira issues:
  Remove unnecessary synchronization from registry lookup in EqualsBuilder and HashCodeBuilder
  affectsVersions:2.6
  https://issues.apache.org/jira/projects/LANG/issues/LANG-1230?filter=allopenissues
  LocaleUtils - DCL idiom is not thread-safe
  affectsVersions:2.6
  https://issues.apache.org/jira/projects/LANG/issues/LANG-803?filter=allopenissues
  Exception when combining custom and choice format in ExtendedMessageFormat
  affectsVersions:2.5;2.6
  https://issues.apache.org/jira/projects/LANG/issues/LANG-917?filter=allopenissues

  3  commons-lang commons-lang (demo/app/pom.xml)
  version: 2.4

  Jira issues:
  Fix case-insensitive string handling
  affectsVersions:2.4
  https://issues.apache.org/jira/projects/LANG/issues/LANG-432?filter=allopenissues
  StringEscapeUtils.escapeHTML() does not escape chars (0x00-0x20)
  affectsVersions:2.4
  https://issues.apache.org/jira/projects/LANG/issues/LANG-439?filter=allopenissues
  DateUtils.round doesn't work correct for Calendar.AM_PM
  affectsVersions:2.4
  https://issues.apache.org/jira/projects/LANG/issues/LANG-440?filter=allopenissues
  Lower Ascii Characters don't get encoded by Entities.java
  affectsVersions:2.4
  https://issues.apache.org/jira/projects/LANG/issues/LANG-448?filter=allopenissues
  Issue in HashCodeBuilder which only shows up under high load multi-threaded usage.
  affectsVersions:2.4
  https://issues.apache.org/jira/projects/LANG/issues/LANG-459?filter=allopenissues
  Ant build file does not include ReflectTestSuite
  affectsVersions:2.4
  https://issues.apache.org/jira/projects/LANG/issues/LANG-463?filter=allopenissues
  EqualsBuilder and HashCodeBuilder treat java.math.BigDecimal inconsistantly and break general contract of hashCode
  affectsVersions:2.4
  https://issues.apache.org/jira/projects/LANG/issues/LANG-467?filter=allopenissues
  JDK 1.5 build/runtime failure on LANG-393 (EqualsBuilder)
  affectsVersions:2.4
  https://issues.apache.org/jira/projects/LANG/issues/LANG-468?filter=allopenissues
  ExtendedMessageFormat: OutOfMemory with custom format registry and a pattern containing single quotes
  affectsVersions:2.4
  https://issues.apache.org/jira/projects/LANG/issues/LANG-477?filter=allopenissues
  parseDate cannot parse ISO8601 dates produced by FastDateFormat
  affectsVersions:2.4
  https://issues.apache.org/jira/projects/LANG/issues/LANG-530?filter=allopenissues
  DateFormatUtils.format does not correctly change Calendar TimeZone in certain situations
  affectsVersions:2.4
  https://issues.apache.org/jira/projects/LANG/issues/LANG-538?filter=allopenissues
  StringUtils replaceEach - Bug or Missing Documentation 
  affectsVersions:2.4
  https://issues.apache.org/jira/projects/LANG/issues/LANG-552?filter=allopenissues
  Javadoc wrong for StringUtils startsWith; startsWithIgnoreCase; endsWith and endsWithIgnoreCase
  affectsVersions:2.4
  https://issues.apache.org/jira/projects/LANG/issues/LANG-557?filter=allopenissues
  HashCodeBuilder reflectionAppend creates unnecessary copy of excludeFields
  affectsVersions:2.4
  https://issues.apache.org/jira/projects/LANG/issues/LANG-575?filter=allopenissues
  ExceptionUtils uses mutable lock target
  affectsVersions:2.4
  https://issues.apache.org/jira/projects/LANG/issues/LANG-584?filter=allopenissues
  ClassUtils.toClass(Object[]) throws NPE on null array element
  affectsVersions:2.4
  https://issues.apache.org/jira/projects/LANG/issues/LANG-587?filter=allopenissues

Sincerely~
FDU Software Engineering Lab
Jan 7th,2019

**Comment by decebals** [comment]
They are demo projects.
