### ISSUE TITLE
Migrate to Java 8

### ISSUE THREAD

**Issue by decebals** [pf4j/pf4j#281]
What you say about this move?
Are people that still use PF4J and Java 7?
The propose is for the next major PF4J version (3.x).

**Comment by RaiMan** [comment]
IMHO development should be with OpenJDK 11, with the build setting the source and target level to Java 8.

So for dev one can play with newer concepts, while assuring, that the artifacts can be used with Java 8 and later.

I am doing this with my project [SikuliX](https://github.com/RaiMan/SikuliX1), where I have on the list to use PF4J for an extension concept (hence I am watching the activities here ;-)

**Comment by decebals** [comment]
> IMHO development should be with OpenJDK 11, with the build setting the source and target level to Java 8.

This approach will be used in PF4J 3. However, I do not fully understand the benefit of this approach. From what I read in one post on reddit ([Writing Java12 and running using JRE8?](https://www.reddit.com/r/java/comments/b36y19/writing_java12_and_running_using_jre8/)), we cannot use a feature introduced in Java 9+ (for example the new `boolean isBlank()` method of `String` class). So, in this circumstance, where is the benefit to use Java 11 on development side?

**Comment by pinhead84** [comment]
> So, in this circumstance, where is the benefit to use Java 11 on development side?

That's a good question indeed. ;)

In general we can use language features introduced with Java 9+. But in this case we would need to implement the same class twice (for Java 9+ and Java 8) and configure the Multi-Release JAR file accordingly (similar to the `module-info.java` approach). I guess in most cases the additional work does not justify the outcome.

The only advantages I see so far:

- We can make use of the Java Module System.
- We can make use of improved development tools. For example Javadoc generates a nicer ([HTML 5 based](https://openjdk.java.net/jeps/224)) output with [search capability](https://openjdk.java.net/jeps/225).

But I must admit, the number of advantages is not very big. But on the other hand I don't see any disadvantages in using Java 11 for development.

**Comment by decebals** [comment]
What is important for me (things that are not features) for PF4J:
1. performance
2. few or no dependencies
3. small size
4. small footprint
5. readable, testable and maintainable code

In the context of 3 (and 4 eventually) is interesting if we can stip a little bit the code (remove some lines or classes from [util](https://github.com/pf4j/pf4j/tree/master/pf4j/src/main/java/org/pf4j/util) package for example).
It's interesting if we can improve point 5, also.
Maybe using the new API from Java 8 we can improve something from what I said above.
