### ISSUE TITLE
Migrate to JUnit 5

### ISSUE THREAD

**Issue by decebals** [pf4j/pf4j#283]

**Comment by dmitry-timofeev** [comment]
That would be awesome! We have recently migrated our projects to 5. I've [documented](https://stackoverflow.com/a/51847402/1792188) how it can be done mostly automatically with the help of Error Prone and Intellij, hope that helps to do that efficiently.

**Comment by decebals** [comment]
Done with e1fb3f7bc411cdfc3eee0cacedc8f7b1a238b7cd on [pf4j_3](https://github.com/pf4j/pf4j/tree/pf4j_3) branch.
