### ISSUE TITLE
Singleton: Don't get own instances for each plugin

### ISSUE THREAD

**Issue by meydominic** [pf4j/pf4j#284]
We have our main application and two plugins.
For testing I created the same plugin twice with different plugin-ids.

Both plugins are loaded correctly.

the plugins have the main application as compileOnly dependency where we have a class called `PluginApplicationContext`

In this class we have a static instance:
```java
private static PluginApplicationContext INSTANCE;

public static PluginApplicationContext getInstance()
{
    if (INSTANCE == null)
    {
        INSTANCE = new PluginApplicationContext();
    }

    return INSTANCE;
}
```

If I call getInstance() from plugin1, then a new instance will be created.
Then getInstance() will be called from plugin2, but it returns the same instance. There is no new created.

Each Plugin has its own (Plugin)ClassLoader.

If I call getInstance from plugin start() method the instances have the following ClassLoader:
sun.misc.Launcher$AppClassLoader@18b4aac2
Which is not the PluginClassLoader.

Even if I extend PluginFactory and try to create/get instance with plugin-class-loader from pluginWrapper it is the same as above.

I read through the docs and checked issues but I can't find any info regarding this. Does it have to do with the order of class-loading (mentioned in doc)?

Any hints?

Edit:
Some code snippets what we tried so far
```java
Class<?> applicationContextClass = pluginWrapper.getPluginClassLoader().loadClass(PluginApplicationContext.class.getName());
Constructor<?> applicationContextConstructor = applicationContextClass.getConstructor(Properties.class);
PluginApplicationContext pluginApplicationContext = (PluginApplicationContext)applicationContextConstructor.newInstance(new Properties());

Class<?> applicationContextClass = pluginWrapper.getPluginClassLoader().loadClass(PluginApplicationContext.class.getName());
Method method = applicationContextClass.getMethod("getInstance");
PluginApplicationContext context = (PluginApplicationContext)method.invoke(null);
logger.info("PLUGIN APP CONTEXT getMethod CL: " + context.getClass().getClassLoader().toString());
```

Thank you

**Comment by decebals** [comment]
I think that the behavior described by you is correct, and I will explain you below why it's correct.
> the plugins have the main application as compileOnly dependency where we have a class called `PluginApplicationContext`

That means that `PluginApplicationContext.class` is available in app.jar and not in plugin.jar. If class/app.jar is available only at compile phase (in Maven, in plugin's `pom.xml` you add a dependency to `app.jar` with scope **provided**) that means that `PluginApplicationContext.class` (and all classes from app.jar) will be loaded by Application's `ClassLoader` and not by Plugin's `ClassLoader`. The PluginClassLoader will delegate to parent class loader the load of PluginApplicationContext class.
PluginApplicationContext is an implementation (not the best) of Singleton pattern.
When I read your post for the first time, my feeling was that your intention is to share some information between all plugins but now I understand that you don't want this :)

If you want one PluginApplicationContext for each plugin, you need to load this class using PluginClassLoader. One solution is to put this class in a plugin (pluginA for example) and add this plugin as dependency in each plugin that use this class. My feeling is that something is wrong in your application design but I don't have all information. It's an uncommon use case in my opinion but maybe I'm wrong.

**Comment by meydominic** [comment]
Thanks for your detailed answer. 👌

Our idea behind this solution is/was to create an interface/class which plugins can implement where they get some information injected as for example plugin-specific Logger (with file logging, ...) and Plugin-Confugration (both need to be controled by main application) and some other stuff.

**Comment by decebals** [comment]
To inject some objects in Plugin is easy with `PluginFactory` (see some details in https://github.com/pf4j/pf4j/issues/20). This is the push approach (application injects objects - services for example - in plugins). Another approach is the pull approach. In this approach the plugins extract information/objects from application via `PluginManager`. For example:
```java
public class MyPluginManager extends DefaultPluginManager {

    private Configuration config;

    public MyPluginManager(Configuration config) {
         this.config = config;
    }

    public Configuration getConfiguration() {
         return config;
    }

}

public class MyBasePlugin extends Plugin {

    public Configuration getConfiguration() {
        return ((MyPluginManager) getWrapper().getPluginManager()).getConfiguration();
    }

}

public class Plugin1 extends MyBasePlugin {
    
    // use getConfiguration() as you wish

}

public class Application {
     
    public static void main(String[] args) {
         Configuration config = ...;
         PluginManager pluginManager = new MyPluginManager(config)
         pluginManager.loadPlugins(0;
         pluginManager.startPlugins();
    }

}

```

**Comment by meydominic** [comment]
The pull approach was the first approach we did, now we are using the push approach and extend PluginFactory. It's working fine 👌

**Comment by decebals** [comment]
@meydominic 
Can we close this issue? Do you need more information?
