### ISSUE TITLE
Store plugins ordered by pluginId

### ISSUE THREAD

**Issue by dmitry-timofeev** [pf4j/pf4j#295]
It would be nice if plugins returned by `AbstractPluginManager#getPlugins` were ordered by PluginId, so that, if included in logs/error messages, the list is easier for a human to parse. It may be easily achieved if a `SortedMap` like `TreeMap` were used instead of a `HashMap`. Are there any reasons not to?

**Comment by decebals** [comment]
> Are there any reasons not to?

I don't think. Please submit a PR.

**Comment by pinhead84** [comment]
I just like to point out, that **each operation** on `TreeMap` elements takes longer compared to a `HashMap`.

> The average time to search for an element under the reasonable assumption, in a hash table is **O(1)**.
> ...
> TreeMap provides a performance of **O(log(n))** for most operations like add(), remove() and contains() 
>
> see [Java TreeMap vs HashMap](https://www.baeldung.com/java-treemap-vs-hashmap)

In general I don't really like the idea to intentionally decrease performance **only** for the sake of nicer looking log files. If there are no other more important reasons, I prefer to keep the `HashMap` implementation.

Maybe a new / separate method `AbstractPluginManager#getPluginsSorted` might make sense. If one needs a sorted map of plugins, he might call this method instead of `AbstractPluginManager#getPlugins`.

**Comment by dmitry-timofeev** [comment]
Thanks for responses! 

> I just like to point out, that each operation on TreeMap elements takes longer compared to a HashMap.

That is not entirely correct: queries do indeed take _O(log(N))_, but bulk operations like `Map#entrySet` are _O(N)_.

Performance is certainly a valid concern; but, if performance is discussed, we must at least understand
 1. How frequent the affected operations (querying plugins by their ids) appear in most applications using the framework.
 2. What is the limit for N for most applications.

Is there any reliable data on that? I could only share the results of _memory_ usage of a prototype app that loaded a lot of different plugins (each loading three classes): 128 plugins consumed ~ 140 MB; 256 plugins ~ 255 MB. It's far from a proper scientific experiment, so take it with a pinch of salt, but from such memory usage one can say that N does not go above a couple of thousands.

**Comment by dmitry-timofeev** [comment]
Regarding adding a separate method — I think it is not worth to add it — the clients can sort themselves if desperately needed. But having a sensible for a human iteration order of plugins (just as an implementation feature of APM, not as a `PluginManager` interface specification = requirement) is nice to have.

**Comment by decebals** [comment]
Do you think that is an option to do this sort in `AbstractPluginManager#getPlugins` and keep the current `HashMap` as storage?
The current implementation is:
```java
@Override
public List<PluginWrapper> getPlugins() {
    return new ArrayList<>(plugins.values());
}
```

An extreme approach is to disable this sort if a system property (for example `pf4j.plugins.noSort`) is present.

Also, I think that a new protected method `AbstractPluginManager#getPlugins(Comparator comparator)` can be a solution. We can use this method instead of `getPlugins` in `AbstractPluginManager`'s methods where we think that we need it.

But, first of all I want to understand clear the benefice (with a real example). I don't understand very clear what means:
> were ordered by PluginId, so that, if included in logs/error messages, the list is easier for a human to parse.

**Comment by pinhead84** [comment]
> ...but from such memory usage one can say that N does not go above a couple of thousands.

I also think, that in most cases the `TreeMap` won't affect performance & memory usage too much. I just wanted to point out, that your proposed change **might** have a downside. We also should keep embedded systems like Raspberry Pi in mind. On those kind of systems saving resources & memory is much more critical compared to regular server or desktop systems.

> Regarding adding a separate method — I think it is not worth to add it — the clients can sort themselves if desperately needed.

But wouldn't a separate method as proposed by @decebals solve your problem (if I understood it correctly) without any negative impact on performance / memory usage? - If a developer needs a sorted list of plugins, he might call the separate method and other parts of PF4J are not negatively affected.

Please don't get me wrong. I'm not generally against your proposal. But sacrificing performance only for the sake of better looking / readable log files feels kind of strange to me.

**Comment by dmitry-timofeev** [comment]
Thanks for the responses,

I agree that if there is little data on the usage to be able to tell that performance isn't affected, it is reasonable to be cautious and not change the implementation unless there is a big need for that. Mine isn't — basically, better readability of diagnostic and error messages when lists of plugins are presented.

As a separate method for obtaining an ordered list of plugins in PF4J with underlying HashMap won't be able to provide better performance than a user-written method (= a user can sort with the same complexity in their own method outside of the plugin manager); and the use-cases for explicit _linearithmic_ sorting on each invocation are even more questionable, I'd abstain from adding such method to keep the interface minimal.

**Comment by decebals** [comment]
> Thanks for the responses,

Thanks for understanding  and for the constructive remarks!
If performance is not a problem for you (few plugins), another solution is to override the `getPlugins` method in your `(Default)PluginManger`, and to return a list of plugins sorted as you wish.
