### ISSUE TITLE
Return extension classes with wildcard type arguments

### ISSUE THREAD

**Issue by dmitry-timofeev** [pf4j/pf4j#296]
Currently a family of `PluginManager#getExtensionClasses(Class<T> extensionType, …)` return `List<Class<T>>`. That, however, makes mocking quite hard:

```java
when(pluginManager.getExtensionClasses(Service.class, pluginId))
    .thenReturn(ImmutableList.of(TestService1.class));
// Won't compile, because List<Class<TestService1>> is not assignable
// to List<Class<Service>>

when(pluginManager.getExtensionClasses(Service.class, pluginId))
    .thenReturn(ImmutableList.of(TestService1.class, TestService2.class)); 
// Won't compile, because List<Class<? extends Service>> is not assignable
// to List<Class<Service>>

when(pluginManager.getExtensionClasses(Service.class, pluginId))
    .thenReturn(ImmutableList.of((Class<Service>) TestService1.class); 
// Won't compile, because Class<TestService1>> cannot be
// cast to Class<Service>.
```

I suggest returning `List<Class<? extends T>>` to make the interface more flexible.

### Workaround 1
Add a method to perform conversion:

```java
  @SuppressWarnings("unchecked")
  @SafeVarargs
  private static <T> List<Class<T>> extensions(Class<? extends T>... extensions) {
    return Arrays.stream(extensions)
        .map(extensionClass -> (Class<T>) extensionClass)
        .collect(toList());
  }
```

### ~~Workaround 2~~

(Not really)
```java
thenReturn(ImmutableList.of(
  ((Class<Service>) ((Class<? extends Service>) TestService1.class))
));
```

**Comment by decebals** [comment]
I think that you talk here about `PluginManager#getExtensionClasses` and not `PluginManager#getExtensions`. Is it correct?

**Comment by decebals** [comment]
@dmitry-timofeev 
Can your respond to my question from my previous comment? Did you find a solution?

**Comment by dmitry-timofeev** [comment]
Hi,

Yes, I had made some typos, now must be fixed, thanks! We use the first workaround in the project.

**Comment by decebals** [comment]
> We use the first workaround in the project.

That means that you use PF4J. Good :+1: :smile:.

**Comment by decebals** [comment]
@dmitry-timofeev 
Can you submit a PR for [pf4j_3](https://github.com/pf4j/pf4j/tree/pf4j_3) branch? Thanks!

**Comment by dmitry-timofeev** [comment]
Hi, I think I'll try in the coming week.-- Best wishes,Dmitry Timofeev21.03.2019, 15:23, "Decebal Suiu" <notifications@github.com>:@dmitry-timofeev
Can you submit a PR for pf4j_3 branch? Thanks!

**Comment by decebals** [comment]
@dmitry-timofeev 
Please review and test the modifications.
The first `SNAPSHPOT` version of PF4J `3.0.0` is available for tests. See [doc](https://pf4j.org/dev/maven.html) for how to use SNAPSHOT versions in your project.

**Comment by dmitry-timofeev** [comment]
Hi @decebals, thank you for the updates! I've finally got to them. We have earlier migrated our mock-based tests to integration tests. They no longer require mocking PF4J classes (with the risks of making the wrong guesses of their actual behaviour) which makes feedback from the tests more valuable. They, hovewer, require a testkit that could create plugin JAR files on the fly: [`ServiceArtifactBuilder`](https://github.com/exonum/exonum-java-binding/blob/404c816ac3436614626c7cedd473098dcd1e93b3/exonum-java-binding/testing/src/main/java/com/exonum/binding/test/runtime/ServiceArtifactBuilder.java#L40-L47), maybe something similar would be useful to other users.

**Comment by decebals** [comment]
@dmitry-timofeev 
Thanks that your share with us your work.
I wish to inform you that PF4J 3 comes with a powerful abstractization of the way to pack a pugin, very useful for tests:
- [PluginJar](https://github.com/pf4j/pf4j/blob/pf4j_3/pf4j/src/test/java/org/pf4j/plugin/PluginJar.java)
- [PluginZip](https://github.com/pf4j/pf4j/blob/pf4j_3/pf4j/src/test/java/org/pf4j/plugin/PluginZip.java)

`PluginJar` is similar with your `ServiceArtifactBuilder` but a lot more flexible (you can add manifest attributes, class data provider - get class data from different sources, ...).

**Comment by dmitry-timofeev** [comment]
Looks great, thank you for the info! I'll check if ours can be migrated to it. I see it is in `test` folder — do you plan to move it to a separate module that can be used by both PF4J integration tests and external projects (e.g., `pf4j-testkit`)?

**Comment by decebals** [comment]
> do you plan to move it to a separate module that can be used by both PF4J integration tests and external projects (e.g., pf4j-testkit)?

It's an idea. Thanks!
