### ISSUE TITLE
Loading extensions may shutdown the application

### ISSUE THREAD

**Issue by pinhead84** [pf4j/pf4j#297]
While I was migrating my PF4J based application from [log4j](https://logging.apache.org/log4j/1.2/) to [Logback](https://logback.qos.ch/) I've discovered a problem regarding [system extensions](https://pf4j.org/doc/system-extension.html) (but I guess extensions provided by plugins should also be affected). I've reduced the problem to this example application:

```java
package test;

import org.pf4j.DefaultPluginManager;
import org.pf4j.ExtensionFinder;
import org.pf4j.PluginManager;
import org.pf4j.ServiceProviderExtensionFinder;

public class ServiceProviderTest {
  public static void main(String[] args) {

    // The problem only occurs, if the ServiceProviderExtensionFinder is used.
    PluginManager pluginManager = new DefaultPluginManager() {
      @Override
      protected ExtensionFinder createExtensionFinder() {
        ServiceProviderExtensionFinder f = new ServiceProviderExtensionFinder(this);
        this.addPluginStateListener(f);
        return f;
      }
    };

    // This seems not necessary, but i'll add this for the sake of completeness.
    System.out.println("LOAD PLUGINS");
    pluginManager.loadPlugins();

    // This seems not necessary, but i'll add this for the sake of completeness.
    System.out.println("START PLUGINS");
    pluginManager.startPlugins();

    // Loading system extensions leads to an exception and immediate shutdown,
    // if Logback is present in the classpath.
    System.out.println("LOAD EXTENSIONS");
    for (Object ext : pluginManager.getExtensions((String) null)) {
      System.out.println("found extension " + ext);
    }

    // This success message is not shown, if Logback is present in the classpath
    System.out.println("APPLICATION FINISHED SUCCESSFULLY");
  }
}
```

The application **works as expected, if *log4j* is present** in the classpath. It shows the following output and ends with the success message:

```
INFO [4j.DefaultPluginStatusProvider:  49] Enabled plugins: []
INFO [4j.DefaultPluginStatusProvider:  53] Disabled plugins: []
INFO [ org.pf4j.DefaultPluginManager: 125] PF4J version 2.6.0 in 'deployment' mode
LOAD PLUGINS
DEBUG [org.pf4j.AbstractPluginManager: 201] Lookup plugins in 'plugins'
INFO [org.pf4j.AbstractPluginManager: 213] No plugins
START PLUGINS
LOAD EXTENSIONS
DEBUG [g.pf4j.AbstractExtensionFinder: 172] Finding extensions from plugin 'null'
DEBUG [ServiceProviderExtensionFinder:  59] Reading extensions storages from classpath
DEBUG [ServiceProviderExtensionFinder: 114] Read 'file:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/icedtea-sound.jar!/META-INF/services'
DEBUG [rviceProviderExtensionFinder$1: 140] Read '/META-INF/services/javax.sound.sampled.spi.MixerProvider'
DEBUG [ServiceProviderExtensionFinder: 114] Read 'file:/home/andy/repositories/pf4j-test/libs2/pf4j-2.6.0.jar!/META-INF/services'
DEBUG [rviceProviderExtensionFinder$1: 140] Read '/META-INF/services/javax.annotation.processing.Processor'
DEBUG [g.pf4j.AbstractExtensionFinder: 289] Found possible 2 extensions:
DEBUG [g.pf4j.AbstractExtensionFinder: 291]    org.classpath.icedtea.pulseaudio.PulseAudioMixerProvider
DEBUG [g.pf4j.AbstractExtensionFinder: 291]    org.pf4j.processor.ExtensionAnnotationProcessor
DEBUG [ServiceProviderExtensionFinder:  83] Reading extensions storages from plugins
DEBUG [g.pf4j.AbstractExtensionFinder: 195] Loading class 'org.classpath.icedtea.pulseaudio.PulseAudioMixerProvider' using class loader 'sun.misc.Launcher$AppClassLoader@75b84c92'
DEBUG [g.pf4j.AbstractExtensionFinder: 200] Added extension 'org.classpath.icedtea.pulseaudio.PulseAudioMixerProvider' with ordinal 0
DEBUG [g.pf4j.AbstractExtensionFinder: 195] Loading class 'org.pf4j.processor.ExtensionAnnotationProcessor' using class loader 'sun.misc.Launcher$AppClassLoader@75b84c92'
DEBUG [g.pf4j.AbstractExtensionFinder: 200] Added extension 'org.pf4j.processor.ExtensionAnnotationProcessor' with ordinal 0
DEBUG [g.pf4j.AbstractExtensionFinder: 209] Found 2 extensions for plugin 'null'
DEBUG [g.pf4j.DefaultExtensionFactory:  38] Create instance for extension 'org.classpath.icedtea.pulseaudio.PulseAudioMixerProvider'
DEBUG [g.pf4j.DefaultExtensionFactory:  38] Create instance for extension 'org.pf4j.processor.ExtensionAnnotationProcessor'
found extension org.classpath.icedtea.pulseaudio.PulseAudioMixerProvider@17d10166
found extension org.pf4j.processor.ExtensionAnnotationProcessor@1b9e1916
APPLICATION FINISHED SUCCESSFULLY
```

But the same application does **not work as expected, if *Logback* is present** in the classpath. It throws an exception and **quits the application immediately** (the success message is not printed):

```
INFO [4j.DefaultPluginStatusProvider:  49] Enabled plugins: []
INFO [4j.DefaultPluginStatusProvider:  53] Disabled plugins: []
INFO [ org.pf4j.DefaultPluginManager: 125] PF4J version 2.6.0 in 'deployment' mode
LOAD PLUGINS
DEBUG [org.pf4j.AbstractPluginManager: 201] Lookup plugins in 'plugins'
INFO [org.pf4j.AbstractPluginManager: 213] No plugins
START PLUGINS
LOAD EXTENSIONS
DEBUG [g.pf4j.AbstractExtensionFinder: 172] Finding extensions from plugin 'null'
DEBUG [ServiceProviderExtensionFinder:  59] Reading extensions storages from classpath
DEBUG [ServiceProviderExtensionFinder: 114] Read 'file:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/icedtea-sound.jar!/META-INF/services'
DEBUG [rviceProviderExtensionFinder$1: 140] Read '/META-INF/services/javax.sound.sampled.spi.MixerProvider'
DEBUG [ServiceProviderExtensionFinder: 114] Read 'file:/home/andy/repositories/pf4j-test/libs/pf4j-2.6.0.jar!/META-INF/services'
DEBUG [rviceProviderExtensionFinder$1: 140] Read '/META-INF/services/javax.annotation.processing.Processor'
DEBUG [ServiceProviderExtensionFinder: 114] Read 'file:/home/andy/repositories/pf4j-test/libs/logback-classic-1.2.3.jar!/META-INF/services'
DEBUG [rviceProviderExtensionFinder$1: 140] Read '/META-INF/services/javax.servlet.ServletContainerInitializer'
DEBUG [g.pf4j.AbstractExtensionFinder: 289] Found possible 3 extensions:
DEBUG [g.pf4j.AbstractExtensionFinder: 291]    org.classpath.icedtea.pulseaudio.PulseAudioMixerProvider
DEBUG [g.pf4j.AbstractExtensionFinder: 291]    ch.qos.logback.classic.servlet.LogbackServletContainerInitializer
DEBUG [g.pf4j.AbstractExtensionFinder: 291]    org.pf4j.processor.ExtensionAnnotationProcessor
DEBUG [ServiceProviderExtensionFinder:  83] Reading extensions storages from plugins
DEBUG [g.pf4j.AbstractExtensionFinder: 195] Loading class 'org.classpath.icedtea.pulseaudio.PulseAudioMixerProvider' using class loader 'sun.misc.Launcher$AppClassLoader@75b84c92'
DEBUG [g.pf4j.AbstractExtensionFinder: 200] Added extension 'org.classpath.icedtea.pulseaudio.PulseAudioMixerProvider' with ordinal 0
DEBUG [g.pf4j.AbstractExtensionFinder: 195] Loading class 'ch.qos.logback.classic.servlet.LogbackServletContainerInitializer' using class loader 'sun.misc.Launcher$AppClassLoader@75b84c92'
Exception in thread "main" java.lang.NoClassDefFoundError: javax/servlet/ServletContainerInitializer
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.pf4j.AbstractExtensionFinder.find(AbstractExtensionFinder.java:196)
	at org.pf4j.AbstractPluginManager.getExtensions(AbstractPluginManager.java:595)
	at test.ServiceProviderTest.main(ServiceProviderTest.java:32)
Caused by: java.lang.ClassNotFoundException: javax.servlet.ServletContainerInitializer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 more
```

I've tested this with OpenJDK 8, 11 and 12. The result is always the same.

The reason is quite simple. Logback provides [this service file](https://github.com/qos-ch/logback/blob/v_1.2.3/logback-classic/src/main/resources/META-INF/services/javax.servlet.ServletContainerInitializer), which is processed by `AbstractExtensionFinder` in order to look for possible extensions. But the corresponding [`LogbackServletContainerInitializer` class](https://github.com/qos-ch/logback/blob/v_1.2.3/logback-classic/src/main/java/ch/qos/logback/classic/servlet/LogbackServletContainerInitializer.java) depends on the servlet API, which is not present in the application classpath (because the application does not make use of this API). Therefore a `ClassNotFoundException` is thrown.

In general a `ClassNotFoundException` is expected behaviour in the `AbstractExtensionFinder` class. It is explicitly caught on [line 201](https://github.com/pf4j/pf4j/blob/release-2.6.0/pf4j/src/main/java/org/pf4j/AbstractExtensionFinder.java#L201-L203). That's why I'm currently confused, why the application quits immediately instead. Shouldn't `AbstractExtensionFinder` just continue his job in this case?

Do you have any idea, why the application quits immediately or do you see any possible way to catch this exception?

As a workaround for my real world application I've replaced `ServiceProviderExtensionFinder` with `LegacyExtensionFinder` and used `extension.idx` in all of my plugins. Of course in this case PF4J does not look for any service files and this problem does not occur. 

I can live with this workaround. But still I wanted to point out this problem hoping, that you may have an idea about this. In general I would love to provide a bugfix - but currently I'm quite confused about how to catch this nasty `ClassNotFoundException`...

**Comment by pinhead84** [comment]
> In general I would love to provide a bugfix - but currently I'm quite confused about how to catch this nasty `ClassNotFoundException`...

Oh my dear ... I've just overlooked, that a `NoClassDefFoundError` is thrown, which is caused by a `ClassNotFoundException`. So the answer might be, that we also need to catch a `NoClassDefFoundError` in [line 201 of `AbstractExtensionFinder`](https://github.com/pf4j/pf4j/blob/release-2.6.0/pf4j/src/main/java/org/pf4j/AbstractExtensionFinder.java#L201-L203).

Catching errors like this is quite ugly. I basically never do this in my applications and therefore didn't consider this at all. But I guess it's necessary in this case?

**Comment by decebals** [comment]
> So the answer might be, that we also need to catch a NoClassDefFoundError in line 201 of AbstractExtensionFinder.

Yes, I think so. The idea is that on any checked or unchecked exception, in that catch block we log the error and move on next class.

**Comment by pinhead84** [comment]
Okay. I'll send you a pull request tomorrow, if you don't mind. :)

**Comment by evervondel** [comment]
in this 'fix", NoClassDefFoundError is not catched.... so how does this fix the issue???

I have the same problem...  When loading an extension which internally references a class which is not on the main app classpath, the classloader throws a NoClassDefFoundError... which is not catched >> and causes my application to crash !!

NoClassDefFound shouls also be caught!!

**Comment by decebals** [comment]
@evervondel 
According https://github.com/pf4j/pf4j/blob/master/pf4j/src/main/java/org/pf4j/AbstractExtensionFinder.java#L201, the `NoClassDefFoundError` is catched.

**Comment by evervondel** [comment]
@decebals It is ok, it was mislead by the commit reference above https://github.com/pf4j/pf4j/commit/17102040c757ca7d3fba2f0375e7306ee169b4f8
where it was not fixed properly...

in the main branch it seems to be ok !! thanks
