### ISSUE TITLE
Provide a module-info.java

### ISSUE THREAD

**Issue by pinhead84** [pf4j/pf4j#299]
@decebals: According to your message in issue #282:

> The development is done on Java 11 (OpenJDK) but the compiled classes will be compatible with Java 8.

If Java 11 is used for development / compilation, we might also consider integrating a `module-info.java`. Even if Java 8 is used as minimal / target version, we still might include this file into the build process. I've seen this for example in the [`asm-7.1.jar` file](https://repository.ow2.org/nexus/content/repositories/releases/org/ow2/asm/asm/7.1/asm-7.1.jar). The library contains a `module-info.class` (compiled for Java 9) and the rest of the class files are targeted at Java 1.5.

I like this approach, because the library is still compatible with Java 8 but can also be used as a module in Java 9+. One possible solution for this proposal is described in the [documentation of maven-compiler-plugin](https://maven.apache.org/plugins/maven-compiler-plugin/examples/module-info.html).

What do you think about this? - If you like it, I would provide a pull request for the [pf4j_3 branch](https://github.com/pf4j/pf4j/tree/pf4j_3).

**Comment by decebals** [comment]
I agree with what you say. Please submit a PR.
