### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by edrik** [pf4j/pf4j#30]
Hi,
Noticed that there is nothing mentioned about thread safety in the readme. Became curious about this when viewing DefaultPluginManager that use plain ArrayList and HashMap internaly with not clear synchronize or lock pathern.

What would be the sugested way to use this library safely in a multithreaded enviroment?

   -F

**Comment by decebals** [comment]
One idea is to extend `DefaultPluginManager` and to sync some methods or to create a thread safe decorator.
The main method of framework is `PluginManager.getExtensions(ExtensionPoint.class)` and I do not see a real problem in its part.

> What would be the sugested way to use this library safely in a multithreaded environment?

Do you have such an environment? I'd happy to help you if you give me something concrete (a quick start example, some errors). 

I will take a look to see if I find something.

**Comment by edrik** [comment]
It was nothing concrete merely an observation I made while evaluating the project.
And it's quite clear that managing plugins is not something that should be under any type of load, but in a servlet environment there is always the risk of concurrent requests.

Actually I just wanted to confirm that guarding against concurrent modifications and access is something you would need to take into consideration when using then library. And suggest that it might be good to mention this in the documentation.

Just throwing it out there, why not use java.util.concurrent versions of lists and maps for the critical parts?

   -F

**Comment by decebals** [comment]
I will try to resolve this issue. Also any PR or pseudo code (draft) is welcome.
