### ISSUE TITLE
java-semver library is outdated

### ISSUE THREAD

**Issue by pinhead84** [pf4j/pf4j#303]
Regarding issue #300 I wanted to send a pull request to the [java-semver library](https://github.com/zafarkhaja/jsemver) to make them provide an automatic module name or to make their library support modules for Java 9+. But it seems, that this project is not actively maintained anymore. It did not receive any updates in the last years and has a lot of open issues / pull requests. The project looks pretty much dead to me.

What do you think - is it a problem for PF4J to force its users to a library, that does not receive updates / improvements? - I know the library is only used for parsing version numbers. Maybe it is not that much of a deal and we can ignore this issue. But in general I don't really like to use libraries, whose developers won't react to problems or future improvements of the JVM (especially Java modules in case of PF4J 3).

In case you share my opinion, what might be the alternatives?

1. We might integrate java-semver into PF4J and maintain the code for ourselves. The code base is not very big. It won't have a big impact on the total size of the library. But of course this means, that we had to take care of more code besides PF4J itself.

2. We might use one of the widely available forks. Especially the forks by [AntiLaby](https://github.com/AntiLaby/jsemver) and [BristolPound](https://github.com/BristolPound/jsemver) look promising to me. Both integrated a lot of pull requests / improvements, that are still open in the original library. But unfortunately it seems, that both libraries are not published to Maven Central yet. This makes it a bit complicated to use these forks within PF4J. Maybe we can contact the developers and ask them to publish their libraries to Maven Central under a separate group ID. Alternatively we might consider to integrate their code directly into PF4J.

3. We might switch to another library like [semver4j](https://github.com/vdurmont/semver4j). It has a smaller code base and its last update is about a year ago. It also has some open / unresolved issues but maybe its still a better alternative. Because of its smaller code base, it also might be easier to integrate their source code into PF4J.

What do you think about all this? - Do you think it is a problem at all and we should do something about it? - Or do you think I'm making up problems, that don't really deserve our attention?

I'm currently not sure, what to think about this. But at least I wanted to point it out and maybe discuss the pros and cons. ;)

**Comment by decebals** [comment]
I don't have a clear opinion related to this aspect. I will try to add only some comments.
PF4J abstracts all aspects about versions in [VersionManager](https://github.com/pf4j/pf4j/blob/master/pf4j/src/main/java/org/pf4j/VersionManager.java) interface.
The default implementation of `VersionManager` is [DefaultVersionManager](https://github.com/pf4j/pf4j/blob/master/pf4j/src/main/java/org/pf4j/DefaultVersionManager.java) and it's based on `jsemver` library.
If a PF4J user doesn't want to use `jsemver` in his project, then he can exclude this library when he add PF4J as dependency, but he must supply a custom implementation of `VersionManager` via `AbstractPluginManager#createVersionManager` or `PluginManager#getVersionManager`.
Historically, first versions of PF4J came with a `Version` class that was a very simple implementation of semver. Then, the issue https://github.com/pf4j/pf4j/pull/44 came with a propose to introduce `jsemver`.

> What do you think - is it a problem for PF4J to force its users to a library, that does not receive updates / improvements?

Sure, it's not good that `jsemver` is not active maintained but for the moment we don't have problems with this library (until now). 

> What do you think about all this? - Do you think it is a problem at all and we should do something about it? - Or do you think I'm making up problems, that don't really deserve our attention?

I don't know. I think that for the moment it's not a real problem. The PF4J is very customizable on this subject (versions management), and we have a lot of solution. The `VersionManager` interface is very small (only two methods) and a new implementation is relative easy to add. 
In the end we can add a lite `Version.java` (like in the past) and make `JSemVersionManager.java` optional (the dependency to `jsemver` is optional). It's only an idea.

**Comment by nbartels** [comment]
maybe it makes sense to send a mail to the developer of the semver lib and ask him to transfer the code base into a community project. So the both fork owner can maintain the thing and the founder is only the founder.
In my experience this is working most of the time :)

**Comment by pinhead84** [comment]
@nbartels A new community project still requires a maintainer, who is willing to invest some time (e.g. fixing bugs, answering issues, checking pull requests etc.).

Also there are [alternatives](https://github.com/vdurmont/semver4j) and different forks of the semver library (e.g. [AntiLaby](https://github.com/AntiLaby/jsemver) and [BristolPound](https://github.com/BristolPound/jsemver)) available. I don't know, if it's worth the effort to start another project / fork for a simple version check mechanism.

---

@decebals 

>  If a PF4J user doesn't want to use `jsemver` in his project, then he can exclude this library when he add PF4J as dependency, but he must supply a custom implementation of `VersionManager` via `AbstractPluginManager#createVersionManager` or `PluginManager#getVersionManager`.

I don't really like, that an unmaintained library is distributed to the developers **by default**. Of course the developer can use its own `VersionManager` - but this unnecessarily requires a custom implementation & configuration. I would personally prefer to use [Semver4j](https://github.com/vdurmont/semver4j) by default - either as dependency or by integrating their code (only five classes) directly into PF4J.

> Sure, it's not good that `jsemver` is not active maintained but for the moment we don't have problems with this library (until now).

I agree, that this is a minor issue and does not need immediate attention. But it still gives me a bad feeling in the stomach. Therefore I will implement a custom `VersionManager` and switch my application to `Semver4j` nevertheless. ;)

If you like, I can give a short feedback after migrating to `Semver4j`. If everything works as expected on my side and you also like to migrate, I would provide a pull request for PF4J 3.x.

**Comment by nbartels** [comment]
@pinhead84 Maybe one of the forks can become the official library and the two forkers you mentioned could be the maintainer(s). But however, maybe switching the library is a better approach.

**Comment by decebals** [comment]
> If you like, I can give a short feedback after migrating to Semver4j. If everything works as expected on my side and you also like to migrate, I would provide a pull request for PF4J 3.x.

Yes. Notify me when you have something. I doubt that `Semver4j` is active maintained, but it's small enough to be ported (some parts) in PF4J.

**Comment by decebals** [comment]
I still don't know what to do with this problem :smile:. 
It will probably stay open until someone has a version issue. At that moment we will react

**Comment by decebals** [comment]
Closed for the moment. See https://github.com/zafarkhaja/jsemver/issues/56#issuecomment-656304223.
