### ISSUE TITLE
How to load a specific plugin jar without load all jar files under the plugins directory?

### ISSUE THREAD

**Issue by JeffYoungL** [pf4j/pf4j#308]
In my case, I have multiple implementations for an interface under the `plugins` directory , but only one should be instantiated at runtime.

Let's say that there is an extension endpoint `Greeting`, and two implementation plugins `HelloGreeting` and `WorldGreeting`. I want to load one specific plugin jar file base on a condition (e.g plugin id) at runtime without loading both plugins from plugin path. Is there any way to do this?

**Comment by decebals** [comment]
Maybe, an elegant solution is to use a custom implementation of [PluginStatusProvider](https://github.com/pf4j/pf4j/blob/master/pf4j/src/main/java/org/pf4j/PluginStatusProvider.java#L22).

**Comment by JeffYoungL** [comment]
According to my understanding, it looks like that `PuginStatusProvider` is not the key point. 

I'm not sure if this is the correct way to load and resolve specific plugin when just given a plugin id "hello-greeting" at runtime, I just post my code here:
```        
public class MyPluginManager extends DefaultPluginManager  {
     ............
    
    public void loadAndStartGreetingService( String plugin ) {
           Path path = getPluginsRoot().resolve(plugin);//  plugin = "hello-greeting-0.0.1-SNAPSHOT.zip"
       
           String pluginId = this.loadPlugin(path);

           this.startPlugin(pluginId);

          List<TsdbService> extensions = this.getExtensions(Greeting.class, pluginId);//Greeting is the extension endpoint
             ......
       }
}
```
As you see,  given `hello-greeting`, the implementation plugin will be loaded and initiated  on demand at runtime, not on the system startup.

**Comment by decebals** [comment]
Your code looks good. This is the correct approach when you want to use (load & start) a new plugin, after the application was started. The variant with `PuginStatusProvider` is used when you want to disable/enable a plugin that exists already in `plugins` (`getPluginsRoot`) directory. If your plugin exists in `plugins` directory, it will be loaded and started automaticaly if it's not disabled.

**Comment by JeffYoungL** [comment]
For most scenarios of mine,  plugins under `plugins` directory are loaded manually. What bothered me is that some extensions under classpath (like `WhazzupGreeting` in the demo project) were loaded automatically, and I don't know how to stop this . If I  haven't  implement my own `PluginStatusProvider`,  what should I put into the `disabled.txt`?

**Comment by decebals** [comment]
>What bothered me is that some extensions under classpath (like WhazzupGreeting in the demo project) were loaded automatically, and I don't know how to stop this .

In this case, the solution is to not use thhis kind of extensions ([system extensions](https://pf4j.org/doc/system-extension.html)).

> If I haven't implement my own PluginStatusProvider, what should I put into the disabled.txt?

Nothing. The `enabled.txt` and `disabled.txt` files are used only by [DefaultPluginStatusProvider](https://github.com/pf4j/pf4j/blob/master/pf4j/src/main/java/org/pf4j/DefaultPluginStatusProvider.java).

**Comment by JeffYoungL** [comment]
Ok, Thanks. By the way, I want to setup parameters when  instantiate the extension through the non-default constructor. For example, I have a `WelcomeGreeting` extension:
```
@Extension
public static class WelcomeGreeting implements Greeting {
    public WelcomeGreeting(Properties properties) {//Maybe other type of parameters
         ......   //do some internal initialization
    }
    @Override
    public String getGreeting() {
        ...
    }
}
```
Maybe the framework can provide a new method like this :
```
pulginManager.getExtensions(Class<T> type, String pluginId, Object[] extraParams);
```
Any better idea is appreciated.

**Comment by decebals** [comment]
A solution is:
- create your custom `AcmePluginManager` only to add the new `getExtensions(..., params) method`
- create a base `ConfigurableExtension` (with extra `setters` or something similar) class/interface and extends this class by all your configurable extensions 
- inside the new added `getExtensions` method, before to return the list with extensions, try to set the `params`:
```java
// pseudo code
List<T> extensions = getExtenions(Class<T> type);
for (T extension : extensions) {
    if (extension instanceof ConfigurableExtension) {
        ConfigurableExtension configExtension = (ConfigurableExtension) extension;
        configExtension.setParam1(...);
        configExtension.setParam2(...);
    }
}
```

You can take a look at https://github.com/pf4j/pf4j/issues/187#issuecomment-353984409, maybe it can help you.

**Comment by JeffYoungL** [comment]
Thanks for your quick and positive response. It does solve my main problem, but this would not make use of inner extension cache in `ExtensionWrapper`. I have to provide another methond `isConfigured` to avoid repeatedly calls of `getExtensions(..., params)` even thoug using `SingletonExtensionFactory`:

```
@Extension
public static class WelcomeGreeting implements Greeting, ConfigurableExtension {

        private boolean configured;

        @Override
        public boolean isConfigured() {
            return configured;
        }

        @Override
        public void configure(Properties properties) {
            if (!configured) {
                System.out.println("configure service with: " + properties);
                configured = true;
            } else {
                System.out.println("service has been configured!");
            }
        }
}
```

Anyway, thanks for the tips.

**Comment by decebals** [comment]
If you use `SingletonExtensionFactory` (get the same instance of the extension when you call the `getExtensions` method multiple times) then yes, you need un mechanism to not call `configure` method multiple times.
 
From design point of view, I think that I prefer to keep my extensions clean (only business methods) and to move the implementation of `configure` in `Configurable`:

```java
public class Configurable {

    private boolean configured;

    @Override
    public boolean isConfigured() {
        return configured;
    }

    @Override
    public void configure(Properties properties) {
        if (!configured) {
            System.out.println("configure service with: " + properties);
            configured = true;
        } else {
            System.out.println("service has been configured!");
        }
    }

}
```

```java
@Extension
public static class WelcomeGreeting implements Greeting extends Configurable {

    public String getGreeting() {
        return "Welcome";
    }

}
```

Other solution is to keep in your `AcmePluginManager` this information about what instances were configurated, and to remove method `isConfigured` from `Configurable`.
 
PS. If you don't need other information, please close the issue.
