### ISSUE TITLE
Multiple instances of the same plugin with isolated classloaders

### ISSUE THREAD

**Issue by jduo** [pf4j/pf4j#310]
Is it possible to have multiple instances of the same plugin (and version), loaded in their own classloader?

The need for this comes from third party libraries that have a static variable used for configuration.

**Comment by decebals** [comment]
Because this request is a little bit uncommon in my opinion (not many users will be use this feature), please add more details (define clear the use case, the problem encountered and if you are some ideas that could help the implementation).

**Comment by jduo** [comment]
The use case for us is related to the Hive Ranger library. We are building an app that should allow for multiple Hive configurations, but the Ranger library has a static variable that's used for configuration, so we need a way to isolate it for each Hive configuration.

I thought about building a plugin manager which when given a plugin Id, modifies the ID and attaches a GUID to try to coerce P4FJ into thinking it's a new plugin and thus creating a new ClassLoader. I haven't tried this out yet though.

**Comment by jduo** [comment]
Hi @decebals ,

Just wondering if you needed any more details? Really I'm curious if what I've suggested would work within the current codebase.

**Comment by decebals** [comment]
For the moment I do not know how to deal with this case. There is a possibility that what you suggest to work. Try it..

**Comment by decebals** [comment]
The issue was opened a few years ago. Reopen it if you have more information and if it is still of interest.
