### ISSUE TITLE
Question: getPluginPaths or getPluginsPaths method name in PluginRepository?

### ISSUE THREAD

**Issue by decebals** [pf4j/pf4j#313]
In https://github.com/pf4j/pf4j/commit/40846fa1864da287690ef01402d5b5ccccbf351f, I renamed  `PluginRepository.getPluginPaths` to `getPluginsPaths` (the old name was **getPluginPath** and the new name is **getPlugin`s`Paths** - a `s` is added)

I have a doubt that my refactoring is correct (from English point of view).

**Comment by cilki** [comment]
I think `getPluginPaths` is the best way to pluralize it. `getPluginsPaths` doesn't sound right.

**Comment by decebals** [comment]
@cilki Thanks!

I reverted the commit with 3cd26fc .
