### ISSUE TITLE
It seems the demo_gradle kotlin didn't work

### ISSUE THREAD

**Issue by bstsnail** [pf4j/pf4j#327]
![image](https://user-images.githubusercontent.com/16055826/60525475-fcf5eb00-9d20-11e9-98bf-b596cc047bda.png)

Kotlin plugin load success, but the KotlinGreet is not working, I found out the kotlin plugin don't have extensions.idx, and java have, I don't know where to generate this file

**Comment by decebals** [comment]
Thanks for reporting the issue.
What version of PF4J are you using?
Unfortunately I am not so familiar with Gradle (I use Maven) and I cannot help you too much.
First of all, please search in all issues about this subject "Gradle". They are people here that use PF4J with Gradle and I am sure that they can help you and together you can solve the problem.

**Comment by bstsnail** [comment]
> Thanks for reporting the issue.
> What version of PF4J are you using?
> Unfortunately I am not so familiar with Gradle (I use Maven) and I cannot help you too much.
> First of all, please search in all issues about this subject "Gradle". They are people here that use PF4J with Gradle and I am sure that they can help you and together you can solve the problem.

The master branch , and after I add the extensions.idx manual, it works
![image](https://user-images.githubusercontent.com/16055826/60527346-94107200-9d24-11e9-809c-2b7abd98badf.png)
I don't know why the plugin3(kotlin) didn't generate this file

**Comment by bstsnail** [comment]
It also don't show kotlin extension in [README](https://github.com/pf4j/pf4j/tree/master/demo_gradle)
![image](https://user-images.githubusercontent.com/16055826/60528500-2285f300-9d27-11e9-9688-afc7d7b4b776.png)

**Comment by decebals** [comment]
From what I see [here](https://github.com/pf4j/pf4j/pull/349/files#diff-365fd5af610e466802648b5a53ef4d43R50), the https://github.com/pf4j/pf4j/pull/349 PR will solves the problem.

**Comment by decebals** [comment]
@bstsnail I merged PR #349. Please check it.
