### ISSUE TITLE
Mvn invalid flag release

### ISSUE THREAD

**Issue by otmanel31** [pf4j/pf4j#332]
Hi, i try to run the demo and got build failure.
Below the error:

> [INFO] PF4J Parent 3.1.0-SNAPSHOT ......................... SUCCESS [  2.031 s]
[INFO] PF4J ............................................... FAILURE [  0.883 s]
[INFO] Demo Parent ........................................ SKIPPED
[INFO] Demo Api ........................................... SKIPPED
[INFO] Demo App ........................................... SKIPPED
[INFO] Demo Plugins Parent ................................ SKIPPED
[INFO] Demo Plugin #1 ..................................... SKIPPED
[INFO] Demo Plugin #2 ..................................... SKIPPED
[INFO] Quickstart Archetype 3.1.0-SNAPSHOT ................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.226 s
[INFO] Finished at: 2019-07-17T17:54:39+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project pf4j: Fatal error compiling: invalid flag: --release -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

My mvn version:

> Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-24T20:49:05+01:00)
Maven home: C:\apache-maven-3.5.3\bin\..
Java version: 1.8.0_211, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_211\jre
Default locale: fr_FR, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by otmanel31** [comment]
Is it due to Java version ?

**Comment by decebals** [comment]
I'm sorry for my late response.
This issue appears in the context of #281 and I think that it was introduced by e025d6704c59ef94e810860f9974f9c424958165.

As an answer to the comment https://github.com/pf4j/pf4j/pull/278#issuecomment-501619639 of 
@dmitry-timofeev, the PF4J 3.0.1 is built with Java 11 but it's compatible with Java 8.

@otmanel31 
If you want, you can create a PR that change actual line for `pom.xml`
```xml
<maven.compiler.release>8</maven.compiler.release>
```

with
```xml
<maven.compiler.target>1.8</maven.compiler.target>	        
<maven.compiler.source>1.8</maven.compiler.source>
```

Please test the PR before submit it for merge.

**Comment by otmanel31** [comment]
Hi, thanks for you response, i'll try it asap .... tomorow may be

**Comment by decebals** [comment]
I tried myself but the solution is not so simple :smile:. The root of the problem is #300, when a new file `module-info.java` was added. This file makes sense for Java9+. It cannot be compile with Java 8.

**Comment by otmanel31** [comment]
That's a time a test it .... may be this properties was sufficient in pom.xml .... but that worked when i tried:

> <java.version>1.8</java.version>

I didn't try it again but may be only the demo app is concerned :)
