### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by MacTrophy** [pf4j/pf4j#333]
Not sure if I encountered a bug/limitation or simply something that is normal but if it's normal I think it might help others to document it.

My application using PF4J (application A) is multithreaded. My PluginManager is created in the main thread (of A). The plugins are transferred over socket from another Java application (B), this enables me to automatically update all the instances/installations of A without much intervention even given A is running on multiple remote computers. My problem doesn't concern B directly.

Since the plugins are received from B and there are delays for the transfers, the `loadPlugins()` and `startPlugins()` call is delayed until B notifies A that the transfers are completed. In A, the messages received from B are in another thread which is delegated for socket management. If the `startPlugins()` is called from the thread responsible for the socket management (after receiving appropriate message of the end of transfers), it will fail starting the plugins with exceptions about classes (that are in my plugins) that cannot be found `java.lang.NoClassDefFoundError`. In the trace logs of PF4j I get those messages `Couldn't find class 'applicationA.plugin1.PluginClass' in plugin classpath. Delegating to parent`, I guess the parent class loader (of socket thread) cannot find it either and that's where the exception is thrown from.

I am not an expert of class loading, I don't fully understand but I guess there is something going "weird" with class loading in a multi threaded context.

I solved my issue using an AtomicBoolean initiated to false and watched by a 3rd thread with the following code.
```java
public class PluginManager extends DefaultPluginManager {
	private static final int PLUGINS_START_VERIFY_INTERVAL = 100;
	private static final int PLUGINS_FORCESTART_DELAY = 1000 * 30;

	private AtomicBoolean ready = new AtomicBoolean(false);
	public PluginManager(Path pluginsRoot) {
		super(pluginsRoot);
		
		Thread launcher = new Thread() {
			@Override
			public void run() {
				Instant max = Instant.now().plusMillis(PLUGINS_FORCESTART_DELAY);
				while (!ready.get()) {
					try {
						sleep(PLUGINS_START_VERIFY_INTERVAL);
					} catch (InterruptedException e) {}
					if (Instant.now().isAfter(max)) {
						break;
					}
				}
				loadPlugins();
				startPlugins();
			}
		};
		launcher.start();
	}
	// this is the method called by the socket thread and where it would fail calling startPlugins()
	public void synchronizedPlugins() {
		ready.set(true);
	}
}
```

It's a bit strange that I am solving my issue by using yet another thread...

I'm not requiring feedback on this, so far my solution is working for me but if this is a known limitation/problem and/or I did something wrong obviously I would be interested to know otherwise may be this might help others.

**Comment by decebals** [comment]
PF4J is not thread safe. This information is present in javadoc of `AbstractPluginManager` and `DefaultPluginManager`. It's your responsibility to deal with concurrency. 
They are many possibilities to resolve the concurrency aspects in Java. Fore example you can use the future concept. 
 Maybe https://github.com/pf4j/pf4j/issues/269#issuecomment-484782465 can help you.

**Comment by MacTrophy** [comment]
Oh well I missed (or forgot) this information, I must admit I am not reading all the JavaDoc of all the classes of all the frameworks I am using (;

May be it could be added (if I didn't missed it again) in the standard documentation of your website, i.e. in the Classe loading section and/or in a dedicated section to state this and may be link to issues 269 and 333.

I will leave it to you to close this issue when appropriate to you.

Thanks again for your framework!

**Comment by decebals** [comment]
Created an issue in documentation project.
