### ISSUE TITLE
File handle on the plugin jar not released after stop and unload the plugin

### ISSUE THREAD

**Issue by tdong6** [pf4j/pf4j#334]
I have a REST API that takes file inputstream of the plugin jar, load and start the plugin. I find the file handle not released after stopping and unloading the plugin. I am using pf4j 2.6.0. The link below provides a code example to reproduce the issue.
https://gist.github.com/tdong6/3f5c35f12b7fa36c9fcf8a4663e60b10

After running the test a few times, I checked `/proc/<pid_of_java_process>/fd` and found 
```
lr-x------ 1 tdong tdong 64 Jul 24 11:58 15 -> /tmp/TEST_305179773695269349/b1686424-f688-497c-a132-a6976547f082-test.jar
lr-x------ 1 tdong tdong 64 Jul 24 11:58 17 -> /tmp/TEST_653924395239229914/ee704339-dacd-422e-a8f3-7045b1f5ef95-test.jar
lr-x------ 1 tdong tdong 64 Jul 24 11:59 19 -> /tmp/TEST_7691645899945456368/5862885a-e965-470f-b0ab-0af450dcc01c-test.jar
```

**Comment by decebals** [comment]
Can you try with the latest version (3.0.1) ? Thanks!

**Comment by tdong6** [comment]
@decebals The behavior is the same for 3.0.1. 
When typing "y" to do the `loadAndUnload` test, I see two fds created, with the same path. After typing "s" to stop and unload the plugin, only one is closed.

**Comment by decebals** [comment]
@tdong6 
I will investigate the problem. Can you add a link to a gist with the full code (imports, ...)?

**Comment by tdong6** [comment]
@decebals Thanks. https://gist.github.com/tdong6/3f5c35f12b7fa36c9fcf8a4663e60b10

**Comment by tdong6** [comment]
Fix #339 resolves the file handle leak created by `loadPlugins()`. While debugging, I find that if `getExtensions(Class<T> type)` is involved, `unloadPlugin(String pluginId)` will not released the file handle created by `startPlugins()` method.

**Comment by decebals** [comment]
@tdong6 
Thanks for your contribution! I did a fast review on #339 and I added a comment.

**Comment by decebals** [comment]
And by the way, can you translate the code from gist in a unit test? You can add it in `AbstractPluginManagerTest` or `DefaultPluginManagerTest`.

**Comment by tdong6** [comment]
@decebals Thanks for your feedback. 
I did a quick look on how I can translate what I have been doing to a unit test but haven't found a way to do that.
What that gist does is straight forward: loading and starting a plugin, then stopping and unloading the plugin. What makes it complicated is I need to count the number of file handles opened for that plugin at each step. What I have been doing is using `ll /proc/<pid>/fd | grep <plugin_id> | wc -l`. Any suggestions?

**Comment by decebals** [comment]
@tdong6 
I don't know a generic method to retrieve programmatically the PID of current Java process for Java < 9. You can take a look at https://stackoverflow.com/questions/4750470/how-to-get-pid-of-process-ive-just-started-within-java-program.
Another possible problem is how you run the test on Windows.
Interesting subject but I don't have time to investigate it.

**Comment by decebals** [comment]
It's similar with #217 and #355.
Today I added some code that fixes #355. Can you check to see if the patch (see d359ad7) solves your problem also? 
Thanks!

**Comment by tdong6** [comment]
@decebals Thanks, I will let you know once I get a chance. 
Just to clarify, in the patch link I only see added tests. Do you mean trying with the latest version?

**Comment by decebals** [comment]
> Just to clarify, in the patch link I only see added tests. 
I fixed the commit link.

> Do you mean trying with the latest version?
I upgraded the SNAPSHOT version to contains the fix. Try with `pf4j-3.3.0-SNAPSHOT`.

**Comment by tdong6** [comment]
@decebals `3.3.0-SNAPSHOT` fixes the issue. Thanks!
