### ISSUE TITLE
DefaultPluginStatusProvider.enablePlugin function seems to be wrong

### ISSUE THREAD

**Issue by SalomonQiu** [pf4j/pf4j#335]
In DefaultPluginStatusProvider.enablePlugin：
`FileUtils.writeLines(disabledPlugins, pluginsRoot.resolve("disabled.txt").toFile());`
should be
`FileUtil.writeLines(enabledPlugins, pluginsRoot.resolve("enabled.txt").toFile());`
I think

**Comment by decebals** [comment]
I improved the unit tests of this class (`DefaultPluginStatusProvider`).
After I read again the last sentence of https://pf4j.org/doc/disable-plugins.html 
```
If a file with enabled.txt exists then disabled.txt is ignored. See enabled.txt and disabled.txt from the demo folder.
```
I think that actual implementation is almost perfect :smile:.

The actual code is OK but a scenario is missing: `enabled.txt` file exists but `disabled.txt` doesn't exists and we want to disable a plugin.
I will come with a unit test that show the problem and a fix of the problem.
