### ISSUE TITLE
Issues with ServiceLoader used by internal JDK classes

### ISSUE THREAD

**Issue by slovdahl** [pf4j/pf4j#336]
First of all, thanks for an awesome library! We've been successfully using it in production for close to 4 years now already.

We've recently stumbled upon an issue related to `ServiceLoader` used by a plugin. A little bit of context:
- the plugin uses the JAX-WS APIs available in OpenJDK 8
- the JAX-WS implementation to use is automagically discovered using Java's built-in `ServiceLoader` mechanism (we have no control over this apart from the next point)
- the implementation to use is configurable by using a `META-INF/services/javax.xml.ws.spi.Provider` file that contains the name of the class that implements the interface
- we're currently using OpenJDK 8, and OpenJDK 8 bundles a reference implementation of `javax.xml.ws.spi.Provider` (`com.sun.xml.internal.ws.spi.ProviderImpl`)
- a critical point: [CXF](https://cxf.apache.org/) is available on the class path outside the plugin, and CXF also provides an implementation of `javax.xml.ws.spi.Provider` (`org.apache.cxf.jaxws.spi.ProviderImpl`), and has a `META-INF/services/javax.xml.ws.spi.Provider` file in its JAR that points to that implementation

Our problem is that in some cases, the plugin doesn't work correctly when the CXF implementation is used, so we would like to force the plugin to use the OpenJDK bundled one instead (or the one from the `com.sun.xml.ws:jaxws-rt` Maven package when running Java 9+). This doesn't currently seem to be possible though.

After spending some time stepping through pf4j and JDK code, I think that the problem is that the `META-INF/services/javax.xml.ws.spi.Provider` file in the plugin is never found/used by `java.util.ServiceLoader`. This is caused by `ServiceLoader` using `java.lang.ClassLoader::getResources(String)`, which is a method that isn't overriden by pf4j's `PluginClassLoader`. The `java.lang.ClassLoader::getResources(String)` method will find both the file from CXF and the one in the plugin, but the one from CXF will be earlier in the returned `Enumeration<URL>`, causing it to be used.

```java
package java.lang;

public class ClassLoader {

  public Enumeration<URL> getResources(String name) throws IOException {
        @SuppressWarnings("unchecked")
        Enumeration<URL>[] tmp = (Enumeration<URL>[]) new Enumeration<?>[2];
        if (parent != null) {
            tmp[0] = parent.getResources(name);
        } else {
            tmp[0] = getBootstrapResources(name);
        }
        tmp[1] = findResources(name);

        return new CompoundEnumeration<>(tmp);
    }
}
```

I have been thinking about how to fix this, and one workaround I came up with was to extend `PluginClassLoader` and override the `getResources(String)` method, and change it to reverse the order of the returned resources like this:
```java
class ResourcesFromPluginClassLoader extends PluginClassLoader {

    ResourcesFromPluginClassLoader( PluginManager pluginManager, PluginDescriptor pluginDescriptor ) {
        super( pluginManager, pluginDescriptor, pluginManager.getClass().getClassLoader() );
    }

    @Override
    public Enumeration<URL> getResources( String name ) throws IOException {
        @SuppressWarnings( "unchecked" )
        Enumeration<URL>[] tmp = (Enumeration<URL>[])new Enumeration<?>[2];

        tmp[0] = findResources( name );

        if ( getParent() != null ) {
            tmp[1] = getParent().getResources( name );
        }

        return new CompoundEnumeration<>( tmp );
    }
}
```

Another approach I've been thinking of (but not tested) is to override `PluginClassLoader` and add support for blacklisting certain classes/resources from being seen by a plugin. But in the end I came to the conclusion that I think this is a limitation in pf4j itself. I'd be interesting to hear your thoughts about this issue, and if you have any other ideas of how to solve/workaround it.

We're currently using the ancient pf4j 0.12.0, but I've looked through release notes and the source code and haven't seen any changes that would fix this issue.

**Comment by decebals** [comment]
Version 2.2.0 came with support for `parent first strategy` in `PluginClassLoader`. Try to use this strategy to see if it's what you need.
Also, read https://pf4j.org/doc/class-loading.html.

**Comment by slovdahl** [comment]
Thanks for the quick response!

> Version 2.2.0 came with support for `parent first strategy` in `PluginClassLoader`. Try to use this strategy to see if it's what you need.

I'm afraid that won't solve the issue. We actually want to have the `parent last strategy`, but the problem is that `PluginClassLoader` doesn't override all methods from `ClassLoader` that are relevant. And just to be clear, our problem is not actually about class loading, but about resource loading via the class loader.

`PluginClassLoader` already overrides the `ClassLoader::getResource(String)` method, but not `ClassLoader::getResources(String)`, which is the one that's used in this case. That's why I'd argue this is a bug, but I'm open to hearing other point of views as well. :slightly_smiling_face:

**Comment by decebals** [comment]
> PluginClassLoader doesn't override all methods from ClassLoader that are relevant. And just to be clear, our problem is not actually about class loading, but about resource loading via the class loader.

After a quick refresh I can say that your affirmation is true. Actual implementation of `PluginClassLoader` overrides `getResource` but doesn't override `getResources` method (your case).

The resource part of the parent first strategy from `PluginClassLoader` is useful in my case. I use PF4J to build web applications. I use Pippo (micro web framework) to create web applications and I want to have a possibility to override templates (I use Pebble for templates) of pages or components. A template can be defined in a plugin as resource and If I activated the parent first strategy in `PluginClassLoader` I have the possibility to copy/paste/modify the original template for a page/component (plugin).

**Comment by decebals** [comment]
@slovdahl 
You can propose a PR with an implementation for `PluginClassLoader#getResources`.

**Comment by decebals** [comment]
@slovdahl 
After you testing that #337 solves the problem, please close this issue. Thanks!

**Comment by slovdahl** [comment]
I'll do that, but don't hold your breath, it'll likely take some time before I get it done. I've been experimenting with updating from 0.12.0 to the latest release, but came across some breaking changes that made it a bit challenging.

**Comment by decebals** [comment]
@slovdahl Do you think that we close this issue? solve #337 this problem?

**Comment by slovdahl** [comment]
It's fine to close it. We haven't still had the time to update to a version with this change, but we're using a subclassed `PluginClassLoader` with the same approach as #337, and it has worked well for more than 6 months already.
