### ISSUE TITLE
please help me! if i want return some object from extension's method,but this object provide by third party

### ISSUE THREAD

**Issue by Ted-Engineer** [pf4j/pf4j#340]
if i want return some object from extension's method,but this object provide by third party
for example:
```java
public interface BookingPriceValidateExtension extends ExtensionPoint {

    /**
     * 
     * @param processContext 
     * @return com.ted.responsibility.common.model.price.SnapClientPriceInfo
     */
    SnapClientPriceInfo process(ProcessContext processContext);

}
```

the interface `BookingPriceValidateExtension` is provide by project **A** (the host application to load all plugin)
and the **Plugin B** Implement interface `BookingPriceValidateExtension`
The **Plugin B** is develop by other group and the class `SnapClientPriceInfo` provide by
third party
so the problem :
 No.1 If `SnapClientPriceInfo` has some update, the project A and Plugin B should synchronous update
 No.2 In the Plugin B, the class `SnapClientPriceInfo` loaded by `PluginClassLoader`, but project A's SnapClientPriceInfo loaded by main classloader, so what can i do to execute this code in project A
```java
List<BookingPriceValidateExtension> list = pluginManager.getExtensions(BookingPriceValidateExtension.class, "pluginId")

SnapClientPriceInfo result = list.get(0).process(new ProcessContext());
```
when i run this code, 
```java
SnapClientPriceInfo result = list.get(0).process(new ProcessContext());
```
will throw some exception like previously initiated loading for a different type with name "com/........./SnapClientPriceInfo",
because the class `SnapClientPriceInfo` has been load by `PluginClassloader` and `MainClassLoader`
so i think the one of the solution is all of the extension's return value must be load by `MainClassLoader`, but the return object coms from different maven's coordinate,i can't 
add the package name to `PluginClassLoader` usually because i can't update maven version regularly.
 the other solution is create one class exactly like the return object,the difference between them is the created is in project A, their package names are the same,so i can modify the PluginClassLoader's loadClass method , if the class's package is same as the package name,i can getParent().loadClass.
but this solution is too complex and waste more time , i want know how would you solve this problem.

**Comment by Ted-Engineer** [comment]
i'm from china, my english is not good enough, please be tolerant

**Comment by decebals** [comment]
It's not a problem with your English, as long as I understand what is your problem.
To do a recap, you say that your application define an extension point like `BookingPriceValidateExtension`. The returned type value of `process` method is `SnapClientPriceInfo`, and this part from an external library (third party).
A plugin **B** comes with a concrete extension for `BookingPriceValidateExtension` extension point.

> If SnapClientPriceInfo has some update, the project A and Plugin B should synchronous update

Yes if you want to update your project to us the the update.

> In the Plugin B, the class SnapClientPriceInfo loaded by PluginClassLoader, but project A's SnapClientPriceInfo loaded by main classloader, so what can i do to execute this code in project A

I think that in this case the solution is simple. If you use Maven for example, mark the third party library that contributes with `SnapClientPriceInfo` in **Plugin B** with scope **provided**.
In this mode, Plugin B will use `SnapClientPriceInfo` loaded by `ApplicationClassLoader`.
See https://github.com/pf4j/pf4j/blob/master/demo/plugins/pom.xml#L87 and https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html.
If you use Gradle or other build tools the idea is the same, to avoid to load `SnapClientPriceInfo` in Plugin B, with PluginClassLoader.

**Comment by Charliezq** [comment]
![image](https://user-images.githubusercontent.com/33457190/66699197-24445700-ed17-11e9-87db-a3b91136a4d8.png)
is it clearly?

**Comment by Ted-Engineer** [comment]
thank you for your answer, i think if i want export a extension with a return object, this object should be export  with extension class.
