### ISSUE TITLE
how can I run my jar/zip plugin in main program without the plugin-project's dependency?

### ISSUE THREAD

**Issue by Charliezq** [pf4j/pf4j#341]
Please help! I have a maven main project.And I wanted let it to load a plugin that have a other dependency.So, when I run the plugin by the main project, the main project have to add the plugin's dependency,so that main project will not throw Exception. So the question that ,I want to ask is : **did it have any way to package plugin's project to let main project run plugins without plugin's dependency?** Appreciate you all !

**Comment by decebals** [comment]
From your explanations, it's not clear for me the nature of your problem.
Try to create your project using the [quickstart](https://pf4j.org/dev/quickstart.html) Maven archetype.
Using the quickstart archetype you can run your application with all plugins from your favorite IDE (IntelliJ IDEA in my case) with [development mode](https://pf4j.org/doc/development-mode.html). For deployment (non development - production) you need to package your plugins in zip/jar archives. I think that quickstart is the correct answer at your question.
If you consider that my answer is not what you are looking for (it doesn't resolve your problem), please add a comment with more clarifications.

**Comment by Charliezq** [comment]
![image](https://user-images.githubusercontent.com/33457190/66699375-efd19a80-ed18-11e9-97b9-deb8e24eb398.png)

is it clearly?

**Comment by decebals** [comment]
Yes, it's clear. I don't understand why the problem appears. The plugin must contains a dependency to commons-lang3 and that is all. If you are using already the commons-lang3 in application then use `scope` **provided** in plugin's pom.xml.

**Comment by decebals** [comment]
Check that you plugin zip/jar contains commons-lang3.

**Comment by Charliezq** [comment]
Plugin's jar contain pom with commons-lang3's dependency.Plugin's jar didn't contain commons-lang3's jar.My purpose is running  application without plugin's dependency in application's project.

**Comment by decebals** [comment]
So, you have two possibilities when you create the Plugin jar:
- create a FAT jar that contains all the plugin's dependencies (the standard behavior in PF4J)
- create a small jar that contains only the code of plugin, and put the plugin's dependencies in the classpath of application

Other variants you don't have.

**Comment by Charliezq** [comment]
If I create a FAT jar,what's the structure of it.

**Comment by decebals** [comment]
As I wrote in one of my previous comments, try to start with a quickstart project and study a little bit the demo. Both (quickstart and demo) contain a plugin that has commons-lang as dependency.

**Comment by decebals** [comment]
You're welcome.
If everything is OK for you, please close this issue. Thanks!

**Comment by nadilas** [comment]
@decebals great library! Working perfectly once distributed. My issue right now is, that the main project when I'm running in development mode from IntelliJ directly, the program doesn't see the dependency. Could it be that development mode doesn't load the fat-jars, but uses the slim jars without the dependencies?
