### ISSUE TITLE
Will support  load plugin from main.resources?

### ISSUE THREAD

**Issue by 1125612673** [pf4j/pf4j#344]
![spring boot slf4j](https://user-images.githubusercontent.com/56629753/67862920-ec823f80-fb5d-11e9-9100-cddbc86c70fa.png)

Our project run in docker,  if we can package it include the plugins in the  spring boot jar, it's will be convenient for us to deploy the project.

**Comment by decebals** [comment]
Out of the box is not possible. PF4J is very flexible/configurable and I think that with few changes of some behaviors/components your scenario can be supported.
Start with reading [Custom manager](https://pf4j.org/doc/custom-manager.html) section of documentation. The first step is to implement a proper `PluginRepository` and `PluginLoader` and inject these components in `PluginManager`.
