### ISSUE TITLE
extensions.idx file error, please help

### ISSUE THREAD

**Issue by AmenaMRafiq** [pf4j/pf4j#345]
Hi, 

I have tried to recreate the demo as a maven project in Eclipse, with api, app and plugins as maven modules. I have pretty much copied the demo with plugin1, just renamed files. 
The welcome plugin is NewLoadMessagePlugin whose interface in the api folder just has a string method that returns a string - literally the same functionality as the demo.
I have a plugin.properties file and all the pom files as needed. 
I enabled annotation processing in eclipse, but nothing changed. 
Is there something else in the log that could be a problem? If anyone has any ideas as to what could be causing this I'd be very grateful.

If there is any other file you might want to see to help, I'll provide it. 

Here is the log from the console:

> 0 [main] INFO org.pf4j.DefaultPluginStatusProvider  - Enabled plugins: [new-message-plugin]
1 [main] INFO org.pf4j.DefaultPluginStatusProvider  - Disabled plugins: []
20 [main] INFO org.pf4j.DefaultPluginManager  - PF4J version 3.1.0 in 'deployment' mode
20 [main] DEBUG org.pf4j.AbstractPluginManager  - Lookup plugins in 'plugins'
28 [main] DEBUG org.pf4j.AbstractPluginManager  - Found 3 possible plugins: [plugins\target, plugins\plugin1, plugins\.settings]
28 [main] DEBUG org.pf4j.AbstractPluginManager  - Use 'org.pf4j.CompoundPluginDescriptorFinder@6d9c638' to find plugins descriptors
28 [main] DEBUG org.pf4j.AbstractPluginManager  - Finding plugin descriptor for plugin 'plugins\target'
28 [main] DEBUG org.pf4j.CompoundPluginDescriptorFinder  - 'org.pf4j.PropertiesPluginDescriptorFinder@7dc5e7b4' is applicable for plugin 'plugins\target'
28 [main] DEBUG org.pf4j.PropertiesPluginDescriptorFinder  - Lookup plugin descriptor in 'plugins\target\plugin.properties'
38 [main] DEBUG org.pf4j.CompoundPluginDescriptorFinder  - Cannot find 'plugins\target\plugin.properties' path
39 [main] DEBUG org.pf4j.CompoundPluginDescriptorFinder  - Try to continue with the next finder
39 [main] DEBUG org.pf4j.CompoundPluginDescriptorFinder  - 'org.pf4j.ManifestPluginDescriptorFinder@5e91993f' is applicable for plugin 'plugins\target'
40 [main] ERROR org.pf4j.CompoundPluginDescriptorFinder  - Cannot find the manifest path
org.pf4j.PluginRuntimeException: Cannot find the manifest path
	at org.pf4j.ManifestPluginDescriptorFinder.readManifest(ManifestPluginDescriptorFinder.java:75)
	at org.pf4j.ManifestPluginDescriptorFinder.find(ManifestPluginDescriptorFinder.java:56)
	at org.pf4j.CompoundPluginDescriptorFinder.find(CompoundPluginDescriptorFinder.java:65)
	at org.pf4j.AbstractPluginManager.loadPluginFromPath(AbstractPluginManager.java:795)
	at org.pf4j.DefaultPluginManager.loadPluginFromPath(DefaultPluginManager.java:130)
	at org.pf4j.AbstractPluginManager.loadPlugins(AbstractPluginManager.java:224)
	at org.bio_project.extendible_clustering_package.MainClass.main(MainClass.java:18)
42 [main] ERROR org.pf4j.AbstractPluginManager  - No PluginDescriptorFinder for plugin 'plugins\target'
org.pf4j.PluginRuntimeException: No PluginDescriptorFinder for plugin 'plugins\target'
	at org.pf4j.CompoundPluginDescriptorFinder.find(CompoundPluginDescriptorFinder.java:84)
	at org.pf4j.AbstractPluginManager.loadPluginFromPath(AbstractPluginManager.java:795)
	at org.pf4j.DefaultPluginManager.loadPluginFromPath(DefaultPluginManager.java:130)
	at org.pf4j.AbstractPluginManager.loadPlugins(AbstractPluginManager.java:224)
	at org.bio_project.extendible_clustering_package.MainClass.main(MainClass.java:18)
42 [main] DEBUG org.pf4j.AbstractPluginManager  - Use 'org.pf4j.CompoundPluginDescriptorFinder@6d9c638' to find plugins descriptors
42 [main] DEBUG org.pf4j.AbstractPluginManager  - Finding plugin descriptor for plugin 'plugins\plugin1'
43 [main] DEBUG org.pf4j.CompoundPluginDescriptorFinder  - 'org.pf4j.PropertiesPluginDescriptorFinder@7dc5e7b4' is applicable for plugin 'plugins\plugin1'
43 [main] DEBUG org.pf4j.PropertiesPluginDescriptorFinder  - Lookup plugin descriptor in 'plugins\plugin1\plugin.properties'
48 [main] DEBUG org.pf4j.AbstractPluginManager  - Found descriptor PluginDescriptor [pluginId=new-message-plugin, pluginClass=org.bio_project.extendible_clustering_package.NewLoadMessage.NewLoadMessagePlugin, version=0.0.1, provider=Amena, dependencies=[], description=, requires=*, license=null]
48 [main] DEBUG org.pf4j.AbstractPluginManager  - Class 'org.bio_project.extendible_clustering_package.NewLoadMessage.NewLoadMessagePlugin' for plugin 'plugins\plugin1'
48 [main] DEBUG org.pf4j.AbstractPluginManager  - Loading plugin 'plugins\plugin1'
49 [main] DEBUG org.pf4j.CompoundPluginLoader  - 'org.pf4j.JarPluginLoader@2401f4c3' is not applicable for plugin 'plugins\plugin1'
49 [main] DEBUG org.pf4j.CompoundPluginLoader  - 'org.pf4j.DefaultPluginLoader@7637f22' is applicable for plugin 'plugins\plugin1'
49 [main] DEBUG org.pf4j.AbstractPluginManager  - Loaded plugin 'plugins\plugin1' with class loader 'org.pf4j.PluginClassLoader@762efe5d'
49 [main] DEBUG org.pf4j.AbstractPluginManager  - Creating wrapper for plugin 'plugins\plugin1'
50 [main] DEBUG org.pf4j.AbstractPluginManager  - Created wrapper 'PluginWrapper [descriptor=PluginDescriptor [pluginId=new-message-plugin, pluginClass=org.bio_project.extendible_clustering_package.NewLoadMessage.NewLoadMessagePlugin, version=0.0.1, provider=Amena, dependencies=[], description=, requires=*, license=null], pluginPath=plugins\plugin1]' for plugin 'plugins\plugin1'
51 [main] DEBUG org.pf4j.AbstractPluginManager  - Use 'org.pf4j.CompoundPluginDescriptorFinder@6d9c638' to find plugins descriptors
51 [main] DEBUG org.pf4j.AbstractPluginManager  - Finding plugin descriptor for plugin 'plugins\.settings'
51 [main] DEBUG org.pf4j.CompoundPluginDescriptorFinder  - 'org.pf4j.PropertiesPluginDescriptorFinder@7dc5e7b4' is applicable for plugin 'plugins\.settings'
51 [main] DEBUG org.pf4j.PropertiesPluginDescriptorFinder  - Lookup plugin descriptor in 'plugins\.settings\plugin.properties'
51 [main] DEBUG org.pf4j.CompoundPluginDescriptorFinder  - Cannot find 'plugins\.settings\plugin.properties' path
51 [main] DEBUG org.pf4j.CompoundPluginDescriptorFinder  - Try to continue with the next finder
51 [main] DEBUG org.pf4j.CompoundPluginDescriptorFinder  - 'org.pf4j.ManifestPluginDescriptorFinder@5e91993f' is applicable for plugin 'plugins\.settings'
52 [main] ERROR org.pf4j.CompoundPluginDescriptorFinder  - Cannot find the manifest path
org.pf4j.PluginRuntimeException: Cannot find the manifest path
	at org.pf4j.ManifestPluginDescriptorFinder.readManifest(ManifestPluginDescriptorFinder.java:75)
	at org.pf4j.ManifestPluginDescriptorFinder.find(ManifestPluginDescriptorFinder.java:56)
	at org.pf4j.CompoundPluginDescriptorFinder.find(CompoundPluginDescriptorFinder.java:65)
	at org.pf4j.AbstractPluginManager.loadPluginFromPath(AbstractPluginManager.java:795)
	at org.pf4j.DefaultPluginManager.loadPluginFromPath(DefaultPluginManager.java:130)
	at org.pf4j.AbstractPluginManager.loadPlugins(AbstractPluginManager.java:224)
	at org.bio_project.extendible_clustering_package.MainClass.main(MainClass.java:18)
52 [main] ERROR org.pf4j.AbstractPluginManager  - No PluginDescriptorFinder for plugin 'plugins\.settings'
org.pf4j.PluginRuntimeException: No PluginDescriptorFinder for plugin 'plugins\.settings'
	at org.pf4j.CompoundPluginDescriptorFinder.find(CompoundPluginDescriptorFinder.java:84)
	at org.pf4j.AbstractPluginManager.loadPluginFromPath(AbstractPluginManager.java:795)
	at org.pf4j.DefaultPluginManager.loadPluginFromPath(DefaultPluginManager.java:130)
	at org.pf4j.AbstractPluginManager.loadPlugins(AbstractPluginManager.java:224)
	at org.bio_project.extendible_clustering_package.MainClass.main(MainClass.java:18)
53 [main] DEBUG org.pf4j.DependencyResolver  - Graph: 
   new-message-plugin -> []
53 [main] DEBUG org.pf4j.DependencyResolver  - Plugins order: [new-message-plugin]
53 [main] INFO org.pf4j.AbstractPluginManager  - Plugin 'new-message-plugin@0.0.1' resolved
54 [main] INFO org.pf4j.AbstractPluginManager  - Start plugin 'new-message-plugin@0.0.1'
54 [main] DEBUG org.pf4j.DefaultPluginFactory  - Create instance for plugin 'org.bio_project.extendible_clustering_package.NewLoadMessage.NewLoadMessagePlugin'
NewLoadMessagePlugin.start()
56 [main] DEBUG org.pf4j.AbstractExtensionFinder  - Finding extensions of extension point 'org.bio_project.extendible_clustering_package.api.LoadMessage'
56 [main] DEBUG org.pf4j.LegacyExtensionFinder  - Reading extensions storages from classpath
56 [main] DEBUG org.pf4j.LegacyExtensionFinder  - Cannot find 'META-INF/extensions.idx'
56 [main] DEBUG org.pf4j.AbstractExtensionFinder  - No extensions found
56 [main] DEBUG org.pf4j.LegacyExtensionFinder  - Reading extensions storages from plugins
56 [main] DEBUG org.pf4j.LegacyExtensionFinder  - Reading extensions storage from plugin 'new-message-plugin'
56 [main] DEBUG org.pf4j.LegacyExtensionFinder  - Read 'META-INF/extensions.idx'
56 [main] DEBUG org.pf4j.LegacyExtensionFinder  - Cannot find 'META-INF/extensions.idx'
56 [main] DEBUG org.pf4j.AbstractExtensionFinder  - No extensions found
56 [main] DEBUG org.pf4j.AbstractExtensionFinder  - Finding extensions of extension point 'org.bio_project.extendible_clustering_package.api.LoadMessage' for plugin 'null'
56 [main] DEBUG org.pf4j.AbstractExtensionFinder  - Finding extensions of extension point 'org.bio_project.extendible_clustering_package.api.LoadMessage' for plugin 'new-message-plugin'
56 [main] DEBUG org.pf4j.AbstractExtensionFinder  - Found 0 extensions for extension point 'org.bio_project.extendible_clustering_package.api.LoadMessage'
Found 0 extensions for extension point 'org.bio_project.extendible_clustering_package.api.LoadMessage'

**### EDIT**

inside the plugin an extensions.idx file exists at path:

ProjectName\plugins\plugin1\target\classes\META-INF

the contents of the extension.idx file is:

> "# Generated by PF4J
org.bio_project.extendible_clustering_package.NewLoadMessage.NewLoadMessagePlugin$NewLoadMessage"

**Comment by decebals** [comment]
After I analysed the log supplied by you, I found some (possible) problems.

> 28 [main] DEBUG org.pf4j.AbstractPluginManager - Found 3 possible plugins: [plugins\target, plugins\plugin1, plugins.settings]

Your "plugins" directory is not "clean". It contains subdirectories that are not plugins (`target` and `settings`). If you take at the structure of the [pugins](https://github.com/pf4j/pf4j/tree/master/demo/plugins) directory of the demo that comes with PF4J, it's clean (only plugins and some config files - enabled, disabled).

If you want to preserve actual layout of `plugins` directory, I think that you can fix very fast the problem with [DefaultPluginRepository#createHiddenPluginFilter](https://github.com/pf4j/pf4j/blob/ee3b5f2276e98526511ecbb237a51da8c48b028b/pf4j/src/main/java/org/pf4j/DefaultPluginRepository.java#L61) (more details ata https://github.com/pf4j/pf4j/issues/1).

> 56 [main] DEBUG org.pf4j.AbstractExtensionFinder - Finding extensions of extension point 'org.bio_project.extendible_clustering_package.api.LoadMessage'
56 [main] DEBUG org.pf4j.LegacyExtensionFinder - Reading extensions storages from classpath
56 [main] DEBUG org.pf4j.LegacyExtensionFinder - Cannot find 'META-INF/extensions.idx'
56 [main] DEBUG org.pf4j.AbstractExtensionFinder - No extensions found
56 [main] DEBUG org.pf4j.LegacyExtensionFinder - Reading extensions storages from plugins
56 [main] DEBUG org.pf4j.LegacyExtensionFinder - Reading extensions storage from plugin 'new-message-plugin'
56 [main] DEBUG org.pf4j.LegacyExtensionFinder - Read 'META-INF/extensions.idx'
56 [main] DEBUG org.pf4j.LegacyExtensionFinder - Cannot find 'META-INF/extensions.idx'
56 [main] DEBUG org.pf4j.AbstractExtensionFinder - No extensions found
56 [main] DEBUG org.pf4j.AbstractExtensionFinder - Finding extensions of extension point 'org.bio_project.extendible_clustering_package.api.LoadMessage' for plugin 'null'
56 [main] DEBUG org.pf4j.AbstractExtensionFinder - Finding extensions of extension point 'org.bio_project.extendible_clustering_package.api.LoadMessage' for plugin 'new-message-plugin'
56 [main] DEBUG org.pf4j.AbstractExtensionFinder - Found 0 extensions for extension point 'org.bio_project.extendible_clustering_package.api.LoadMessage'
Found 0 extensions for extension point 'org.bio_project.extendible_clustering_package.api.LoadMessage'

PF4J tries to find, using different strategies, where is located the `extensions.idx`file of `new-message-plugin` plugin. In the end, the files that describe the extensions that come with your plugin is not found.

You can try to use the [development](https://pf4j.org/doc/development-mode.html) mode when you you start your application. Now you are using `deployment`/`production` mode:
> 20 [main] INFO org.pf4j.DefaultPluginManager - PF4J version 3.1.0 in 'deployment' mode 

P.S. I will try to improve the logging to offer you (and to other persons that are new comers) the possibility to see what it's wrong with your application (from PF4J perspective). For me it's easy to "read" that information but for you probably is a screen from Matrix, the movie :smile:.
For example in

> 56 [main] DEBUG org.pf4j.LegacyExtensionFinder - Cannot find 'META-INF/extensions.idx'

is not very clear that the file is relative to `plugins\plugin1`.

I prefer to improve these aspects (to clarify the concepts and the features that already exist) instead to add new "cool" features.

**Comment by AmenaMRafiq** [comment]
Thank you @decebals !! Development mode has fixed the problem.

About improving the logging - that would be great for new people like me!
