### ISSUE TITLE
hello,I think the PluginClassLoader need take all the class package name  in "rt.jar" to findSystemClass

### ISSUE THREAD

**Issue by Ted-Engineer** [pf4j/pf4j#351]
hello,I think the PluginClassLoader need add "rt.jar"  to findSystemClass
for example  the plugin's code use dom4j:
1. `SAXReader reader = new SAXReader();`
2. `reader.setEncoding("UTF-8");`
3. `Document document = reader.read(new StringReader(config));`
the 3 line will be throw 
```java
org.xml.sax.SAXException: Can't create default XMLReader; is system property org.xml.sax.driver set?
	at org.xml.sax.helpers.XMLReaderFactory.createXMLReader(Unknown Source)
	at org.dom4j.io.SAXHelper.createXMLReader(SAXHelper.java:83)
	at org.dom4j.io.SAXReader.createXMLReader(SAXReader.java:894)
	at org.dom4j.io.SAXReader.getXMLReader(SAXReader.java:715)
	at org.dom4j.io.SAXReader.read(SAXReader.java:435)
	at org.dom4j.io.SAXReader.read(SAXReader.java:365)
```

i think the solution once and for all is take all the class package name  in "rt.jar" to findSystemClass

like this
![image](https://user-images.githubusercontent.com/11263110/69416671-14765480-0d52-11ea-9604-dc7849b5e679.png)

What do you think?

**Comment by decebals** [comment]
@Ted-Engineer 
I'm afraid that I don't understand very clear your problem.
Can you come with more details?
I need some clarification like:
1. What version of PF4J and JAVA are you use?
2. From what class is your snapshot?
3. The snapshot code with create the xml parser is from one of yours plugins?

**Comment by decebals** [comment]
Closed issue for inactivity. Please reopen it if you want.
