### ISSUE TITLE
Extension loading files behavior

### ISSUE THREAD

**Issue by alienatorZ** [pf4j/pf4j#354]
When running a unit test from a plugin using the code:
```java
 new File(getClass().getResource("/message/field.properties").toURI()).exists()
```
resolved to true.

When inside a method defined by an extension and called from the main application the same code resolved to false. 

Is there a trick to getting resources when in the context of the `PluginClassLoader`?

**Comment by decebals** [comment]
It will be nice to have a unit test that simulate this problem. Try to see what class loaders are used to resolve the class in both situations.

> Is there a trick to getting resources when in the context of the PluginClassLoader?

The same approach.

You can take a look on #337 to see if this PR didn't introduce a bug.
Try to run your application in debug mode to be able to see the details.

**Comment by decebals** [comment]
@alienatorZ 
Any news?

**Comment by decebals** [comment]
Closed issue for inactivity. Please reopen it if you want.
