### ISSUE TITLE
Cannot remove plugin jar file after unloading,same as#217

### ISSUE THREAD

**Issue by yeahCaesar** [pf4j/pf4j#355]
jgomer2001 commited issue with the same problem #217(https://github.com/jgomer2001). And I want to know , if the problem is fixed.The pf4j I'm using is 3.0.1.

**Comment by yeahCaesar** [comment]
I upgrade pf4j to 3.2.0. the problem is still there

**Comment by decebals** [comment]
The release notes for pf4j 3.2.0 is available [here](https://github.com/pf4j/pf4j/compare/release-3.1.0...release-3.2.0). It doesn't contain something related to #217.
I think that @jgomer2001 presented in #217 an workaround. On the other side, @hazemkmammu added a PR (##322) that fixed a `FileSystemException` in Windows on plugin delete.
Can you add more information about your problem (OS, the stacktrace of error, ...)?

**Comment by yeahCaesar** [comment]
of course. OS is windows with no doubt.And the web framework is spring-boot 2.1.3.RELEASE with tomcat. Sometimes, I need to upgrade the plugin (jar file). There is a scheduler task to do the upgrade.First download the latest plugin, then stop and unload the running plugin, next is deleting the jar file, and fail to delete.File.delete( ) returns 'true', but the jar file is still there. And if you try to delete the jar file again, it thows FileAccessException.When the program is shut down, the jar disappeasr immediately.
The PluginClassLoader is still in the jvm heap after calling unload( ), is this a problem?

**Comment by jgomer2001** [comment]
I faced the same as described [here](https://github.com/pf4j/pf4j/issues/217#issuecomment-391326877). Fortunately it does not show up in Linux. 

This is not a pf4j issue, but a windows jvm one IMO.

**Comment by decebals** [comment]
@yeahCaesar 
Can you reproduce the problem in a minimalist/[quickstart](https://pf4j.org/dev/quickstart.html) application? A very simple application, with just one plugin.

**Comment by yeahCaesar** [comment]
I think the information is enough to describe the problem.If you think a demo is necessary , I'll make one after work.

**Comment by yeahCaesar** [comment]
May I ask a question? In your design , after calling the method unload , which resources should be release and which resources will be still held ?

**Comment by decebals** [comment]
@yeahCaesar 
Just a curiosity, can you run [JarPluginManagerTest](https://github.com/pf4j/pf4j/blob/ee3b5f2276e98526511ecbb237a51da8c48b028b/pf4j/src/test/java/org/pf4j/JarPluginManagerTest.java) with success? I am interested by `deletePlugin` test.
Do you use `zip` or `jar` for your plugins packaging?

**Comment by decebals** [comment]
@yeahCaesar 
> May I ask a question? In your design , after calling the method unload , which resources should be release and which resources will be still held ?

In `unloadPlugin` method we close the plugin class loader.
The idea is that after you stop a plugin you can call start plugin and the same class loader is used.
Actually, the `deletePlugin` method (see the implementation from `AbstractPluginManager`) deletes the plugin from system (jar/zip file).
More details about `ClassLoader#close` you can find in [Java documentation](https://docs.oracle.com/javase/8/docs/technotes/guides/net/ClassLoader.html).
From documentation:
> owever, since it can't be predicted exactly when finalization and garbage collection will occur, problems are caused for applications which need to be able to do this in a predictable and timely fashion. It is a problem on Windows, because open files cannot be deleted or replaced.

If we cannot reproduce the problem with a unit test we cannot play with the possible solutions.

**Comment by yeahCaesar** [comment]
@decebals 
OK.Consider this, is it possible that the PluginClassLoader  is still held the jar file handle after unloading?As we can see , delete( ) returns true and the jar file disappeared after program shutdown.And I'm trying to reproduce the problem to a unit test, but I have to take some conditions in.

**Comment by yeahCaesar** [comment]
@decebals 
please take a look at the picture, the unit test code can show the problem
![175135](https://user-images.githubusercontent.com/19277364/70313714-13b0e880-1851-11ea-8647-f9c1a807e540.png)

**Comment by decebals** [comment]
@yeahCaesar 
I think that you misunderstood me. First of all, please answer me to my questions:
> Just a curiosity, can you run `JarPluginManagerTest` with success? I am interested by `deletePlugin ` test.

Secondary, in your unit test your, the flow used by you is to unload the plugin via the `unloadPlugin` method and delete the jar file. As I said in my latest comment (https://github.com/pf4j/pf4j/issues/355#issuecomment-562481142) the correct method to delete the plugin from the file system is to use directly `deletePlugin` method.

**Comment by yeahCaesar** [comment]
@decebals 
1. JarPluginManagerTest is successful.
2.whatever calling file.delete or deletePlugin, the file is still there before  stopping the program.And the PluginManager is DefaultPluginManager by the injection .

**Comment by chingjustwe** [comment]
> @decebals
> 
> 1. JarPluginManagerTest is successful.
>    2.whatever calling file.delete or deletePlugin, the file is still there before  stopping the program.And the PluginManager is DefaultPluginManager by the injection .

Caesar, the problem is related with [FileUtils.java](https://github.com/pf4j/pf4j/blob/master/pf4j/src/main/java/org/pf4j/util/FileUtils.java), the method **getPath()** did not close the Stream of FileSystem.

Should implement like below:
> try {
>     FileSystem fs = getFileSystem(uri);
>     return fs.getPath(first, more);
> } finally {
>     fs.close();
> }

**Comment by yeahCaesar** [comment]
@decebals 
Like chingjustwe said , there is a problem in the method getPath(), the fileStream is not released, so we can't delete jar file even we unload the plugin.
I fixed the problem and created a pull request(https://github.com/pf4j/pf4j/pull/356) for this.
Please verify.

**Comment by yeahCaesar** [comment]
> I faced the same as described [here](https://github.com/pf4j/pf4j/issues/217#issuecomment-391326877). Fortunately it does not show up in Linux.
> 
> This is not a pf4j issue, but a windows jvm one IMO.

Hi @jgomer2001 , it is a problem caused by the java code , not the OS. Linux and windows have different way to deal with files, in this case , actually, when we delete the file , linux just stash the file or dir ,not the real delete, and windows deletes the file or dir until the program which holds the file is stopped.There is a problem in pf4j ,though not fatal, but a problem.See #356

**Comment by decebals** [comment]
To be clear, the problem only appeared on __Windows__.
