### ISSUE TITLE
Calls to File.mkdirs() in unzip logic may silently fail

### ISSUE THREAD

**Issue by slovdahl** [pf4j/pf4j#359]
While debugging some issues related to module loading, I noticed that the return value of calls to `File.mkdirs()` in `org.pf4j.util.Unzip` isn't validated. The `mkdirs()` method doesn't usually throw exceptions in case the directory/directories can't be created.

I guess there can be other failures later on if there's no directory to unzip files to, but I think it would at least make sense to log something about the fact that creating directories failed.

**Comment by decebals** [comment]
@slovdahl 
Can you come with a PR? Thanks!

**Comment by slovdahl** [comment]
> @slovdahl
> Can you come with a PR? Thanks!

Absolutely!

What do you think would be the best course of action, just logging, or an exception? I'd be inclined to say that an exception would be warranted, because it could certainly cause other types of errors down the line if it's just logged.

**Comment by decebals** [comment]
I think that you talk about [Unzip#extract](https://github.com/pf4j/pf4j/blob/master/pf4j/src/main/java/org/pf4j/util/Unzip.java#L86) method.
In this case, I see that the signature of the method contains already `throws IOException` and we can throw an `IOException` if something goes wrong on `file.mkdirs`. 
Also we can remove the logger completely and the the entire `catch (FileNotFoundException e)` because of course `FileNotFoundException`  is an `IOException`.
What you say?

**Comment by decebals** [comment]
The idea is to pass the responsibility of making a decision to the caller.

**Comment by slovdahl** [comment]
> I think that you talk about Unzip#extract method.

Exactly, thanks for making that explicit :+1: 

>  In this case, I see that the signature of the method contains already throws IOException and we can throw an IOException if something goes wrong on file.mkdirs.
Also we can remove the logger completely and the the entire catch (FileNotFoundException e) because of course FileNotFoundException is an IOException.
What you say?

> The idea with throws IOException is to pass the responsibility of making a decision to the caller.

Very reasonable thoughts IMO. I will submit a PR with the suggested changes after the christmas holidays.

**Comment by decebals** [comment]
@slovdahl 
Do you have any news?

**Comment by slovdahl** [comment]
Coincidentally, I had planned on getting the MR submitted today :slightly_smiling_face: Stay tuned.
