### ISSUE TITLE
Order of classpath loading in plugins

### ISSUE THREAD

**Issue by moley** [pf4j/pf4j#368]
Hi, 

The `DevelopmentPluginLoader` makes development very easy, but one thing I think can be improved. Currently the maven/gradle/kotlin classpaths comes BEFORE the idea classpath. Therefore you always have to call the build on console before you can start your application. In my opinion it would be better to have the IDE's classpath first to be able to restart even with idea's included build. 
What do you think?

**Comment by decebals** [comment]
@moley 

Please read https://github.com/pf4j/pf4j/pull/323. Short story is that I don't use IDE's classpath (I use IntelliJ but my projects are Maven and they use the Maven convention for output files). Maybe @hank-cp can help. In the end, if you consider that it's an issue, please create a PR.

**Comment by moley** [comment]
@decebals 
OK, thank you for your answer. I have solved it by building my projects in IDEA with gradle before launching. So for me it's totally OK. If you want you can close this suggestion
