### ISSUE TITLE
Is pf4j.ignoreExtensionPoint supposed to work with abstract ExtensionPoint?

### ISSUE THREAD

**Issue by GunoH** [pf4j/pf4j#369]
Hi,

Using an abstract class as extension point, which does **not** implement `org.pf4j.ExtensionPoint` (combined with the compiler arg `-Apf4j.ignoreExtensionPoint` that was added for #350), gives me the following compilation error:
`Error:(32,8) java: com.foo.MyExtension is not an extension (it doesn't implement any interface)`

According to the [pf4j docs](https://pf4j.org/doc/extensions.html), an extension point can either be an interface or an abstract class. Therefore I do not agree with the error message; `MyExtension` **is** an extension, because it extends an extension point (which happens to be an abstract class instead of an interface). So it should just work :-)

Am I missing something here? Is this supposed to work? Could this be a bug in pf4j?

Thanks,
Guno

**Comment by decebals** [comment]
@GunoH 
Take a look on https://github.com/pf4j/pf4j/issues/358. 
I created already a PR (https://github.com/pf4j/pf4j/pull/360) to solve some of the issues discussed in https://github.com/pf4j/pf4j/issues/358 but I think that it's not too much interest for this PR.

**Comment by GunoH** [comment]
Thanks. I agree. Don't think #360 will help much for the issue I'm having.

I can see why it could be difficult to determine from `ExtensionAnnotationProcessor#findExtensionPoints` which of `MyExtension`'s super classes would be the actual extension point, so I'm not counting on a fix for that soon. 

The error message could be improved a bit though, because it made me doubt whether using an abstract class as extension point was supported by pf4j in the first place. Maybe something like `"Cannot use %s as extension point with " + IGNORE_EXTENSION_POINT + " compiler arg (it doesn't implement any interface)"`. Should I add a PR for that?

**Comment by decebals** [comment]
>  Should I add a PR for that?

Yes. Please add a PR.

**Comment by decebals** [comment]
@GunoH 
Can we close this issue?

**Comment by GunoH** [comment]
Yes, let's close it.
