### ISSUE TITLE
The plug-in developed by pf4j extends the front-end page, what are the good solutions?

### ISSUE THREAD

**Issue by fendo8888** [pf4j/pf4j#373]
I want to implement plug-in development of website functions through pf4j, but how do front-end pages provide extension points and expand through pf4j, is there any good solution?

**Comment by decebals** [comment]
It's not a simple answer.
Things get a little simpler if you use a Java web framework. For example I use PF4J to develop modular web applications using [Pippo](http://www.pippo.ro/) (I am the initiator of this project) and [Wicket](https://github.com/pf4j/pf4j-wicket). I know that other people use PF4J with [Vert.x](https://vertx.io/). If you use a JavaScript web frameworks (Angular, VueJS, ReactJS), PF4J could help you to modularize the rest services/controllers.
