### ISSUE TITLE
High vulnerable issue in whitesource scan

### ISSUE THREAD

**Issue by KoushikMaity** [pf4j/pf4j#375]
Hi,
The latest version of PF4J which 0.6.0 is using high vulnerable library Apache Log4j log4j:log4j:1.2.17. In whitesource scan it is posing as high security threat.
Which is coming as indirect dependency  in our application.
Kindly fix this version.

Thanks,
Koushik Maity

**Comment by decebals** [comment]
The problem is already solved by https://github.com/pf4j/pf4j/commit/fd72b5389257ef2a38b71e5f0f45e09e26b3501a.

**Comment by decebals** [comment]
Log4j is only used on demo and quickstart Maven archetype.
