### ISSUE TITLE
Question - environment variables and security

### ISSUE THREAD

**Issue by zhaoqingchris** [pf4j/pf4j#379]
- What is best practice to execute code from plugins written by pf4j with restricted permission? For example, I don't want the plugin to access my local file systems

- What is the recommended way to manage environment variables, e.g between test , staging and production?

I cannot find the information that address above two questions in the documentation.  Any help will be appreciated

Thanks,

**Comment by decebals** [comment]
> - What is best practice to execute code from plugins written by pf4j with restricted permission? For example, I don't want the plugin to access my local file systems

You can use a [SecurityManager](https://docs.oracle.com/javase/7/docs/api/java/lang/SecurityManager.html) in your application.

They are some issues/comments that make reference to this subject:
- https://github.com/pf4j/pf4j/issues/182#issuecomment-482171431
- https://github.com/pf4j/pf4j/issues/127

Pseudocode:
```java
public class PluginSecurityManager extends SecurityManager {

    private String pluginDir; // or PluginManager instance

    public PluginSecurityManager (String dir) {
        pluginDir = dir;
    }

    // ... other methods 
 
    public void checkRead (String file) {
        // check code here and throw SecurityException if something is wrong
    }

    public void checkWrite (String file) {
        // check code here and throw SecurityException if something is wrong
    }

}
```

You can take a look on https://learnsomethingquick.com/java-applications-with-plugins-security/, maybe it helps you.

> - What is the recommended way to manage environment variables, e.g between test , staging and production?

I cannot make a recommendation on this subject. Maybe other developer can help you.

**Comment by chris-pccw** [comment]
Thank you so much for above information @decebals. Another question, we could customise the directory where we store plugins by setting system property `pf4j.pluginsDir`, what if I want to store the plugins in cloud storage like aws s3?  I had a look at `AbstractPluginManager`, seems like `createPluginsRoot` function always return `java.nio.file.Path`, not `InputStream`

**Comment by decebals** [comment]
> what if I want to store the plugins in cloud storage like aws s3?

If you cannot use `Path` to specify the `pluginsDir` or the path of plugin, it means that It's not possible to use a `PluginManager` that comes with PF4J. I think that you need to write a custom `PluginManager`.

**Comment by decebals** [comment]
@zhaoqingchris Can we close this issue? Do you need more information?
If my explanations helped you to solve the problem, it would be nice if you can share with us some information about your final solution (some technical aspects, code snippet, ...).

**Comment by chris-pccw** [comment]
Yeah I am happy to close this issue for now. Thanks @decebals

**Comment by Crispy-fried-chicken** [comment]
I wander whether the createPluginsRoot will have some CWE-22 vulnerability. The function `createPluginsRoot()` reads a directory path from a system property (`PLUGINS_DIR_PROPERTY_NAME`) and directly creates Path objects using `Paths.get()` without any validation or sanitization. This allows an attacker who can control the system property to specify arbitrary file paths, including paths using relative path traversal sequences like `../` to access files outside the intended plugins directory. The code does not normalize paths or verify that the resulting path stays within an expected directory boundary. While this might be intended for administrator configuration, the lack of input validation makes it a potential path traversal vulnerability (CWE-22).
