### ISSUE TITLE
classloading child first strategy suggestion/question

### ISSUE THREAD

**Issue by asafbennatan** [pf4j/pf4j#382]
Hi,
looking at the default(child first) class loading strategy pf4j provides it loads class in this order:
1.local
2.dependencies
3.parent

wont it be better to change it so the order is :
1.local
2.parent
3.dependencies

this will ensure that class is loaded from dependency only if required causing less "dependency hell",
in my use case i have a shared parent class loader loading some base classes so this issue is more observant

**Comment by decebals** [comment]
It's difficult to make this modification in current default implementation because for some projects this modification will change the current behavior without any notification. 

You need a custom implementation of PluginClassLoader for your use case.

If anyone has another opinion, I'm glad to hear it.

**Comment by asafbennatan** [comment]
understood , already did that , i do think it might be a good idea to expose some of the used method as protected so its easier to extend / allow to configure the loading order  ( since we only have three loading components : local,parent and dependencies)

**Comment by decebals** [comment]
> understood , already did that , i do think it might be a good idea to expose some of the used method as protected so its easier to extend / allow to configure the loading order ( since we only have three loading components : local,parent and dependencies)

My first thought was this, but after taking a look at the code of [PluginClassLoader](https://github.com/pf4j/pf4j/blob/master/pf4j/src/main/java/org/pf4j/PluginClassLoader.java) I realized that the code is quite well structured. Maybe we can modify the modifier of `*FromDependecies` methods from `private` to `protected` if you think that is useful. Also if you see other refactoring steps to improve the readability and extensibility of `PluginClassLoader` please create a PR and we will analyse this PR.

**Comment by asafbennatan** [comment]
https://github.com/pf4j/pf4j/pull/385 contains a change for better customization of PluginClassLoader

**Comment by decebals** [comment]
Solved by #385.
