### ISSUE TITLE
FileSystemException when deleting Plugins

### ISSUE THREAD

**Issue by Euklios** [pf4j/pf4j#389]
Me and two friends of mine are currently working on a project, using pf4j.

The person responsible for the frontend is currently implementing the views, corresponding to plugin-management, and was playing around with some endpoints (especially upload and delete).

Our setup may be a bit special, as we are working in development mode:
Structure:
```
- container
- shared
- plugins
    - plugin1
```
All of the mentioned folders are maven-modules. We are using the development mode to load them without packaging.

`pf4j.mode=development`
`pf4j.pluginsDir=./plugins`
As our plugins-folder is located in the root folder of our project.

OS: Windows
Java target-version: 11
Runntime-version: 14

Steps:
* If we delete the plugin using `PluginManager.deletePlugin` all files, related to the plugin (including sources) are removed by pf4j as expected.
* After a combination of uploading a fat-jar into the plugins folder and `PluginManager.loadPlugin`, everything appears to be okay.
* If we now delete the plugin again, pf4j fails with a `FileSystemException`, when deleting the files.
* If we now retry the delete, pf4j complains about the plugin-id being unknown. However, the jar is still there.

When testing, I noticed that the jar-file is not locked until the call to `PluginManager.deletePlugin`. However, the lock was left in place until we restarted the backend. 

I'm not sure if this is even fixable (as I don't know why the file is locked), but I'd prefer it if pf4j would indicate some kind of failed state, or return to the stopped state and afterward throw an exception, to show the failed removal.

Attached: [logs.txt](https://github.com/pf4j/pf4j/files/4974507/logs.txt)

**Comment by decebals** [comment]
Please try with the latest version of PF4J. Maybe your problem is related to https://github.com/pf4j/pf4j/issues/355.

**Comment by decebals** [comment]
Close it due to lack of response. You can reopen it with a new comment.
