### ISSUE TITLE
ClassLoadingStrategy.java: Incorrect enum selection in ADP strategy

### ISSUE THREAD

**Issue by srosenthal13** [pf4j/pf4j#391]
`    /**
     * application(parent) -> dependencies -> plugin
     */
    public static final ClassLoadingStrategy ADP = new ClassLoadingStrategy(Arrays.asList(Source.APPLICATION, Source.DEPENDENCIES, Source.APPLICATION));`

According javadoc and variable name, last enum value should be PLUGIN, not APPLICATION.

**Comment by decebals** [comment]
@srosenthal13 Good catch. Thanks!

**Comment by srosenthal13** [comment]
You're welcome.
