### ISSUE TITLE
can we expose `ClassLoadingStrategy` to plugin manager layer?

### ISSUE THREAD

**Issue by chingjustwe** [pf4j/pf4j#392]
Came from older version of PF4J(3.2.0), and **VERY GLAD** to see there is a `ClassLoadingStrategy` to customize the class loading strategy now!
Recently we encounter a plugin cast problem. Our plugin class not only extended [org.pf4j.Plugin](https://github.com/pf4j/pf4j/blob/e7e15c18b86549a13e7b4b08f9cb57768f881423/pf4j/src/main/java/org/pf4j/Plugin.java), but also implemented another **customized interface**. 
On **Plugin-Management** project, after we loaded the plugin class through [JarPluginLoader](https://github.com/pf4j/pf4j/blob/e7e15c18b86549a13e7b4b08f9cb57768f881423/pf4j/src/main/java/org/pf4j/JarPluginLoader.java), we failed to cast the instance to **target interface** with `ClassCastException`.
After dive into the source code, we found that by default, the [PluginClassLoader](https://github.com/pf4j/pf4j/blob/e7e15c18b86549a13e7b4b08f9cb57768f881423/pf4j/src/main/java/org/pf4j/PluginClassLoader.java) loads 3rd party classes prior to it's parent(`AppClassloader`), so the class **customized interface** is loaded by `PluginClassLoader`, but the 3rd party **customized interface** is actually under the `lib` folder of **Plugin-Management** project's *Classpath*. The `Classloader` is different, cased the error. Below is the brief example:

#### Plugin side
~~~java
public class CustomizedPlugin extends Plugin implements CustomizedInterface {

    public CustomizedPlugin(PluginWrapper wrapper) {
        super(wrapper);
    }

    public static void main(String[] args) { }
    
    @Override
    public void CustomizedMethod() {
        System.out.println("foo");
    }
}
~~~

#### Plugin-Management project side
~~~java
public class Loader {
    public CustomizedInterface loadPlugin() {
        final PluginManager pluginManager = new JarPluginManager();

        pluginManager.loadPlugin(Paths.get("foo"));
        PluginWrapper pluginWrapper = pluginManager.getPlugin("bar");
        Plugin plugin = pluginWrapper.getPlugin();

        // throws ClassCastException, because class CustomizedInterface is loaded by PluginClassLoader 
        CustomizedInterface customizedPlugin = (CustomizedInterface) plugin;
        return customizedPlugin;
    }
}
~~~

After knowing the source code, the way to fix is pretty simple: create extended classes to use different `ClassLoadingStrategy`(`parentFirst` for elder version) like below:
~~~java
class CustomizedPluginManager extends JarPluginManager {
    @Override
    protected PluginLoader createPluginLoader() {
        return new CompoundPluginLoader()
                .add(new DevelopmentPluginLoader(this), this::isDevelopment)
                .add(new CustomizedJarPluginLoader(this), this::isNotDevelopment);
}

class CustomizedJarPluginLoader implements PluginLoader {
    @Override
    public ClassLoader loadPlugin(Path pluginPath, PluginDescriptor pluginDescriptor) {
        // set parentFirst as true
        PluginClassLoader pluginClassLoader = new PluginClassLoader(pluginManager, pluginDescriptor, getClass().getClassLoader(), true);
        pluginClassLoader.addFile(pluginPath.toFile());

        return pluginClassLoader;
    }
}
~~~

I know that on most cases, `PluginClassLoader` do should load classes prior to it's parent(incase loading different version of classes from classpath), but I think there still be some cases that we need to specify the loading strategy, that's why the `ClassLoadingStrategy` class being added right:-). So I think the better way to do it, is expose this param to PuginManager layer: add a construct param to indicate the ClassLoadingStrategy, something like:
~~~java
public class JarPluginManager extends DefaultPluginManager {

    public JarPluginManager() {
        super();
    }

    public JarPluginManager(Path pluginsRoot) {
        super(pluginsRoot);
    }
    // add ClassLoadingStrategy
    public JarPluginManager(Path pluginsRoot, ClassLoadingStrategy strategy) {
        super(pluginsRoot, strategy);
    }
}
~~~

I think it will be more user-friendly that, pf4j is flexible and support to specify class loading strategy according to any scenarios, rather than extend existing classes and do our customization after **deep dive into the source code**.
Please share your comments @decebals

**Comment by decebals** [comment]
@chingjustwe Thanks for your detailed explanation.
In the documentation, on page [Class loading](https://pf4j.org/doc/class-loading.html) it says:
> Use `parentFirst` parameter of `PluginClassLoader` to change the loading strategy.
> For example if I want to use a Parent First strategy in my application, all I must to achieve this is:
>
> ```java
>new DefaultPluginManager() {
>    
>    @Override
>    protected PluginClassLoader createPluginClassLoader(Path pluginPath, PluginDescriptor pluginDescriptor) {
>        return new PluginClassLoader(pluginManager, pluginDescriptor, getClass().getClassLoader(), true);
>    }
>
>};
```

Many customization can be done In PF4J overriding some factory methods (`createX`).
So, it's enough only to override `createPluginClassLoader`method to specify the `ClassLoadingStrategy`. I think that relative easy. Sure it's more simple to add this strategy as parameter in constructor but I want to avoid telescopic constructors.
What do you think?

**Comment by chingjustwe** [comment]
Oh make sense, it's an another simple way to customize the strategy, I'm OK with it;-), Thanks @decebals

**Comment by decebals** [comment]
@chingjustwe You're welcome!
