### ISSUE TITLE
dependencies conflict

### ISSUE THREAD

**Issue by yeahCaesar** [pf4j/pf4j#393]
I am using pf4j 3.2.0 to make a jar plugin, a fat jar, the jar has the pf4j denpendency.
The program which will load the plugin also has has the pf4j dependency.
When I call the plugin.start,  there is an exception,  and .. how to fix this?
![image](https://user-images.githubusercontent.com/19277364/90622819-3ef52f80-e248-11ea-8077-89c753486a4e.png)

**Comment by decebals** [comment]
Depends what build tool you are using (Maven, Gradle). My advice is to take a look on demo (see the structure of project, the pom files - how the PF4J dependencies are declared, dependency's scope).

**Comment by yeahCaesar** [comment]
I want to know if the pluginClassLoader is used to load all the plugin dependencies and to make the plugin run  without conflict to the main program.If so, is there anyone consider about that sometimes , the dependencies could be loaded by different classLoader , just like dom4j , it uses Class.forName to load some classes.

**Comment by decebals** [comment]
I don't understand very clear your question and what you try to achieve.
Each plugin + dependencies are loaded by a different `PluginClassLoader`. You can choose a different `ClassLoaderStrategy` for your application. You can choose for example the built-in `ClassLoaderStrategy.PDA` (probably your case). In the end you can use a complete custom `ClassLoader` instead of `PluginClassLoader`.

**Comment by yeahCaesar** [comment]
OK,  let me make it clearer. pf4j uses a pluginClassLoader to load the plugin and the dependencies of the plugin, right? When i load the plugin to run which includes a dom4j dependency, the program throws an Exception caused by class conflict, I notice the dom4j is imported by the main program too. I checked the source code of dom4j and found that it uses Class.forName to load some classes , and the classLoader to the Class.forName method , is not plugin class loader.So it can't be executed and throws exception

**Comment by decebals** [comment]
@yeahCaesar Do we have a resolution for this issue?

**Comment by decebals** [comment]
Close it due to lack of response. You can reopen it with a new comment.
