### ISSUE TITLE
ClassLoadingStrategy builder

### ISSUE THREAD

**Issue by hank-cp** [pf4j/pf4j#395]
I suggest ClassLoadingStrategy provides a builder that allow user to combine class loading strategy freely.

For example, I don't want my plugin loads resource from its dependency with same name.

Now ClassLoadingStrategy's constructor is private, I think it's not hard to add a builder right?

**Comment by decebals** [comment]
According my [comment](https://github.com/pf4j/pf4j/pull/385#discussion_r456367811), all possible combinations are already present in `ClassLoadingStrategy`. From this reason `ClassLoadingStrategy`'s constructor is private. Am I missing something?

**Comment by hank-cp** [comment]
For example, I don't want my plugin loads resource from its dependency with same resource name, So I want my `ClassLoadingStrategy`being `PA` (plugin->application). Propose code looks like:
```java
    new PluginClassLoader(pluginManager, pluginDescriptor, ClassLoadingStrategy.of(List.of(
        Source.PLUGIN, Source.APPLICATION)) // no Source.DEPENDENCIES

```
