### ISSUE TITLE
quickstart tutorial from scratch

### ISSUE THREAD

**Issue by paolodiprima** [pf4j/pf4j#399]
Hello,
 I'm trying to use this framework for a university project.  Unfortunately I'm not a pro of Java and 
 I'm just learning Maven.
 
 I'm successfully used the framework starting from the quickstart project and doing some refactoring.
 But I got difficulties to create my own start project from scratch.
  The idea is to create same simple structure of "quickstart" but by myself, creating module structure 
  with Eclipse Maven and fill the different pom files.
  
  In there any tutorial, guide, that shows how to make pom files (parent,  app module,  plugins module) etc..

  Or do someone have some suggestion, I have tried to copy those of the "quickstart" project but I did not success.

thanks,
Paolo

 today I'm not able even to resole the maven compiler plugin :
 
 `[INFO] plugins_win10 Parent 0.0.1-SNAPSHOT ................ SUCCESS [  2.119 s]
[INFO] app_name 0.0.1-SNAPSHOT ............................ FAILURE [  0.809 s]
[INFO] plugins 1.0-SNAPSHOT ............................... SKIPPED
[INFO] plugin1Name 1.0-SNAPSHOT ........................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.138 s
[INFO] Finished at: 2020-10-03T11:59:54+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project app: Fatal error compiling: invalid flag: --release -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.`

**Comment by decebals** [comment]
Can you share your project? (GitHub or other public repositories)

**Comment by paolodiprima** [comment]
thanks for immediate reply.. here it is 
https://github.com/paolodiprima/mydemoPF4J.git

**Comment by decebals** [comment]
The issue is too old. Reopen it with more context if you still need help.
