### ISSUE TITLE
Current state of the JPMS support

### ISSUE THREAD

**Issue by mkpaz** [pf4j/pf4j#400]
I've found some issues that such support was implemented some time ago:

https://github.com/pf4j/pf4j/pull/300
https://github.com/pf4j/pf4j/pull/305

However, there is no `module-info.java` in the current master branch and JAR of the latest version of `pf4j` from Maven Central is just an old plain JAR, it's not multi-release how it stated in `pom.xml`. Was JPMS support removed from `pf4j` completely? Do you have any plans do return it to any near future?

**Comment by decebals** [comment]
Solved by 6e956335182bacfc478159b5f2a6f6697d266d9e.

**Comment by decebals** [comment]
@mkpaz 
Can you try the latest SNAPSHOT version (3.5.0), please?

**Comment by mkpaz** [comment]
I will, thanks.
