### ISSUE TITLE
Java 9 - module-info problems

### ISSUE THREAD

**Issue by rreich** [pf4j/pf4j#405]
Since using Java 9 with module-info, I cannot build the project anymore.

I can install the current master with maven on command-line, but I cannot build the project in Intellij Idea due to unknown module-info files.

When I change the line https://github.com/pf4j/pf4j/blob/master/pom.xml#L46 from version 8 to 9 (which would be the correct value IMHO), I can build in Idea, but not on the command-line anymore.

```
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project pf4j: Compilation failure: Compilation failure:
...module-info.java:[30,27] module not found: org.objectweb.asm
...module-info.java:[36,19] module not found: slf4j.api
...module-info.java:[41,18] module not found: java.semver
```
The unit-tests have strange NoClassDefFound errors and duplicate resource-loading problems.

I think something regarding the Java Modules is not set-up correctly.
Or maybe I am doing something wrong?

**Comment by decebals** [comment]
I don't know what to say. I think that we need do (double) check if the modules defined in `module-info.java` exist or not.
For this, we need to go on each dependency library's site and to do this check.

**Comment by decebals** [comment]
@drinkitup777 

Can you create a PR please? Try to search if they are (stable) versions for `asm` and `slf4j` libraries that come with support for modularity. If you didn't find something try please your variant proposed by you. Please do some tests using demo application or your application to be sure that the solution proposed in PR resolves entirely the problem. Thanks!

**Comment by RationalityFrontline** [comment]
I've created a [PR](https://github.com/pf4j/pf4j/pull/423) that should solve this issue (already tested on local).

In addition, for people using kotlin, since [kapt doesn't support multi-release jar](https://youtrack.jetbrains.com/issue/KT-32202), it needs some additional hack (gradle kotlin dsl):
```kotlin
import org.gradle.kotlin.dsl.support.zipTo

plugins {
    kotlin("jvm") version "1.4.20"
    kotlin("kapt") version "1.4.20"
    application
    id("org.javamodularity.moduleplugin") version "1.7.0"
}

repositories {
    mavenLocal()
    mavenCentral()
}

configurations.create("mrjar9")

dependencies {
    val pf4jVersion = "3.7.0"
    implementation("org.slf4j:slf4j-simple:1.7.30")
    implementation("org.pf4j:pf4j:$pf4jVersion")
    kapt("org.pf4j:pf4j:$pf4jVersion")
    add("mrjar9", "org.pf4j:pf4j:$pf4jVersion")
}

application {
    mainClass.set("org.rationalityfrontline.demo.pf4j.AppKt")
    mainModule.set("demo.pf4j")
}

sourceSets.main {
    java.srcDir("src/main/kotlin")
}

modularity.disableEffectiveArgumentsAdjustment()

kapt{
    javacOptions {
        option("--module-path", tasks.compileJava.get().classpath.asPath)
    }
}

tasks.register("moveModuleInfoInMRJARs") {
    configurations["mrjar9"].files.forEach { mrjar9Jar ->
        val tree = zipTree(mrjar9Jar)
        val moduleInfoFile = tree.matching { include("module-info.class") }
        val v9ModuleInfoFile = tree.matching { include("META-INF/versions/9/module-info.class") }
        if (moduleInfoFile.isEmpty && !v9ModuleInfoFile.isEmpty) {
            val unzipDir = file("$buildDir/tmp/mrjar9")
            delete(unzipDir)
            mkdir(unzipDir)
            copy {
                from(tree, v9ModuleInfoFile.singleFile)
                into(unzipDir)
            }
            zipTo(mrjar9Jar, unzipDir)
            println("Fixed $mrjar9Jar")
        }
    }
}

// See https://github.com/java9-modularity/gradle-modules-plugin/issues/162 and https://youtrack.jetbrains.com/issue/KT-32202
afterEvaluate {
    tasks["kaptKotlin"].dependsOn("moveModuleInfoInMRJARs")
}
```
