### ISSUE TITLE
Disable logging?

### ISSUE THREAD

**Issue by rjzak** [pf4j/pf4j#407]
How can I disable the logging output? I'm trying to create a console application, and the extra output from PF4J is distracting and annoying. I'm not familiar with the many logging frameworks, or where to put the needed .xml or .properties file in my Jar.

`Nov 04, 2020 1:14:55 PM org.pf4j.DefaultPluginStatusProvider <init>`
`INFO: Enabled plugins: [my-plugin1]`
`Nov 04, 2020 1:14:55 PM org.pf4j.DefaultPluginStatusProvider <init>`
`INFO: Disabled plugins: []`
`Nov 04, 2020 1:14:55 PM org.pf4j.DefaultPluginManager initialize`
`INFO: PF4J version 0.0.0 in 'deployment' mode`
`Nov 04, 2020 1:14:55 PM org.pf4j.AbstractPluginManager resolvePlugins`
`INFO: Plugin 'my-plugin1@1.0' resolved`

**Comment by decebals** [comment]
I don't know what logging framework/library are you use in your application.

**Comment by rjzak** [comment]
None, yet logging information appears showing `org.pf4j` at start.

**Comment by decebals** [comment]
Any resolution here? Did you solved the problem?

**Comment by decebals** [comment]
Close it  due to lack of response. You can reopen it with a new comment.
