### ISSUE TITLE
A question about the default ClassLoadingStrategy of PluginClassLoader.

### ISSUE THREAD

**Issue by LamGC** [pf4j/pf4j#410]
I want to ask why the default value of `ClassLoadingStrategy` in `PluginClassLoader` is **PDA**. I found that the same fully qualified class name will be loaded by `SystemClassLoader` and `PluginClassLoader`, resulting in two class objects (This destroys the delegation model in ClassLoader).

This will affect `Class.isAssignableFrom` , Because the `Plugin` used by the inheritance is not the same object as the `Plugin` in the PluginFactory (I haven't compared the two objects specifically. This is my guess).

**Comment by decebals** [comment]
You can use multiple class loading strategies when you work with a `ClassLoader`. 
The best knows are:
- `Parent first` (default in Java - first delegate the class load operation to the parent class loader)
- `Child first`

The child first strategy is used in some application servers (for example Tomcat). In Tomcat for example, `WebappClassLoader` (somehow a `PluginClassLoader` from PF4J) loader does not follow the model delegated by the parent loader of Java.

> I found that the same fully qualified class name will be loaded by SystemClassLoader and PluginClassLoader, resulting in two class objects (This destroys the delegation model in ClassLoader).

This behavior is normal if you have the same library (or class) in both application's classpath and plugin's classpath. But they are two different classes for JVM.
They are some advantages (from isolation point of view) if you use a child first strategy. The good part is that PF4J is very configurable and you can choose what suits you.

**Comment by LamGC** [comment]
@decebals I see. Thank you for your answer! :D
