### ISSUE TITLE
please update the version of slf4j

### ISSUE THREAD

**Issue by l1046j** [pf4j/pf4j#411]
org.slf4j.ext.EventData in the slf4j-ext module in QOS.CH SLF4J before 1.8.0-beta2 allows remote attackers to bypass intended access restrictions via crafted data.

**Comment by decebals** [comment]
Can you submit a PR please?

**Comment by decebals** [comment]
We have https://github.com/pf4j/pf4j/pull/412 for this but for the moment I closed because it is debatable if it is OK to add a beta version as a dependency in the project
