### ISSUE TITLE
Excuse me, how to get the extension of multiple instances?

### ISSUE THREAD

**Issue by 799452017** [pf4j/pf4j#413]
```java
DemoImpl implA = pluginManager.getExtension(DemoImpl.class,"xxxx").get(0);
implA.setMessage("hello");

DemoImpl impB = pluginManager.getExtension(DemoImpl.class,"xxxx").get(0);
String message = implB.getMessage(); // I want an unassigned message
```

**Comment by decebals** [comment]
It's not clear for me what to try to achieve. 
I feel that https://github.com/pf4j/pf4j/issues/293 can help you. It's about what implementation are you using in your project for `ExtensionFactory`.
Please add more details.
If I understand correctly the last line from the code supplied by you in the issue's description returns `hello` and you want `null`. Is it correct what I say?

**Comment by 799452017** [comment]
> It's not clear for me what to try to achieve.
> I feel that #293 can help you. It's about what implementation are you using in your project for `ExtensionFactory`.
> Please add more details.
> If I understand correctly the last line from the code supplied by you in the issue's description returns `hello` and you want `null`. Is it correct what I say?

Yes, I need to get new instances every time. I want message to be null.

**Comment by decebals** [comment]
In this case (you use `pf4j-spring`) please take a look at `SpringExtensionFactory`. 
Post an issue in `pf4j-srping` project, with a link to this issue, because there are people with Spring knowledge who can help you.
