### ISSUE TITLE
adding the programatic plugin generation interface to a different dependency

### ISSUE THREAD

**Issue by asafbennatan** [pf4j/pf4j#414]
Hi,
i think it would be beneficial if the classes used for pf4j's testing are published in a different package so framework extenders could also check their work in the same manner.

**Comment by decebals** [comment]
Yes, you are right. I tried to create a `pf4j-test` repository and to move some classes from pf4j/test (like `PluginZip`, `PluginJar`, ...) in the new repo but I encountered some problems. I don't remember exactly but I think that was a circular dependency or something similar.

**Comment by asafbennatan** [comment]
for my use case i only took:
DefaultClassDataProvider
PluginJar
ClassDataProvider

and used plugin jar class

**Comment by asafbennatan** [comment]
actuall i understand why becuase testClasses->pf4j->testClasses

**Comment by decebals** [comment]
> actually i understand why because pf4j-tests->pf4j->testClasses,
> i guess the correct way of solving that is to create three packages:

It's not clear for me if `three packages` means three repositories or three artifacts (Maven, Jar) or just three Java packages (group of classes).
Probably the simple solution is to move the important classes (the classes mentioned by you) from `src/test` to `src/main` (in a new `org.pf4j.test` package). The single drawback of this solution is that artifact (the jar file) will increase in size. In the end I don't know if it's a serious drawback.

**Comment by asafbennatan** [comment]
i mean jars(maven) , while moving the test classes into main is a possibility IMHO the main issue here is the leakage of test related classes into the library regardless of the size , so my suggestions will be to create the following maven projects:
1.pf4j-api containing production classes required by testing as well as main library
2.pf4j-tests a library which will be used by testing only ,contains tests classes- this will depend on pf4j-api
3.pf4j (current library) uses pf4j-tests in test scope and pf4j-api in compile(default) scope - this contains all production classes which are not required by pf4j-tests

**Comment by decebals** [comment]
To be honest I don't like the idea to split `pf4j` in `pf4j-api` and `pf4j`. It's very difficult to decide what to contain `pf4j-api`.
I prefer to create only a new `pf4j-test` Maven module in the current repository, and to move some classes from `src/test` (`pf4j` module) in the new `pf4j-test` module. Of course, if it's possible and enough.

**Comment by asafbennatan** [comment]
Yes it should be enough

**Comment by decebals** [comment]
In the end I found a simple and not intrusive (no need to create a new Module module or something similar).
The solution proposed by me is based on https://maven.apache.org/plugins/maven-jar-plugin/examples/create-test-jar.html.
In the end a new jar will be created and deployed on Maven Central Repository. I will do a little refactoring in `pf4j/test/java`, and I will move all the classes/files that will be part of the test jar file in a new package (probably `org.pf4j.test`).
I tested very quickly with a test application (new external project) and the result is very good.
I like to keep things simple as possible and from this reason sometimes I spent more time to find a good solution (I try to find the best one).

I will come very soon with a PR to present you my solution.

@asafbennatan Thank you for your patience!

**Comment by asafbennatan** [comment]
Thanks !

**Comment by decebals** [comment]
Created https://github.com/pf4j/pf4j/pull/415.

**Comment by decebals** [comment]
It's available in version `3.6.0` (released today).
