### ISSUE TITLE
unknow plugin id

### ISSUE THREAD

**Issue by wlyjj412414** [pf4j/pf4j#421]
When JMeter is used for pressure measurement, the number of concurrent tests is 50, and the unknown plugin ID is abnormal

**Comment by decebals** [comment]
Can you add more details about the context of your application. I don't understand th epart with JMeter.

**Comment by wlyjj412414** [comment]
private static PluginManager pluginManager=null;

if(pluginManager == null){
    pluginManager = new JarPluginManager();
}
pluginManager.loadPlugin(Paths.get(pluginPath));
pluginManager.startPlugin(pluginId);
List<Indexer> indexerList = pluginManager.getExtensions(Indexer.class);
if(indexerList !=null && indexerList.size()>0){
    return indexerList.get(0);
}

pluginManager.stopPlugin(pluginId);
pluginManager.unloadPlugin(pluginId);



A single request is normal. If there are too many concurrent requests, an unknown plugin ID exception will be reported

**Comment by decebals** [comment]
According documentation ([Thread safety](https://pf4j.org/doc/thread-safety.html) section), PF4J is not thread safety. It’s your responsibility to deal with concurrency (maybe create a custom `PluginManager` and sync some methods).
