### ISSUE TITLE
Run plugin from memory instead of file

### ISSUE THREAD

**Issue by bytecod3r** [pf4j/pf4j#422]
I have special requirement in my client/server application, which the server side hosts the plugin files and load them and the client will connect to server via socket.

But I want the plugins on the server side, to contain another mini plugin for the client side, which once the server loads the plugin, the mini plugin to be transfered to the client and load in there too.

My question is, is there anyway to load a plugin in the client side from a serialized data? or anything else similar that is in memory and is not a .jar/zip file.

Appreciate any hints

**Comment by decebals** [comment]
Personal, it's the first time I've heard anything like this. Why you don't use something similar with `pf4-update`? I understand that you download the plugins, for each client, from a server. You can download all these plugins in a tmp directory using https, websocket, or anything else transport protocol and set this directory as plugins root.

**Comment by Sailsman63** [comment]
I can think of two possible scenarios, here.

1. You can't have write access to the client filesystem at runtime, but can run a File-server on the server end.
    - In this case, you need a `PluginLoader` that can take a URL to the plugin on the fileserver. Shouldn't be too hard, as `PluginClassLoader` already extends `URLClassLoader`.
2. If you can't even serve files from the server end, you might be able to make use of the methods in `ClassLoader` that define a class based on a `byte[]`.  The byte array needs to be an exact match to a valid classfile. This would probably only work well for very small plugins, such as a single method or so, with no dependencies.

**Comment by decebals** [comment]
any resolution here? is this topic still of interest to you?
