### ISSUE TITLE
How to firstly install the interface jar and later install the plugin jar that implements the interface

### ISSUE THREAD

**Issue by jeven2016** [pf4j/pf4j#424]
Hi  team,
   In our web project, we will firstly upload the interface jar by the system operator at runtime from web GUI, and some team members may upload the plugins after they complete the test.  So the question is how to dynamiclly load the interface jar with PF4j ?

Thanks

**Comment by decebals** [comment]
Sorry but I don't understand what you try to achieve. Can you add more details please?

**Comment by jeven2016** [comment]
Say we have an api.jar and two plugins,  in this case the App project has to add the api.jar as an dependecy in build.gradle.  
But this isn't what we need in our project , we  prefer to dynamiclly load the api.jar at runtime for App instead of adding it as dependency in build.gradle.  And then we can develop the corresponding gui to upload/install/uninstall the api.jar .

**Comment by decebals** [comment]
Did you find a solution to your problem? Is it still relevant to you?

**Comment by decebals** [comment]
Close it due to lack of response. You can reopen it with a new comment.
