### ISSUE TITLE
PF4J for dynamic plugin (feature market place)

### ISSUE THREAD

**Issue by mathewsreji** [pf4j/pf4j#431]
Hello community!

I was doing some research around framework which can help to implement a marketplace kind of experience where users can select or purchase features and once done, it should be immediately available in the main application. Am looking at "feature" as a plugin

My requirement is
- Addition of the new plugin **shouldn't call for restart of main application** . It should be able to pick up the jar (from a folder) on the fly. ( and maybe perform a registration of the new plugin/extension into a registry from where we can lookup and use)
- Main application is a springboot and the plugins should be able to register their extensions as spring beans once PluginManager has loaded them.

From my initial analysis of javadocs, the .loadPlugin(Path) method in PluginManager class should help load new plugins dynamically on demand. But just wanna hear from you guys if PF4J has any known limitation to implementing my requirement?

Cheers
Reji

**Comment by decebals** [comment]
> * Addition of the new plugin **shouldn't call for restart of main application** . It should be able to pick up the jar (from a folder) on the fly. ( and maybe perform a registration of the new plugin/extension into a registry from where we can lookup and use)

I think that this aspect is satisfied by PF4J.

> * Main application is a springboot and the plugins should be able to register their extensions as spring beans once PluginManager has loaded them.

You have `pf4-spring` project for this or you can use other libraries available on GitHub, that integrates PF4J with Spring(Boot).
