### ISSUE TITLE
Problem using pf4j together with java9 module system

### ISSUE THREAD

**Issue by RationalityFrontline** [pf4j/pf4j#437]
When using pf4j (v3.6.0) together with java9 module system, I encountered some problems:
1. Can't use slf4j of version above 1.7.25.
2. Must declare an additional dependency of asm besides pf4j itself.

I've created a demo project that could reproduce this issue: [pf4j-jpms-demo](https://github.com/RationalityFrontline/pf4j-jpms-demo/tree/master).
(To reproduce the issue, you need to edit the app/build.gradle.kts file)

**Comment by decebals** [comment]
The problem is only partially solved. For more details see https://github.com/pf4j/pf4j/pull/438#issuecomment-813001646.

**Comment by RationalityFrontline** [comment]
> The problem is only partially solved. For more details see [#438 (comment)](https://github.com/pf4j/pf4j/pull/438#issuecomment-813001646).

I think this issue is already solved, the build process of pf4j can run with no error, and the generated multi-release jar artifact can be used in modular java project with no problem (you can test this with [pf4j-jpms-demo](https://github.com/RationalityFrontline/pf4j-jpms-demo)). I don't see any more problems between pf4j and  java module system.

The "module not found: java.semver" error message mentioned in #405 will only show up when you change the following maven compiler version from 8 to 9:
https://github.com/pf4j/pf4j/blob/575abd034fd3bfbeff60f1ddbd9deb88c6b741e6/pom.xml#L46
But there is no reason to change the maven compiler version since pf4j is already configured as a multi-release project: 
https://github.com/pf4j/pf4j/blob/575abd034fd3bfbeff60f1ddbd9deb88c6b741e6/pf4j/pom.xml#L51

**Comment by decebals** [comment]
@RationalityFrontline 
Good news. Thanks for your explanation and your implication!
In this case, can we close this issue?

**Comment by RationalityFrontline** [comment]
Yes, closing now.

**Comment by decebals** [comment]
@RationalityFrontline 
What do you think about https://github.com/pf4j/pf4j/issues/441?
