### ISSUE TITLE
cannot compile - module-info,java is present but release is set to 8

### ISSUE THREAD

**Issue by asafbennatan** [pf4j/pf4j#441]
java: modules are not supported in -source 8
  (use -source 9 or higher to enable modules)

we should remove the module-info file or set maven.compiler.release to >=9 (preferably 11)

**Comment by decebals** [comment]
I think that we have something which should solve this problem.  It's about https://github.com/pf4j/pf4j/blob/master/pf4j/pom.xml#L30.
You can take a look on https://github.com/pf4j/pf4j/pull/300 to see when `module-info.java` was introduced.

**Comment by RationalityFrontline** [comment]
@asafbennatan Java module is already supported, run command "mvn clean install" and the project can be built successfully (with jdk version >= 9). The generated jar artifact will contain a module-info.class file (under META-INF/versions/9/), and can be used in modular java projects. The PF4J project is configured as a [multi-release](https://www.baeldung.com/java-multi-release-jar) project. What do you mean by "cannot compile" ? How to reproduce the problem that you've encountered?

**Comment by decebals** [comment]
@RationalityFrontline 
I think that @asafbennatan talks about build PF4J (with `mvn clean package`) using Java 8.
```
 ~/work/pf4j [master|● 1✚ 1…15⚑ 11] 
20:58 $ java -version
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
```
mvn clean package
ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project pf4j: Fatal error compiling: invalid flag: --release -> [Help 1]
[ERROR] 
```

In theory, the minimum Java version required by PF4J (build and runtime) is 8.

**Comment by RationalityFrontline** [comment]
@decebals I agree with your assumption, java 8 can't handle the module-info.java file. To prevent issues like this, I think we need to update the document related with building PF4J. The current minimum jdk version required to build PF4J should be 9, but the runtime java version can be 8 since the artifact is a multi-release jar.

**Comment by asafbennatan** [comment]
> @RationalityFrontline
> I think that @asafbennatan talks about build PF4J (with `mvn clean package`) using Java 8.
> 
> ```
>  ~/work/pf4j [master|● 1✚ 1…15⚑ 11] 
> 20:58 $ java -version
> java version "1.8.0_201"
> Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
> Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
> ```
> 
> ```
> mvn clean package
> ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project pf4j: Fatal error compiling: invalid flag: --release -> [Help 1]
> [ERROR] 
> ```
> 
> In theory, the minimum Java version required by PF4J (build and runtime) is 8.

yes - this is what i meant ,

**Comment by decebals** [comment]
I updated home page and the build page. The minimum required Java version to build PF4J is 9 but as runtime the minimum required Java version is 8.
