### ISSUE TITLE
how to read resource file in plug-in when plugin loads

### ISSUE THREAD

**Issue by sunyuyangg555** [pf4j/pf4j#442]
Hi there, I want read resource/foo.xml in plug-in extension. 
`
IOUtils.resourceToString(/foo.xml);
`
Unfortunately I got a no file error. So how do I it?

**Comment by decebals** [comment]
In few words, by default each plugin is loaded by a separated `ClassLoader` ([PluginClassLoader](https://github.com/pf4j/pf4j/blob/master/pf4j/src/main/java/org/pf4j/PluginClassLoader.java)). You need to use ClassLoader's get Resource to load/read a resource.

**Comment by sunyuyangg555** [comment]
Thank you very much. I use
`
pluginWrapper.getPluginClassLoader()
`
do it.
