### ISSUE TITLE
Class not found exception even if class present in plugin's lib folder

### ISSUE THREAD

**Issue by Nigam-Patel-Main** [pf4j/pf4j#447]
Sir, I have one plugin contain jars and classes. Jars is located in lib folder of plugin. When I start plugin i got class not found exception.Can you give me solution for loading jar which is located in plugin lib folder

**Comment by decebals** [comment]
Each plugin must be assembled as a JAR or ZIP. According your description (`lib` folder that contains jars - probably dependencies) you need to go with the ZIP format for your plugins.
See doc for more info:
- https://pf4j.org/doc/packaging.html
- https://pf4j.org/doc/custom-manager.html

**Comment by Nigam-Patel-Main** [comment]
Thanks for reply. But sir is anything possible with jar packaging. As mentioned in doc of PF4J that jar packaging is standard.

**Comment by decebals** [comment]
As I mentioned before (previous comment), out of the box PF4J has support for two types of plugin packaging:
- JAR
- ZIP

The JAR packaging contains only classes and resources file (it's a kind of uber or fat standard JAR). All JAR the files (one file for each plugin) are located in `plugins` folder. 
If you need a custom mechanism for plugin packaging you need a new implementation for `PluginRepositrory` and `PluginLoader`. For more information see [JarPluginManager](https://github.com/pf4j/pf4j/blob/master/pf4j/src/main/java/org/pf4j/JarPluginManager.java).
