### ISSUE TITLE
Switch from Travis-ci.org

### ISSUE THREAD

**Issue by wolframhaussig** [pf4j/pf4j#456]
As travis-ci.org will shutdown tomorrow we would consider updating the build pipeline to either travis-ci.com or github actions:
![image](https://user-images.githubusercontent.com/13997737/121920440-569e2700-cd38-11eb-849b-0352b3d9eb83.png)

Personally,  I would switch to the github actions as this way, everything would be within Github.

I can help with the github actions migration if you want but there are some things I am not allowed in the Repo (like setting CI/CD secrets).

**Comment by decebals** [comment]
I don't know what means:

```
Your account needs to be part of the beta to start migrating public repositories here. Please, sign up for the beta below.
```

![image](https://user-images.githubusercontent.com/1248311/121955870-1a36ef00-cd69-11eb-9b6d-8e6eef001474.png)

**Comment by wolframhaussig** [comment]
I don't know either as I have not used travis-ci in the past.

Any reasons not to migrate to GitHub action

**Comment by decebals** [comment]
@wolframhaussig 
> Any reasons not to migrate to GitHub action

Good question. I'm not familiar with GitHub actions so from this reason I don't know what to say here (I prefer to invest my time to improve the code). But I'm not saying no to this proposal.

**Comment by decebals** [comment]
Problem solved. We have been using GitHub actions for some time.
