### ISSUE TITLE
Class loading from fatJar

### ISSUE THREAD

**Issue by mathewsreji** [pf4j/pf4j#462]
I am a new user of pf4j.

While packaging the plugin as a fat jar (to include all the pom.xml dependencies), does the app load all those classes which are packaged in plugin jar or just the extension?

I don't see any information about loading such classes on this document page - https://pf4j.org/doc/class-loading.html . Also, I was trying to figure out the [logic here](https://github.com/pf4j/pf4j/blob/master/pf4j/src/main/java/org/pf4j/PluginClassLoader.java#L98-L146) to see if other classes in a fat jar are also considered. On debugging, I don't see the PluginClassLoader touching any of those additional classes in fat jar.

Any clues/pointors would be helpful for me :)

Reji

**Comment by mathewsreji** [comment]
Just to make the question more clear

![image](https://user-images.githubusercontent.com/5595781/124664057-e5eeb400-de78-11eb-84fc-22aa884494b5.png)

**Comment by mathewsreji** [comment]
I noticed that the plugin starts well, however, on the execution time, it cannot find classes of external dependencies like 3rd party sdks and jdbc drivers. 

If no, does it mean, we need to implement our own classloaders to load additional classes in the fatJar?

**Comment by mathewsreji** [comment]
Similar to this issue https://github.com/pf4j/pf4j/issues/361

**Comment by decebals** [comment]
Can you do what I described in https://github.com/pf4j/pf4j/issues/461#issuecomment-874868504?

**Comment by decebals** [comment]
@mathewsreji Any resolution on this issue? Did you mange to solve it?

**Comment by decebals** [comment]
Close it due to lack of response. You can reopen it with a new comment.
