### ISSUE TITLE
Custom Annotation processor that generate extension

### ISSUE THREAD

**Issue by centoria** [pf4j/pf4j#463]
Hi we use pf4j in our project.
From custom class with custom annotation (retention source) we generate classes annoted with @Extension. Our custom annoation do its job, but the second round with pf4j dont work , we have our generated classes compiled but the extension.idx is empty and the extension are not loaded.

Here the configuration of pom (maven-compiler-plugin)

````
<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.1</version>
				<configuration>
					<release>${jdk.version}</release>
					<annotationProcessorPaths>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
							<version>1.18.8</version>
						</path>
						<path>
							<groupId>org.pf4j</groupId>
							<artifactId>pf4j</artifactId>
							<version>3.5.0</version>
						</path>
						<path>
							<groupId>centoria.nerp</groupId>
							<artifactId>core-tools</artifactId>
							<version>0.0.1-SNAPSHOT</version>
						</path>
						<path>
							<groupId>centoria.nerp</groupId>
							<artifactId>core-model</artifactId>
							<version>0.0.1-SNAPSHOT</version>
						</path>
						<path>
							<groupId>centoria.nerp</groupId>
							<artifactId>core-common</artifactId>
							<version>0.0.1-SNAPSHOT</version>
						</path>
					</annotationProcessorPaths>
				</configuration>
			</plugin>
````

core-tools contain our custom annotations.

Its works ans generate for exmple  :

```

@Extension
public class CategoryAppAdd extends AppDtoExtension { 

	public CategoryAppAdd() {
...

```

Did someone use annoation to generate pf4j extension and have a solution ??

Thanks and excuse my english

**Comment by decebals** [comment]
I don't know why you declare the annotation processor for pf4j. In [demo](https://github.com/pf4j/pf4j/tree/master/demo) project this operation is out of the box.
An interesting idea that avoid annotation processor is described [here](https://www.jadaptive.com/extending-pf4j-to-scan-for-extensions/).
