### ISSUE TITLE
ClassNotFound

### ISSUE THREAD

**Issue by AdrienRoux** [pf4j/pf4j#467]
Hi decebals and community, 

I'm a bit new with pf4j, I tried starting a project from the quickstart maven archetype you provide on the website but after adding my files and modifying the plugins examples, it seems that they cannot be found on the class path and so they don't seem to be detected by the code after that...
I have checked for any typo and if the modules where in the project structure but I can't figure it out

Here is the log following the start of the application
![image](https://user-images.githubusercontent.com/35739752/129938539-7dd6adbe-cbee-4bb7-9977-05c7bee52737.png)

Here is my project structure (basically the same as the quickstart archetype)
![image](https://user-images.githubusercontent.com/35739752/129938766-7ca6bbb5-3be4-42e1-83c6-9984f562c93e.png)

Any idea on how I could resolve this ?

**Comment by decebals** [comment]
Please check that you are running in development mode? (run application with `-Dpf4j.mode=dev`)

https://pf4j.org/doc/development-mode.html

**Comment by decebals** [comment]
If you continue to have problems, please attach the log file or create a guickstart that replicates the problem (will be awesome if it's available on Git - GitHub, ... ).

**Comment by AdrienRoux** [comment]
Oh thank you so much !! It was the development mode !
