### ISSUE TITLE
The observer pattern and the publisher/subscriber pattern

### ISSUE THREAD

**Issue by pierre03** [pf4j/pf4j#473]
Hi, 
Can you tell me if you have the observer pattern or publisher/subscriber pattern in the framework, please?
How and when the core system can call the plugin?  
Thanks.

**Comment by decebals** [comment]
I don't understand what you try to achieve. 
In my projects where I use pf4j, I don't use a such approach (related to plugins) but I am sure that is possible. They are some issues (closed)  that describe in details a communication mechanism between core and plugins.
Please describe what you try to achieve, maybe other pf4j users already using what you want.

**Comment by pierre03** [comment]
Thank you for your quick reply.
I want to create a system in plugin architecture by two teams(core team,  plugin team), the main fonctions will be defined directly in core system, and some special fonctions will be developped by another team by plugin.
 
But it's not clear to use your framwork, we should define in the core system in advance to call the plugin fonctions? Or the plugin fonction will be trigged by some events?

The sample code is too simple, with it, i can just imagine that the framwork can be used to create a workflow application to process a command step by step by calling the same fonction, but can you tell me how to use the framwork for my situation(core+plugin), please?

Thank you.

**Comment by decebals** [comment]
As I said:
> They are some issues (closed) that describe in details a communication mechanism between core and plugins

- https://github.com/pf4j/pf4j/issues/187
- https://github.com/pf4j/pf4j/issues/181

and probably other issues.

A possible approach (very used) is to create a `BasePlugin` in your application, that is the root of any plugin developed by your plugins team. In this `BasePlugin` you can inject from application core an `EventBus` so, you can listen or publish events in application from plugin.
A plugin is only a container for some extensions or extensions points. When you say function probably is an extension (an implementation of extension point). For example function save in an image processing application. You can define `Save` extension point. By default you can save an image in few formats (let's say GIF and PNG), they are implemented as default extensions. Other people can write plugins for your application, allowing to save an image in other formats (let's say JPEG).

```java
public interface Save extends ExtensionPoint {

    void save(Image image)

}
```

```java
@Extension
public class SaveAsPNG implements Save {
    
    @Overide
    void save(Image image) {
        // save image in PNG format
    }

}
```

For more details see [documentation](https://pf4j.org/doc/extensions.html).

I am sure that PF4J can solve all needs you are :). In any modular application, the first step is relatedabout planning the things you want to expose for extensions (the `extension points`).

**Comment by decebals** [comment]
@pierre03 Did you find a solution? Can we close this issue or you still need help?

**Comment by decebals** [comment]
Close it due to lack of response. You can reopen it with a new comment.
