### ISSUE TITLE
Not working with `okta-jwt-verifier-java`

### ISSUE THREAD

**Issue by abcfy2** [pf4j/pf4j#474]
When I package a shadowJar contains `okta-jwt-verifier-java` as my extension, it will throws:

```
        at java.base/java.lang.Thread.run(Thread.java:866)
Caused by: java.lang.IllegalStateException: No `interface com.okta.jwt.AccessTokenVerifier$Builder` implementation found on the classpath. Have you remembered to include the okta-jwt-verifier-impl.jar in your runtime classpath?
        at com.okta.jwt.JwtVerifiers.lambda$loadService$1(JwtVerifiers.java:60)
        at <unknown class>.get(Unknown Source)
        at java.base/java.util.Optional.orElseThrow(Optional.java:408)
        at com.okta.jwt.JwtVerifiers.loadService(JwtVerifiers.java:60)
        at com.okta.jwt.JwtVerifiers.accessTokenVerifierBuilder(JwtVerifiers.java:51)
        at id.attestation.plugins.auth.FacebookAuthService.<init>(FacebookAuthService.java:22)
        at java.base/java.lang.J9VMInternals.newInstanceImpl(Native Method)
        at java.base/java.lang.Class.newInstance(Class.java:2288)
        at org.pf4j.DefaultExtensionFactory.create(DefaultExtensionFactory.java:38)
        ... 30 common frames omitted
```

I find okta-jwt-verifier-java  use `java.util.ServiceLoader` to load implement class: https://github.com/okta/okta-jwt-verifier-java/blob/master/api/src/main/java/com/okta/jwt/JwtVerifiers.java#L60

And also all services files already bundled in shadow jar file:

my-plugin-all.jar:

```
META-INF/
META-INF/MANIFEST.MF
...
META-INF/okta/
META-INF/okta/version.properties
com/
com/okta/
com/okta/jwt/
com/okta/jwt/impl/
com/okta/jwt/impl/jjwt/
com/okta/jwt/impl/jjwt/BaseVerifierBuilderSupport.class
com/okta/jwt/impl/jjwt/TokenVerifierSupport.class
com/okta/jwt/impl/jjwt/TokenVerifierSupport$OktaJwtHandler.class
com/okta/jwt/impl/jjwt/ClaimsValidator$CompositeClaimsValidator.class
com/okta/jwt/impl/jjwt/ClaimsValidator.class
com/okta/jwt/impl/jjwt/ClaimsValidator$ContainsAudienceClaimsValidator.class
com/okta/jwt/impl/jjwt/IssuerMatchingSigningKeyResolver.class
com/okta/jwt/impl/jjwt/models/
com/okta/jwt/impl/jjwt/models/JwkKeys.class
com/okta/jwt/impl/jjwt/models/JwkKey.class
com/okta/jwt/impl/jjwt/JjwtAccessTokenVerifierBuilder.class
com/okta/jwt/impl/jjwt/RemoteJwkSigningKeyResolver.class
com/okta/jwt/impl/jjwt/JjwtIdTokenVerifier.class
com/okta/jwt/impl/jjwt/JjwtAccessTokenVerifier.class
com/okta/jwt/impl/jjwt/JjwtIdTokenVerifierBuilder.class
com/okta/jwt/impl/http/
com/okta/jwt/impl/http/HttpClient.class
com/okta/jwt/impl/http/OktaCommonsHttpClient.class
com/okta/jwt/impl/DefaultJwt.class
...
META-INF/services/com.okta.jwt.AccessTokenVerifier$Builder
META-INF/services/com.okta.jwt.IdTokenVerifier$Builder
META-INF/services/com.okta.commons.http.RequestExecutorFactory
META-INF/services/io.jsonwebtoken.CompressionCodec
META-INF/services/io.jsonwebtoken.io.Serializer
META-INF/services/io.jsonwebtoken.io.Deserializer
META-INF/services/com.fasterxml.jackson.core.JsonFactory
META-INF/services/com.fasterxml.jackson.core.ObjectCodec
...
```

What's wrong with me? How do I resolve this issue ?

Thanks.

**Comment by decebals** [comment]
`ServiceLoader#load` uses `Thread.currentThread().getContextClassLoader()`. 
Put a breakpoint (debug mode) in `JwtVerifiers` to see what `ClassLoader ` trying to use (it's `PluginClassLoader` or something else).

**Comment by abcfy2** [comment]
Thank you. After add a logger debug:

```java
LOGGER.debug(JwtVerifiers.class.getClassLoader().toString());
```

The log is:

```
2021-11-12 10:13:50,540 DEBUG i.a.plugins.auth.FacebookAuthService - org.pf4j.PluginClassLoader@71bacacd
```

**Comment by abcfy2** [comment]
Maybe this issue is similar with https://github.com/pf4j/pf4j/issues/461 ?

**Comment by decebals** [comment]
> Maybe this issue is similar with #461 ?

Yes it's a possibility.

Can you create a simple [quickstarr](https://pf4j.org/dev/quickstart.html) application that replicate the problem and to make it public (on ghithub or a git repository in general)? The idea is to be able to reproduce and debug the problem is isolation.

**Comment by abcfy2** [comment]
Thank you. Please check:

[myproject.zip](https://github.com/pf4j/pf4j/files/7529259/myproject.zip)

Just use `unzip -d myproject myproject.zip`, then `cd myproject && ./run.sh`

**Comment by decebals** [comment]
As I anticipated in a [previous](https://github.com/pf4j/pf4j/issues/474#issuecomment-966414388) comment, `ServiceLoader#load` uses `Thread.currentThread().getContextClassLoader()` and the context `ClassLoader` is `AppClassLoader`.

If you use the `ServiceLoader` directly is not a problem because it's available a `load` method that receive a `ClassLoader` as parameter. When you indirectly the `ServiceLoader` via an external library (your case with OKTA) you have a problem because you cannot force a `PluginClassLoader`. 

The quick solution is to inject the `PluginClassLoader` as context class loader before you call the the part of external library that uses `ServiceLoader`.

In your example, we have something like (`com.mycompany.hello.HelloGreeting#getGreeting`):

```java
// save the current ClassLoader to restore it after ServiceLoader#load call
ClassLoader contextClassLoader = Thread.currentThread().getContextClassLoader();

// inject PluginClassLoader
Thread.currentThread().setContextClassLoader(getClass().getClassLoader());

// call indirectly SericeLoader#load
AccessTokenVerifier jwtVerifier = JwtVerifiers.accessTokenVerifierBuilder().build();

// restore initial context ClassLoader saved in the first step
Thread.currentThread().setContextClassLoader(contextClassLoader);
```

The same problem is available in OSGI.
For a client, to solve this problem I used aspects (AspectJ as library). The idea is to use an annotation (like `@ServiceLoaderAware` or a better name) to specify that a method uses internally the `ServiceLoader` and the aspect implementation will decorate the call of the method with what I described above (inject `PluginClassLoader` as thread context class loader).

For example:
```java
@ServiceLoaderAware
private AccessTokenVerifier getAccessTokenVerifier()  {
    // return something
}
```

**Comment by abcfy2** [comment]
Thank you very much. pf4j is a owsome project. Hope this will get better and better.

**Comment by decebals** [comment]
@abcfy2 Can we close this issue? Do you need help?

**Comment by abcfy2** [comment]
Yes.
