### ISSUE TITLE
Dependency injection for filesystem instance

### ISSUE THREAD

**Issue by tsuki-code** [pf4j/pf4j#476]
When inspecting plugin manager code, I noticed that whenever filesystem operations are performed, such as loading plugins, `Paths.get` method is invoked, which uses the default JVM filesystem instance. 

This makes testing difficult, because there is no local way of providing such file system. As an example, https://github.com/google/jimfs could be used for in-memory filesystem mocking.

This proposal would entail using java.nio `FileSystem` injecting whenever current `Paths.get` method is used. `fileSystemInstance.getPath` would be used instead.

**Comment by tsuki-code** [comment]
My real needs are as stated above. I am writing software that uses the plugin manager to load plugins that are stored on the file system. These plugins are updated over a custom connection and these updates are transactional, with rollbacks.
I want to test this code, and it is difficult without dependency injection.

**Comment by decebals** [comment]
@tsuki-code I understand the nature of your problem but did you test what I wrote in my previous [comment](https://github.com/pf4j/pf4j/issues/476#issuecomment-980797789)? If it works, there is no need to change anything in the code.

**Comment by decebals** [comment]
I don't know if it helps in your case but for testing please take a look on [testing](https://pf4j.org/doc/testing.html) documentation section.

**Comment by decebals** [comment]
In branch [file_to_path](https://github.com/pf4j/pf4j/tree/file_to_path) the `java.io` is replaced by `java.nio`.
Also, a new default `getFileSystem` method is added in `PluginManger`. You can override this method if you want to use other `FileSystem` (for example JIMFS).
@tsuki-code 
Please try to use this new branch a supply a feedback.

**Comment by decebals** [comment]
@tsuki-code is this topic still of interest to you?

**Comment by tsuki-code** [comment]
No, thank you

śr., 29 cze 2022, 00:15 użytkownik Decebal Suiu ***@***.***>
napisał:
