### ISSUE TITLE
Run pf4j with jetty embeded

### ISSUE THREAD

**Issue by centoria** [pf4j/pf4j#489]
Hello,

I have a ClassNotFoundException when i use pf4j whith an embedded jetty with this framework : https://sparkjava.com/.

I initialize the project by loading extensions, this work well i can see in logs that an extension wich is a DTO (MyDTO) is loaded.

But in my controller when i cannot instantiate it (new MyDTO) and i have a ClassNotFoundException.

When i add the plugin jar containing MyDTO in CLASSPATH i have a
h_MASTER_1646651529481_465 - loader constraint violation: loader org.pf4j.PluginClassLoader @510f3d34 wants to load class com.centoria.base.dto.helpe

I think its an issue with Jetty jEE class loading but i'm not sure. Can someone help me or guide me ?

Thanks

**Comment by centoria** [comment]
I have found a solution by putting class i need in core app in the classpath and use a jarpluginloader with a coumpoundplugin loader and some parameters for dev mode.

I'm not sure it's the good solution, i was thinking better to provide to jetty or jdk the PluginClassLoader but i dont know how to do so.

**Comment by decebals** [comment]
@centoria can you supply a quickstart project that replicates the problem in a easy way?

**Comment by decebals** [comment]
any resolution here?

**Comment by decebals** [comment]
Close it due to lack of response. You can reopen it with a new comment.
