### ISSUE TITLE
Unable to load plugins on certain OS

### ISSUE THREAD

**Issue by pmck91** [pf4j/pf4j#496]
Hello, 

Using the latest pf4j and the zip plugin format, I am running into weird issues on various linux based OS (such as ubuntu 20, 18 etc).

While the plugin manager is loading the plugin zip, it is finding an empty manifest.mf in the zips root directory, instead of the correct manifest in the classes dir. The issue is happening in `ManifestPluginDescriptorFinder`. 

this appears to be a bug that has been around for years. It throws this sort of exception: 

    08:21:03.760 [main] ERROR org.pf4j.AbstractPluginManager - Field 'id' cannot be empty
    org.pf4j.PluginRuntimeException: Field 'id' cannot be empty

The correct manifest is loaded on windows, mac, and several other systems.

**Comment by decebals** [comment]
We have `ManifestPluginDescriptorFinderTest` that contains zero failed tests.
![image](https://user-images.githubusercontent.com/1248311/168662551-fed2aa29-3a4d-43a2-97ba-e6e1fc0bbf36.png)
As you can see from above screenshot, my dev box is a Linux (Ubuntu) machine and I don't see any problem.
To reproduce the problem please add a new test in `ManifestPluginDescriptorFinderTest`, test that fails.

**Comment by decebals** [comment]
Any resolution here?

**Comment by decebals** [comment]
Close it due to lack of response. You can reopen it with a new comment.
