### ISSUE TITLE
Next release of PF4J?

### ISSUE THREAD

**Issue by vkolomeyko** [pf4j/pf4j#498]
I note that the latest release was `3.6.0` which got published in Jan-2021. There were multiple (important) changes in `master` branch since then.
Are there any plans to publish next release of PF4J and if so when?

Thank you!

@decebals ^

**Comment by decebals** [comment]
A new version will be available very soon (in few days - this week).

**Comment by decebals** [comment]
A new version (3.7.0) is available.
