### ISSUE TITLE
Host dependencies not being supplied to Plugins at runtime

### ISSUE THREAD

**Issue by pmck91** [pf4j/pf4j#500]
Hello, 

I am trying to moved shared dependencies out of plugins and into the host application. However I am unable to get the classes to match up properly, and using jackson as an example am receiving this error:

`java.lang.ClassCastException: class com.fasterxml.jackson.module.kotlin.KotlinModule cannot be cast to class com.fasterxml.jackson.databind.Module (com.fasterxml.jackson.module.kotlin.KotlinModule is in unnamed module of loader 'app'; com.fasterxml.jackson.databind.Module is in unnamed module of loader org.pf4j.PluginClassLoader`

in the build.gradle of the app I have jacksons kotlin module set to `CompileOnly`, and in the host I have it set to `Implementation`.

I am using the default pluginloader.

**Comment by decebals** [comment]
I don't know what to say about this issue.
From `is in unnamed module of loader 'app'` I understand that your application uses JPMS - Java Platform Modules System (Java 9+). I have not used PF4J with JPMS and have not received feedback from other users related to this subject.

**Comment by pmck91** [comment]
So for future reference, this was caused by clashing dependencies. excluding the offending deps from the plugin fully fixed this.
