### ISSUE TITLE
[Question] plugins with diferente dependencies

### ISSUE THREAD

**Issue by julianoBRL** [pf4j/pf4j#507]
I have "system A", it is the main one and it is the one that will load the plugins and it has the X,Y,Z libraries

i have "plugin B", the plugin has libraries X,Y,Z,T

"System A" doesn't have library T, is there any way to make the plugin work even with this extra library that the main one doesn't have?

I searched a lot but couldn't find a way to make it work.

**Comment by decebals** [comment]
I don't understand what is "system A". We use APD notation: A - application, P - plugin, D - plugin dependencies.

Please take a look on:
- https://pf4j.org/doc/class-loading.html
- https://github.com/pf4j/pf4j/blob/master/pf4j/src/main/java/org/pf4j/ClassLoadingStrategy.java
- https://github.com/pf4j/pf4j/pull/385
- https://github.com/pf4j/pf4j/issues/395

II would really appreciate it if someone could [update](https://github.com/pf4j/pf4j.github.io/blob/master/_posts/2018-07-19-class-loading.md) the ClassLoader [section](https://pf4j.org/doc/class-loading.html) of documentation. It would help a lot.
Just create a PR in https://pf4j.org/doc/class-loading.html with information extracted from #385, #395 and other issues/PRs that make reference to this topic. I will help that person.

**Comment by decebals** [comment]
@julianoBRL 
Can we close the issue or do you need more help?

**Comment by decebals** [comment]
Close it due to lack of response. You can reopen it with a new comment.
