### ISSUE TITLE
DefaultPluginManager.loadPlugin() does't resolve dependencies

### ISSUE THREAD

**Issue by decebals** [pf4j/pf4j#51]
Check to see if all the dependencies are resolved.

**Comment by decebals** [comment]
Also we must review and other methods: `stopPlugin`, `unloadPlugin`, `disablePlugin`, `enablePlugin`, `deletePlugin`.

**Comment by janhoy** [comment]
Also, `PluginDependency`'s versionSupport does not seem to be enforced anywhere? If someone upgrades a plugin but forgets to upgrade one of its dependencies, the upgraded plugin should not start?

**Comment by decebals** [comment]
> Also, PluginDependency's versionSupport does not seem to be enforced anywhere? If someone upgrades a plugin but forgets to upgrade one of its dependencies, the upgraded plugin should not start?

Yes. I feel that it's the responsibility of UI (or the layer over PF4J) to force you to don't make these kinds of mistakes. The UI (user interface) can create a graph with all the dependencies for an updated/installed plugin. The UI should calls under the hood the update/install method for each dependency and in the end it calls restart application. If the UI restarts the application then it's necessary to modify the `UpdateManager.installPlugin` method according to https://github.com/decebals/pf4j-update/issues/4#issuecomment-291503974 (we don't need to call `load` and `start` methods in the body of `installPlugin` method, these methods (load ans start) will be executed eventually from outside, after the install plugin process) .

**Comment by janhoy** [comment]
Do you know of any example in real world use where a plugin depends on another plugin? How do they do it?

A UI to manage plugin updates would probably either do it all from scratch without pf4j-update, in which case this project should support each step of the process. Or if pf4j-update is used, we can open another issue over there...
