### ISSUE TITLE
Question - Prevent plugin from accessing files, network, etc.

### ISSUE THREAD

**Issue by nicoi15** [pf4j/pf4j#510]
Hello! Is there a way to prevent plugins from accessing all things that we specify? We don't want the plugins developers to have malicious codes in their plugins.

We are using JDK 17, windows 11 and PF4J version 3.8.0.

Thank you in advance for any advise or recommendation!

**Comment by decebals** [comment]
I think that you need a [SecurityManager](https://docs.oracle.com/javase/tutorial/essential/environment/security.html). See also #127 and #379.

**Comment by nicoi15** [comment]
Would this be the only way to secure even though SecurityManager is getting removed in Java 17 and later? Please see reference https://openjdk.org/jeps/411.

**Comment by decebals** [comment]
> Would this be the only way to secure even though SecurityManager is getting removed in Java 17 and later? Please see reference https://openjdk.org/jeps/411.

I have no other idea on this topic. If anyone has another idea, I'm curious to hear it.

**Comment by nicoi15** [comment]
Okay, I see. No worries, we'll try to find if there's an alternative or we could just use the SecurityManager for the meantime. Thank you.

**Comment by decebals** [comment]
@nicoi15 Did you find a solution? If your answer is yes, please share with us your solution.
Can we close the issue or do you need more help?

**Comment by decebals** [comment]
Close it due to lack of response. You can reopen it with a new comment.

**Comment by decebals** [comment]
I found [1] in the context of this discussion. Maybe it could help.

[1] https://inside.java/2021/04/23/security-and-sandboxing-post-securitymanager/

**Comment by nicoi15** [comment]
Thank you for this and sorry for the very late response. For now, we are just using the SecurityManager as you first suggested. We will look into this post Security Manger too. Thank you!
