### ISSUE TITLE
zip file plugin does not work

### ISSUE THREAD

**Issue by diddowill** [pf4j/pf4j#511]
Use Case:
I pack my plugin as my-zip-plugin.zip, and put it in the default plugin dir as: /plugins/my-zip-plugin.zip

Error:
Exception is thrown with message:
No PluginDescriptorFinder for plugin 'plugins/my-plugin'

Cause:
the  FileUtil::expandIfZip method duplicates the zip file name in the file path, i.e., my-zip-plugin.zip is unziped as:
/plugins/my-zip-plugin/my-zip-plugin.
Then plugin descriptor finder tries to find plugin definition in upper folder: /plugins/my-zip-plugin, and failed.

**Comment by decebals** [comment]
@diddowill 
Can you put more context please? I don't understand what is special about your zip file.
It helps a lot if you can attach the zip file (of course if it's not that big).

**Comment by decebals** [comment]
@diddowill 
Any news here?
In the end, according to your initial comment (the part with `plugins/my-zip-plugin/my-zip-plugin` from stack trace) I feel that your plugin is packaged wrong (you have a root `my-zip-plugin` inside of zip file).

**Comment by decebals** [comment]
Close it due to lack of response. You can reopen it with a new comment.
