### ISSUE TITLE
[Question]about the custom annotation 

### ISSUE THREAD

**Issue by side-wipe** [pf4j/pf4j#518]
The problem is that when I try to write a custom annotation and a custom processor refer to @Extension processor, then i build the project and get a CompilationFailureException because Maven can't find the processors. like this:
`javax.annotation.processing.Processor: Provider com.pro.BaseProcessor not found`.
But when i build pf4j project,i do not get this Exception,i do not know why? Do you have any configuration I have ignored? Please help me with this,thanks

**Comment by decebals** [comment]
what means:
> a custom processor refer to @extension processor

**Comment by side-wipe** [comment]
emm....., you can think I want to write a custom `AnnotationProcessor`, just like the `ExtensionAnnotationProcessor` in your pf4j, but it failed to build as successfully as your project, so I have the above problem.

**Comment by decebals** [comment]
I don't think that is related PF4J. You need to investigate more.

**Comment by side-wipe** [comment]
sorry, maybe i did't express it clearly, i just want to know did you have the same problem(build the `ExtensionAnnotationProcessor ` failed) when you use the `AnnotationProcessor` in this project.

**Comment by decebals** [comment]
No, I have not encountered such a problem.
