### ISSUE TITLE
Loading extensions not working with fat jars

### ISSUE THREAD

**Issue by finn0s** [pf4j/pf4j#519]
## Environment
I'm using a multi module project (maven modules) with three modules.
* Share: contains a `BaseExtension` class
* Plugin: contains a `DummyExtension` class extending the `BaseExtension` class from the Share
* Main: The main class that tries to load all `BaseExtensions`

The Plugin module ist build as a fat jar.
The main class tries to load all extensions as seen below.
<pre>
final JarPluginManager jarPluginManager = new JarPluginManager(jarFile);
jarPluginManager.loadPlugins();
jarPluginManager.startPlugins();
final List<BaseExtension> extensions = jarPluginManager.getExtensions(BaseExtension.class);
System.out.println(extensions);
</pre>

## The Problem
If the Plugin is build with the `maven-assembly-plugin` (**creates a fat jar**). The `getExtensions` method returns an empty list.

If the Plugin is build with the `maven-jar-plugin` (**no fat jar**) it works fine and the `DummyExtension` is returned.

## Example
You can download the minimal example project [here](https://github.com/pf4j/pf4j/files/10933572/example.zip).
To run the main class execute the following commands in the example folder.
<pre>
mvn clean install
java -jar Main/target/Main-1.0-SNAPSHOT.jar
</pre>

The last output in the console is a list with all loaded extensions.

## Possible reason
When the plugin jar is build as a fat jar, the `Share` project is also included in the jar file.
I think this problem occurs because of the `BaseExtension` is loaded by two different ClassLoaders.

![issue](https://user-images.githubusercontent.com/90374296/224082108-0a4eac42-8df6-4dba-98ff-5f123c37834c.png)

1. The Application tries to load all extensions based on the `BaseExtension (AppClassLoader)` class.
2. The PluginSystem finds the `DummyExtension` class and check if it is an instance of `BaseExtension (AppClassLoader)` (<b>AbstractExtensionFinder:143</b>).
3. But the `DummyExtension` is an instance of the `BaseExtension (PluginClassLoader)`.

**Comment by decebals** [comment]
I see from your example that you are using Spring Boot as app launcher.
As you yourself mentioned, it's a problem related to packaging.Maybe https://github.com/pf4j/pf4j/issues/341#issuecomment-541330123 can help you.

By the way, what tool did you use to generate the diagram?

**Comment by finn0s** [comment]
Thanks for the answer.
Using the <code>provided</code> scope fixed the problem described in this issue as well as the problem from #505.
I think you can close both issues. It would be helpfull to add another troubleshoot article to the website for other users dealing with this problem.

I used [excalidraw](https://excalidraw.com/) for the diagram.

**Comment by decebals** [comment]
> I think you can close both issues. It would be helpfull to add another troubleshoot article to the website for other users dealing with this problem.

Yes, I will do it.

As a feedback, I like the detailed description you put.
