### ISSUE TITLE
New plugin type: Thin jar with unpacked lib subdirectory

### ISSUE THREAD

**Issue by sschuberth** [pf4j/pf4j#523]
This relates a bit to https://github.com/pf4j/pf4j/issues/208, but addresses the concerns expressed in [this comment](https://github.com/pf4j/pf4j/issues/208#issuecomment-406192186). The proposal is to support loading plugins from a "thin" / regular JAR, plus dependency JARs that are located as-is (i.e. not ZIPped) on disk, like in the approach documented [here](https://medium.com/geekculture/designing-a-lightweight-plugin-architecture-in-java-5eedfeaa92a9#60b0). So the idea is to have a separate subdirectory below "libs" for each plugin which contains all JARs required for the plugin, including the plugin JAR itself. Alternatively, one more directory level could be introduced to separate the plugin JAR from its dependency JARs.

That approach gives more immediate visibility of the number of dependency JARs a plugin has, and compression-wise there is no gain in putting JARs into a ZIP anyway. Eventually, this could even help to deduplicate dependency JARs that are shared across plugins by using something like hard-links, if the underlying filesystem supports that.

**Comment by decebals** [comment]
Sure, a such plugin structure can be implemented but honestly I don't see a real value.
The plugin zip format is implemented in core but in the end the plugin is unzipped before loading. I think that we can load plugins in a non zip format (a directory for each plugin).

**Comment by decebals** [comment]
I checked and by default pf4j knows how to load plugin from a directory.
See below the file layout:
```
decebal@latitude-5501:~/work/pf4j-test/test-dist$ tree .
.
├── lib
│   ├── commons-lang-2.4.jar
│   ├── java-semver-0.9.0.jar
│   ├── jul-to-slf4j-2.0.6.jar
│   ├── log4j-1.2.16.jar
│   ├── pf4j-3.9.0.jar
│   ├── reload4j-1.2.22.jar
│   ├── slf4j-api-1.7.30.jar
│   └── slf4j-reload4j-2.0.6.jar
├── pf4j-test-app-0.1.jar
└── plugins
    └── pf4j-test-plugin-0.1
        └── classes
            ├── META-INF
            │   ├── extensions.idx
            │   ├── MANIFEST.MF
            │   └── maven
            │       └── org.pf4j.test
            │           └── pf4j-test-plugin
            │               ├── pom.properties
            │               └── pom.xml
            └── org
                └── pf4j
                    └── demo
                        └── welcome
                            ├── WelcomePlugin$WelcomeGreeting.class
                            └── WelcomePlugin.class

13 directories, 15 files
```

**Comment by decebals** [comment]
You can use a new `PluginLoader` implementation if you want a specific custom format for plugins.

**Comment by sschuberth** [comment]
Interesting, why is `pf4j-test-plugin-0.1` itself not a jar?

**Comment by decebals** [comment]
> why is pf4j-test-plugin-0.1 itself not a jar?

By default pf4j works with (fat)jar, zip and directory (zip unzipped) as plugin format.

**Comment by sschuberth** [comment]
Ok, so what I'd be looking for is a layout like

```
.
├── pf4j-test-app-0.1.jar
└── plugins
    └── pf4j-test-plugin-0.1
        ├── pf4j-test-plugin-0.1.jar
        └── lib
            ├── commons-lang-2.4.jar
            ├── java-semver-0.9.0.jar
            ├── jul-to-slf4j-2.0.6.jar
            ├── log4j-1.2.16.jar
            ├── pf4j-3.9.0.jar
            ├── reload4j-1.2.22.jar
            ├── slf4j-api-1.7.30.jar
            └── slf4j-reload4j-2.0.6.jar
```

Is this also easily possible to implement currently with a custom `PluginLoader`?

**Comment by decebals** [comment]
Builtin, for a plugin you have the below format (with `classes` directory instead of plugin.jar):
```
.
├── pf4j-test-app-0.1.jar
└── plugins
    └── pf4j-test-plugin-0.1
        ├── classes
        └── lib
            ├── commons-lang-2.4.jar
            ├── java-semver-0.9.0.jar
            ├── jul-to-slf4j-2.0.6.jar
            ├── log4j-1.2.16.jar
            ├── pf4j-3.9.0.jar
            ├── reload4j-1.2.22.jar
            ├── slf4j-api-1.7.30.jar
            └── slf4j-reload4j-2.0.6.jar
``` 
where `classes` directory contains plugin classes (and other resources) and `lib` directory contains plugin dependencies.
In my example from https://github.com/pf4j/pf4j/issues/523#issuecomment-1635016858, the plugin has no external dependencies -> no `lib` folder.
I want to add a remark here. The `lib` directory contains app external dependencies and `plugin/lib` contains plugin external dependencies.  So your example with pf4j.jar and stuff (content of app/lib) in `plugin/lib` is not exactly accurate.

> Is this also easily possible to implement currently with a custom PluginLoader?

Yes. In your case I think it's enough to supply a custom `PluginClasspath` (take a look on `DevelopmentPluginClasspath` as example). In more complex cases/formats you need to add a custom `PluginLoader` (probably extends `BasePluginLoader`).

**Comment by sschuberth** [comment]
Ok, thanks, then it's probably good to close this.
