### ISSUE TITLE
keep the access modifier  consistent

### ISSUE THREAD

**Issue by dre4merp** [pf4j/pf4j#524]
In DefaultPluginFactory
``` java
public class DefaultPluginFactory implements PluginFactory {
    protected static final Logger log = LoggerFactory.getLogger(DefaultPluginFactory.class);
    ......    
}
```

In DefaultExtensionFactory 
``` java
public class DefaultExtensionFactory implements ExtensionFactory {
    private static final Logger log = LoggerFactory.getLogger(DefaultExtensionFactory.class);
    ......
}
```

We can see that the log access modifiers are different in similar classes. I don't know what your original intention is, but I think they should be consistent. And they both should be `private`.

**Comment by decebals** [comment]
If I remember correctly the idea was to make to makes logging service available for descending classes.
They are only to classes with protected logger:
- DefaultPluginFactory
- Plugin

The logger defined in Plugin is sensible to this modification and it has a special target.
I think that we could make the modification in DefaultPluginFactory. Please create a PR.

**Comment by dre4merp** [comment]
Thanks for your prompt reply, I have submitted the PR.
