### ISSUE TITLE
Can we pass parameters/data's to plugins during the time of starting the plugin ?

### ISSUE THREAD

**Issue by MadhavanAnanthan** [pf4j/pf4j#530]
HI @decebals 

I want to pass a few parameters to the respective plugin, Is it possible to use PF4J or any external lib? Because I didn't see any internal methods to pass the parameter while starting the plugin?

**Comment by decebals** [comment]
You can use a PluginContex (see https://github.com/pf4j/pf4j/pull/512) or a custom PluginFactory (see https://github.com/pf4j/pf4j/issues/319).

**Comment by decebals** [comment]
@MadhavanAnanthan 
Do you still need help related to this issue? If your answer is no, please close the issue.
