### ISSUE TITLE
How to get plugin related information in extension 

### ISSUE THREAD

**Issue by dre4merp** [pf4j/pf4j#531]
extension.java
```
@Extension
public class FooExtension implements ExtensionPoint {

    public FooExtension (){
    }
    
    @Override
    public void service() {
        String pluginId;
        String pluginVersion;
        System.out.println(pluginId+pluginVersion);
    }
}
```
How to get plugin related information in extension ?
The `create` of `ExtensionFactory` only provides the `Class` parameter.
Can I get the corresponding plugin information and send it to the Extension.

**Comment by decebals** [comment]
Sorry, I think I missed your post.
Why you need information about plugin in extension?

**Comment by dre4merp** [comment]
The plugins is working on serveal clients. Its role is to send some information to the server. So I wanan know which version is the information comes from.

By the way, I have solved this problem by using custom `ExtensionFactory`. I build a ExtensionContext which including descriptor geting by `.whichPlugin(extensionClass).getDescriptor()` .

**Comment by decebals** [comment]
Yes indeed, the `whichPlugin` method is what you are looking for.
Please close the issue if you have solved the problem.
