### ISSUE TITLE
How to use it under jdk6 ?

### ISSUE THREAD

**Issue by dre4merp** [pf4j/pf4j#535]
I'm writing a project now, unfortunately I can only use jdk6. 
Does any version supports JDK6, such as 1.3.0?
Do you recommend that I use the old version or modify the current pf4j to be compatible with jdk6?

**Comment by decebals** [comment]
First of all what problems are you having? Chances are it won't work but you need to try.

**Comment by dre4merp** [comment]
My English is not very good, I'm sorry if I didn't describe the problem clearly.

I'm working on a project and want it to have the ability to load and unload plugins. I can only use jdk6, but the latest pf4j is compiled using jdk9 (compatible with jdk8), which does not work well under jdk6. 

In order to solve this problem, I have two ideas. 
1. Reference the latest version pf4j.jar which supports jdk6, but I don't know which version it is. 
2. Modify the source code of the existing pf4j and compile it with jdk6. 

I don't know which solution is better, so I want to ask for your suggestion.

Anyway, thanks for your answer.

**Comment by decebals** [comment]
My idea is to try to use the current version of pf4j in your jdk8. Try to compile your project with the latest version of pf4j as a dependency and see the result.

**Comment by dre4merp** [comment]
I have tested it under jdk8 and pf4j works fine without any problem.

But now, I need develop under jdk6,  the following is the result of demo test.

![image](https://github.com/pf4j/pf4j/assets/40335717/6d4f56de-fce0-4f5b-84e2-aa2ad7b85ee4)

Obviously, it doesn't work. The code of jdk8 (bytecode 52.0) cannot run under jdk6 (bytecode 50.0). That's why I need your advice.

**Comment by decebals** [comment]
You can use an old version (see the history of pom.xml -> source/target = 1.6) of pf4j or you can try to modify the current version (use old version for maven plugins + modify the source files -> remove diamond, ..)
