### ISSUE TITLE
The method of extracting the zip file has a path traversal vulnerability

### ISSUE THREAD

**Issue by afeng2016-s** [pf4j/pf4j#536]
## description
Dear project developers, I use SpringBoot and pf4j to implement the system's extension plug-in function, the use of zip or jar package format is very easy to expand the system. When I was using pf4j, I found that the pluginPath value was not verified securely when loading plug-ins. If the developers using pf4j were not security conscious, directly calling the loadPluginFromPath method to receive malicious parameters passed by untrusted users would lead to directory traversal vulnerabilities.

## affected version
<= release-3.9.0

## [vulnerability analysis](javascript:;)
The sample code attempts to extract a malicious file (for example: C:\Windows\notepad.exe) to the root path of drive E to simulate a directory traversal attack.
1. Build a malicious ZIP file，Save the resulting ZIP file to E:\\Code\\0811\\malicious.zip。
![image](https://github.com/pf4j/pf4j/assets/85676107/44f28efb-dd32-4695-b646-5c35f1df74d6)

2, write a test class, call DefaultPluginManager#loadPluginFromPath method to load E:\\Code\\0811\\malicious.zip
![image](https://github.com/pf4j/pf4j/assets/85676107/76b4e717-cf2d-4773-9a86-b3be5bc55972)

First run a test class to prove that the path E:\Windows\notepad.exe does not exist.
![image](https://github.com/pf4j/pf4j/assets/85676107/f895e117-c6c7-492e-bdfa-194bff0352ee)

3. Debug the code
Go to DefaultPluginManager#loadPluginFromPath.
Load the plug-in from disk. If the path is a zip file, unzip it first.
![image](https://github.com/pf4j/pf4j/assets/85676107/46477780-15bb-479a-9c71-c1ddb0fc2427)

Do some preparatory work in FileUtils
![image](https://github.com/pf4j/pf4j/assets/85676107/fa1bc2b1-4392-4553-be5d-7d4d67cd6ec9)

Follow up unzip.extract()
![image](https://github.com/pf4j/pf4j/assets/85676107/d2115c93-8fef-4620-b978-57f9032a5dd6)

![image](https://github.com/pf4j/pf4j/assets/85676107/c9a14ad1-851a-4387-9c7e-a573afcc134f)

After the execution is complete, extract the target file to the root directory of drive E.
![image](https://github.com/pf4j/pf4j/assets/85676107/ea3352a6-91d4-4283-9b2a-23a641ce876a)

![image](https://github.com/pf4j/pf4j/assets/85676107/f2c85bc7-f1b6-4099-840d-6871ba8d85c5)

**Comment by decebals** [comment]
Duplicate of #526. Honestly I don't understand these kind of issues. I see a pattern. Again, instead of detailed description please provide a PR (test that replicate the problem and the fix).

**Comment by afeng2016-s** [comment]
Thanks for your prompt reply, I have submitted the PR.
