### ISSUE TITLE
Diagram from the "Plugin lifecycle" ?

### ISSUE THREAD

**Issue by aadrian** [pf4j/pf4j#541]
Hi,

For the Plugin Lifecycle https://pf4j.org/doc/plugin-lifecycle.html  is there any Diagram, e.g. like https://plantuml.com/state-diagram to just illustrate it?
_(from the description one can't figure out what transitions happen and when and what is allowed and what not)_

Thank you.

**Comment by decebals** [comment]
Maybe https://github.com/pf4j/pf4j/issues/198#issuecomment-360344350 is a good start point.
I think there is a diagram somewhere (issue/PR) but I can't find it at the moment.
Finally, a diagram in the lifecycle doc page will be helpful.

**Comment by decebals** [comment]
@aadrian What is the status of this, can we close the issue?

**Comment by aadrian** [comment]
> can we close the issue?

@decebals  sure,  but is the diagram from the PR https://github.com/pf4j/pf4j/issues/198#issuecomment-360344350 still up to date, or is it already obsolete?

**Comment by decebals** [comment]
> @decebals sure, but is the diagram from the PR [#198 (comment)](https://github.com/pf4j/pf4j/issues/198#issuecomment-360344350) still up to date, or is it already obsolete?

I think that is still up to date. I don't know if that diagram has a source and it can be edited. Maybe @hxzhao527 can tell more about this.
Finally, if I had something editable, I could add the diagram to the documentation.
We'll see, now we don't have new functionalities in pipe, the only thing that can bring a consistent value to the project is an improvement of the documentation.

**Comment by aadrian** [comment]
> I don't know if that diagram has a source

@decebals it does not matter, since PlantUML allows to quickly create new ones. e.g. see https://gist.github.com/aadrian/931db30dcd26744895621a99ba9b52c3

That would look like: https://tinyurl.com/pf4jdiagram
