### ISSUE TITLE
Security updates release?

### ISSUE THREAD

**Issue by emilaasa** [pf4j/pf4j#542]
Will there be a release addressing these CVEs?

https://github.com/advisories/GHSA-cj8w-v588-p8wx
https://github.com/advisories/GHSA-rvm8-j2cp-j592
https://github.com/advisories/GHSA-3r28-rgp9-qgv4

The latest commit on master looks pretty promising

**Comment by decebals** [comment]
The new version (3.10.0) contains a security fix related to https://github.com/pf4j/pf4j/issues/526.
