### ISSUE TITLE
org.pf4j.PluginRuntimeException: Field 'id' cannot be empty but it exists

### ISSUE THREAD

**Issue by ErSeraph** [pf4j/pf4j#543]
Hi, Im trying to create a plugin using Spring. I put plugin.properties in src/main/resources with this content as a test:

plugin.id=Bello
plugin.class=it.seraph.bello.PluginBelloApplication

But my main Spring project says that "field id cannot be empty", what am I doing wrong?

**Comment by decebals** [comment]
Please take a look at https://pf4j.org/doc/plugins.html.
> Create a file called `plugin.properties` in the root of your plugin folder (or ZIP/JAR archive)

**Comment by decebals** [comment]
@ErSeraph Did you finally find out where the problem was?

**Comment by ErSeraph** [comment]
Hi! Yes, I had to write these information in pom.xml
