### ISSUE TITLE
Where is the correct "entry point"?

### ISSUE THREAD

**Issue by k1ll1n** [pf4j/pf4j#544]
Hi, I don't quite understand what the entry point is.

For example, in plugins for Minecraft servers there is another entry point (its own main), in which we receive the context and from it we write our plugin.

But there are several entry points.
1. Entry point in the descendants of the Plugin class
these are: methods start() stop() delete()

2. Entry point in the successors of ExtensionPoint

I don't understand where I should start writing my code.

Thanks in advance for any explanation!

**Comment by decebals** [comment]
According README (home page of the project on GitHub):
- **ExtensionPoint** is a point in the application where custom code can be invoked. It's a java interface marker.   
Any java interface or abstract class can be marked as an extension point (implements `ExtensionPoint` interface).
- **Extension** is an implementation of an extension point. It's a java annotation on a class.
- **PLUGIN** = a container for **EXTENSION POINTS** and **EXTENSIONS** + lifecycle methods (start, stop, delete)

I know nothing about the plugins ecosystem of Minecraft, so I cannot tell you what is an entry point.

**Comment by milgner** [comment]
I'd say that in the end it's up to the application that integrates PF4J to decide where individual plugins should have their entry point. Personally I prefer having only rudimentary initialisation in `Plugin::start` and then have a kind of `Worker` extension point for which the launcher instantiates all associated extensions and starts them. Using structured concurrency (in Kotlin, but it's available in Java 21, too, I learned today) one can then start jobs from within these workers and have them torn down when anything goes wrong. Then a supervisor process can re-start the worker extension in these cases.

**Comment by decebals** [comment]
@k1ll1n Is it clearer now?Can we close the issue?

**Comment by decebals** [comment]
Please open this issue if you consider that you have not been answered.
