### ISSUE TITLE
Support Kotlin KSP with PF4J

### ISSUE THREAD

**Issue by delopst** [pf4j/pf4j#552]
Hi.

In older Kotlin versions (< 1.9.10) we used PF4J using KAPT which is able to use Java annotation processing (we could use Extension annotation processing).

Since KAPT is now deprecated we need to use KSP.  
I developed a simple KSP plugin that is able to generate extensions.idx file or JSP files from simple, nested or inner Kotlin classes annotated with @Extension and implement ExtensionPoint interface.

Would you be interested in forking the KSP plugin in the PF4J repository and release it under pf4j account?

Regards, Primož

**Comment by decebals** [comment]
Hi

See my answer in https://github.com/pf4j/pf4j/discussions/547.

**Comment by delopst** [comment]
Hi.

For the time being, I already published the code here since we were in a hurry: https://github.com/better-care/pf4j-kotlin-symbol-processing.

I can also reply to this in the [#547](https://github.com/pf4j/pf4j/discussions/547) or we can continue the conversation here.
I am open to any discussion about transferring the repository somewhere else if needed. I can also offer some maintenance of the plugin to be compatible with the latest Kotlin versions.

Regards, Primož

**Comment by delopst** [comment]
Closing the issue and moving the discussion here [#547](https://github.com/pf4j/pf4j/discussions/547).
