### ISSUE TITLE
Getting extensions by class when plugin is not started

### ISSUE THREAD

**Issue by milgner** [pf4j/pf4j#553]
The method [`PluginManager#getExtensions(java.lang.Class)`](https://www.javadoc.io/static/org.pf4j/pf4j/2.4.0/org/pf4j/PluginManager.html#getExtensions(java.lang.Class)) only returns extensions from started plugins.

In my project I'd like to use the extension mechanism to find database migrations in all plugins. It is a bit unfortunate that plugins now have to start before their migrations have been applied: if a plugin author would try to use `Plugin#start()` to do something database-related, it wouldn't work. Our work-around was adding another `started` callback - but it would be useful to have a way to get extensions without starting the plugins.

One idea would be to have an overloaded `PluginManager#getExtensions` method that takes a `PluginState` argument.

**Comment by decebals** [comment]
> The method [PluginManager#getExtensions(java.lang.Class)](https://www.javadoc.io/static/org.pf4j/pf4j/2.4.0/org/pf4j/PluginManager.html#getExtensions(java.lang.Class)) only returns extensions from started plugins.

How did you come to this conclusion?

**Comment by decebals** [comment]
I need more information about what you try to achieve, your flow.
Something similar with:
1. load plugins
2. get extensions
3. do something (migration)
4. start plugins

**Comment by decebals** [comment]
In https://pf4j.org/doc/plugin-lifecycle.html, we have this statement:
> only STARTED plugins may contribute extensions. Any other state should not be considered ready to contribute an extension to the running system.

**Comment by milgner** [comment]
> I need more information about what you try to achieve, your flow.
> Something similar with:
> 1. load plugins
> 2. get extensions
> 3. do something (migration)
> 4. start plugins

Yes, that's exactly it. There is an ExtensionPoint `DatabaseMigration` which has Extensions through plugins. When the app starts, it finds all these extensions and applies the migrations through Flyway.
Afterwards, the system is considered fully started and ready to do actual work.

At the moment, we introduced an `AbstractPlugin` base class which - along some functionality to set up a dependency injection container - also has an additional `notifyStarted()` method that can be overridden by plugins that want to do initiate some work after startup.

This is fine - I'm just afraid it might cause confusion down the line once everything is published and someone tries to override the standard `start()` method of the base `Plugin` class.

The distinction to have only started plugins contribute extensions probably makes sense in a lot of / most scenarios. But I was still wondering whether it might be possible to enhance the mechanism to retrieve extensions of all plugins.

**Comment by decebals** [comment]
The protection (I talk here about only started plugins) is in [AbstractExtensionFinder#find](https://github.com/pf4j/pf4j/blob/master/pf4j/src/main/java/org/pf4j/AbstractExtensionFinder.java#L91).
I prefer to not change the current behavior.
In your `PuginManager`  implementation (extends `DefaultPluginManager`) you can add a new method with implementation similar with:
```java
public List<T> getAllExtensions(Class<T> type) {
    List<T> extensions = new ArrayList<>();
    List<PluginWrapper> plugins = getPlugins();
    for (PluginWrapper plugin : plugins) {
        Set<String> classNames getExtensionClassNames(plugin.getPluginId()));
        // for each className checks that extension class is implementation of method parameter `type` (via classloader)
        // for each checked className executes extensionFactory#create
    }

    return extensions;
}
```
It's only an idea, I'm not 100% sure it will work but you can try.

On the other hand, you say:
>This is fine - I'm just afraid it might cause confusion down the line once everything is published and someone tries to override the standard start() method of the base Plugin class.

I recommend to have an `AbstractPlugin` or `BasePlugin` for all your plugins, in this mode you can put more context in each plugin, you can come with helper methods, and so one. You can mark method `start` as final in this abstract/base class to prevent the override.

**Comment by milgner** [comment]
Thank you for elaborating! I'll do that!
