### ISSUE TITLE
define the execution sequence of extensions across the plugins

### ISSUE THREAD

**Issue by MunichandraPolanki** [pf4j/pf4j#559]
@decebals  Thanks for pf4j library , its helpful :)

I have a project with multiple plugins and some of those plugins have multiple extensions. Currently with the 'PluginDependencies' property I can only get the plugin's order of execution . I can use 'Ordinal' among the extensions with in a SINGLE plugin to impose an order of execution among extensions. But , I have a special situation like following .

I have 3 plugins namely PluginA, PluginB and PluginC.

PluginA has 2 extenions PluginAExt1, PluginAExt2
PluginB has 3 extensions PluginBExt1, PluginBExt2, PluginBExt3
PluginC has 2 extensions PluginCExt1,PluginCExt2

Dependency graph b/w plugins as per my requirement is like this . PluginC -> PluginB ->PluginA ,PluginC.
That means I get into cyclic dependency exception.

The actually execution dependency in my use case supposed to have dependency among the extensions.

This is the dependency graph among the extensions I am expecting for my use case which does not function with the current PF4j.

PluginCExt1 -> PluginBExt1 -> PluginAExt1, PluginCExt2.

In a nutshell, I would like to have provision to define the execution sequence of extensions across the plugins.! It seems like , I have to reinvent the wheel using the way pf4j calculates the plugin's dependency graph.

We could also have single extension per plugin, then using just 'PluginDependencies' property we could get the dependency graph provided by PF4J, but that is something we don't want to have as we have strong reasons to include multiple extensions in a single plugin.

Inputs are highly appreciated, thanks!

**Comment by decebals** [comment]
> I have 3 plugins namely PluginA, PluginB and PluginC.
PluginA has 2 extenions PluginAExt1, PluginAExt2
PluginB has 3 extensions PluginBExt1, PluginBExt2, PluginBExt3
PluginC has 2 extensions PluginCExt1,PluginCExt2

I don't see the extensions points, in which plugins are they defined? 
And I don't see the plugins definitions in terms of dependencies. Can you share them?

> Dependency graph b/w plugins as per my requirement is like this . PluginC -> PluginB ->PluginA ,PluginC.
That means I get into cyclic dependency exception.

Are you getting this exception when you start the app?

**Comment by MunichandraPolanki** [comment]
In the screenshots, i have real plugin names.
I do have only one extension point named 'PluginExtension' (Its an abstract class) which is implementing the 'ExtensionPoint' from pf4j and it is defined in API module. All the extensions from the plugins are extending 'PluginExtenion'. 

> > I have 3 plugins namely PluginA, PluginB and PluginC.
> > PluginA has 2 extenions PluginAExt1, PluginAExt2
> > PluginB has 3 extensions PluginBExt1, PluginBExt2, PluginBExt3
> > PluginC has 2 extensions PluginCExt1,PluginCExt2
> 

This is the dependencies graph for the plugins (-> represents depends on)  PluginC -> PluginB,PluginA ->PluginA ,PluginC.
> I don't see the extensions points, in which plugins are they defined? And I don't see the plugins definitions in terms of dependencies. Can you share them?

![image](https://github.com/pf4j/pf4j/assets/53851768/2d6a2e35-8804-4ccb-875e-7962d5604a2b)
![image](https://github.com/pf4j/pf4j/assets/53851768/85bacec9-46e7-4498-8b17-21a83f33e78c)
![image](https://github.com/pf4j/pf4j/assets/53851768/bf495ba2-39bb-4648-9a7c-9e6a774f9eab)




> > Dependency graph b/w plugins as per my requirement is like this . PluginC -> PluginB ->PluginA ,PluginC.
> > That means I get into cyclic dependency exception.
> 
> Are you getting this exception when you start the app?
![image](https://github.com/pf4j/pf4j/assets/53851768/0de22f34-f177-46a6-85f8-20c9f353f921)

**Comment by decebals** [comment]
The current behavior is normal. You have cyclic dependencies in your project, `ecu-plugin` depends on `sync-plugin` and `sync-plugin` depends on `ecu-plugin`.
What are your expectations in this case?

**Comment by MunichandraPolanki** [comment]
May be my first comment in the issue is lengthy and did not point out my exact requirement. Let me put it in a simple sentence.. With current pf4j, I can only order the extensions from a same plugin using 'Ordinal' annotation   How to impose dependency order among the extensions across different plugins? 

imagine following 3 plugins and their respective extensions .


sync-plugin has 2 extenions sync-pluginExt1, sync-pluginExt2
ecu-plugin has 2 extensions ecu-pluginExt1, ecu-pluginExt2
vcu-plugin has 1 extension vcu-pluginExt1

This is the dependency graph among the extensions I am expecting for my use case which does not function with the current PF4j.
(-> indicates dependency order)

ecu-pluginExt1-> sync-pluginExt1 -> ecu-pluginExt2, vcu-pluginExt1


do you see the problem here? If i go with the concept of plugin dependency, i get into cyclic dependency exception.

**Comment by decebals** [comment]
> I can only order the extensions from a same plugin using 'Ordinal' annotation

No, your order all the extensions, for all plugins

> This is the dependency graph among the extensions 
> ecu-pluginExt1-> sync-pluginExt1 -> ecu-pluginExt2, vcu-pluginExt1

The dependency graph is created only to resolve the order of plugins, nothing about extensions.

I think that you misunderstanding something but I don't know what.
The fact that you get a cyclic dependency exception is a bad sign.

They are multiple solutions to avoid cyclic dependency exception, one of them is to put common classes (extensions points for example) in a separate plugin shared by multiple other plugins.
You show us only few plugins with extensions inside of each plugin. I don't understand why you declare this cyclic dependency between two or more plugins, what you try to achieve?
Also, it's not clear where you define the extensions points.

Please try to start from [demo](https://pf4j.org/doc/demo.html).
And if encounter problems, as I said in one of my previous comment, please create a runnable [quickstart](https://pf4j.org/dev/quickstart.html) example and share it with us via GitHub.

**Comment by decebals** [comment]
@MunichandraPolanki What is the current status of this issue? Do you still need help?

**Comment by decebals** [comment]
Please reopen the issue if you still need help.
