### ISSUE TITLE
Is pf4j compatible with arrch64 architecture?

### ISSUE THREAD

**Issue by leoyim** [pf4j/pf4j#562]
When I build my project on a arrch64 linux machine, it runs wrong
report the following problem:
`Fatal error compiling: java.lang.NoClassDefFonudError: org/pf4j/processor/ExtensionAnnotationProcessor: org.pf4j.processor.ExtensionAnnotationProcessor -> [Help 1]`

**Comment by decebals** [comment]
Can you add more context?

> Is pf4j compatible with arrch64 architecture? 

PF4J is not special from this point of view. `ExtensionAnnotationProcessor` is a standard annotation processor.

**Comment by decebals** [comment]
@leoyim I'm just curios, did you find something (cause of the problem, ..)?

**Comment by leoyim** [comment]
> @leoyim I'm just curios, did you find something (cause of the problem, ..)?

@decebals I build my project on an arrch64 machine, it runs wrong.

>  `Fatal error compiling: java.lang.NoClassDefFonudError: org/pf4j/processor/ExtensionAnnotationProcessor: org.pf4j.processor.ExtensionAnnotationProcessor -> [Help 1]`

But it runs successfully on a x86_64 machine, I don't find any differences about my build script. So, I want to know is pf4j compatible with arrch64. Have you tried compiling a project using pf4j on an arm64 machine?

**Comment by decebals** [comment]
> Have you tried compiling a project using pf4j on an arm64 machine?

No

**Comment by decebals** [comment]
If I have some time I will try to use a Raspberry Pi for test. At the moment I don't have the time and the board, too.

**Comment by decebals** [comment]
Unfortunately I didn't have time. is the topic still relevant for you?

**Comment by decebals** [comment]
If your question is still relevant, please reopen the issue.
