### ISSUE TITLE
 pf4j vs dependency injection framework

### ISSUE THREAD

**Issue by man-chi** [pf4j/pf4j#572]
I am building a web application that has plugin capability similar to the vscode extension.

thanks to the pf4j great community, I am impressed by the simplicity of pf4j.

may I know the differences between pf4j vs spring DI framework ?

when is the best use case to integrate both pf4j with DI framework?

please kindly advise

**Comment by decebals** [comment]
> thanks to the pf4j great community, I am impressed by the simplicity of pf4j.

Thanks also and welcome.

> may I know the differences between pf4j vs spring DI framework ?

They were designed to solve different problems. You can simulate a plugin framework with spring DI, to define an interface and retrieve all implementations, but that's about it. Pf4j loads each plugin, uses a separate class loader (for isolation), manages plugins (dependencies, ..) and emits events related to their life-cycle plus not everyone uses spring.

There are other differences, but I'll stop here.

> when is the best use case to integrate both pf4j with DI framework?

When you have a spring base application but you want to use the power of pf4j. For more details about pf4j and spring please see [pf4j-spring](https://github.com/pf4j/pf4j-spring), [pf4j-spring-tutorial](https://ralemy.github.io/pf4j-spring-tutorial/), [pf4j-spring-boot](https://github.com/hank-cp/sbp) and others.

**Comment by man-chi** [comment]
thanks for the great feedback and advice.

one more thing, how would you compare pf4j to osgi? when should I use pf4j vs osgi?

**Comment by decebals** [comment]
> one more thing, how would you compare pf4j to osgi? when should I use pf4j vs osgi?

Both (osgi and pf4j) allow you to load plugins dynamically (e.g., by its filename). They also handle plugin isolation, and provide some abstractions atop (like lifecycle management). For many people (I count myself among them) OSGi appears heavyweight and complex. PF4J can be seen as an alternative to OSGI.

**Comment by man-chi** [comment]
thanks for sharing your valuable insight.
