### ISSUE TITLE
Question: Migrate from other plugin system

### ISSUE THREAD

**Issue by makiam** [pf4j/pf4j#578]
I'm researching the possibility of migrating code from another Plugin Framework and there are several functions that I can't express using pf4j.
Current framework allows me to register some localized resources inside plugin and then access them in code. Ex. I can declare in my plugin descriptor (i.e xml file)
```
    <resource type="TranslateBundle" id="polymesh" name="polymesh"/>
    <resource type="UITheme" id="polymesh" name="polymesh/theme.xml"/>

```
it is also possible for several different localized versions of a resource to be available provided by different plugins.

So this resources can be accessed from application Plugin and UITheming managers like this:
`var name =  Translate.text("polymesh:menu.lathe");
`
Another functionality is to register function in plugin to be accessed from other parts application this way:
Register:
```
        <export method="getString" id="preferences.getString" >
            Get a String value

            @param owner String name of the preferences owner
            @param name  String name of the preference value

            @return the preference value as a String
        </export>


```
NB. Method call can be documented here!
Call:
`PluginRegistry.invokeExportedMethod("preferences.getString", "spmanager", "userName");
`

So the question is such functionality can be adopted with pf4j
Thanks.

**Comment by decebals** [comment]
> Current framework allows me to register some localized resources inside plugin and then access them in code. 

Probably you can use [ClassLoader/PluginClassLoader](https://github.com/pf4j/pf4j/blob/master/pf4j/src/main/java/org/pf4j/PluginClassLoader.java#L182) to achieve this.

> So this resources can be accessed from application Plugin and UITheming managers like this

The plugin that contains the resources can be declared as a dependency for other plugins => in that plugins you can use ClassLoader#getResource or ClassLoader#getResources

> Another functionality is to register function in plugin to be accessed from other parts application this way

Put these methods in a static class? 

I'm sure that you can emulate all these behaviors in your pf4j based application. In the end you need to think in terms of functionalities and not in the terms in which that functionality was implemented in the old plugin system (xml stuff, ..). If you insist to preserve the old API you can add a tiny layer over PF4J nu obtain the same API.

**Comment by makiam** [comment]
Main question is how to register  resources/methods inside plugin system. Once I try to migrate codу I add implements ExtensionPoint and  apply @Extension annotation and its works. But this way cannot be applied to static resources
Looks like I need extra pass when plugin started to process my xml metadata (But this not looks handsome)

**Comment by decebals** [comment]
Start small/lean with a [quickstart](https://pf4j.org/dev/quickstart.html) project which highlights your problem in a narrow context. Share with us your quickstart project. It's more simple and easy to follow.
As I mention in my previous project, my feeling is that you are stuck thinking in the old framework. Try to think more freely, to think about what you have to do, what you want to achieve, and not how to translate in a 1:1 ratio code from the old framework into pf4j.

**Comment by makiam** [comment]
Demo project https://github.com/makiam/PluginFrameworkMigrateTest
and original one https://github.com/ArtOfIllusion/ArtOfIllusion

**Comment by decebals** [comment]
The demo project is too large. I'm sorry, I cannot help you.
