### ISSUE TITLE
How can I access the controller of the plugin inside the core

### ISSUE THREAD

**Issue by Gracemansam** [pf4j/pf4j#580]
Hello, Pls I try to use pf4j in my project but I can not access the controller of the plugin inside the core. Also the life cycle of the plugin, like stop and update.  Below is an image of the plugin staring inside the core application.Thank you
![pf4j1](https://github.com/pf4j/pf4j/assets/42440376/81d72ac8-79d2-43a8-8952-789b049d160d)

**Comment by decebals** [comment]
Please add more context (details). A [quickstart](https://pf4j.org/dev/quickstart.html) project that replicates your problem will speed up a resolution.

**Comment by decebals** [comment]
If you still need help, reopen it and add the requested information.
