### ISSUE TITLE
Upgrade to 3.11 not possible: "final" keyword on AbstractPluginManager.getResolveRecoveryStrategy() prevents use of dependency injection using Jakarta CDI

### ISSUE THREAD

**Issue by aschwarte10** [pf4j/pf4j#582]
When attempting to upgrade pf4j from 3.10 to 3.11 in our environment, we found a technical issue that causes our dependency injection to fail with exception. In our scenario we are extending the DefaultPluginManager as treat it as an application bean. Dependency injection for this bean fails with the exception `PluginManager is not proxyable because it contains a final protected method`

Consequently this is blocking for us the update to 3.11

We are using Jakarta CDI with JBoss Weld as implementation in our environment, and this uses by specification a proxy implementation. For such implementations `final` modifiers cannot be used, see https://jakarta.ee/specifications/cdi/3.0/jakarta-cdi-spec-3.0#unproxyable

The `final` modifier was introduced as part of https://github.com/pf4j/pf4j/pull/564 and we had a quick chat in the comments of that issue with @slovdahl and @decebals . Relevant method is `AbstractPluginManager.getResolveRecoveryStrategy()`

When there are no strong technical reasons for having the final, we propose to remove the `final` modifier to re-enable support for dependency injection using Jakarta CDI.

It would be great if you can communicate some kind of timeline for a potential fix release such that we can arrange our plannings. Also if you don't plan to remove the `final` modifier on the protected method, please share this information such that we can find alternative work-arounds.

**Comment by decebals** [comment]
The fix is included in the latest release [3..11.1](https://github.com/pf4j/pf4j/releases/tag/release-3.11.1)

**Comment by aschwarte10** [comment]
> The fix is included in the latest release [3..11.1](https://github.com/pf4j/pf4j/releases/tag/release-3.11.1)

Thanks a lot @decebals, this is really highly appreciated. Great to see such ownership of an open source project
