### ISSUE TITLE
Can It be used in SCALA

### ISSUE THREAD

**Issue by SuheylZ** [pf4j/pf4j#583]
recently started looking into this project as I need plugin functionality for my system. The system I have is in SCALA. as you know scala runs on JVM. I have two important things to ask 

1. Can the extensions/ plugins be used on GRAALVM  and GRAALJDK ?
2. Can they be utilized from Scala?

**Comment by decebals** [comment]
I don't know what to say because I don't use Scala.
a few years ago someone added an [article](https://andreyor.st/posts/2021-04-10-pf4j-and-clojure/) about how to use PF4J with Closure.
