### ISSUE TITLE
how to debug the zip plugin loaded by pf4j-spring with idea ?

### ISSUE THREAD

**Issue by QcoderWho** [pf4j/pf4j#587]
I have successfully run the zip plugin by pf4j-spring, but I cannot debug it in app with idea .

**Comment by decebals** [comment]
Nothing something special. Put a breakpoint and run app in debug mode.
What problem are you having? Please add some details.

**Comment by QcoderWho** [comment]
> Nothing something special. Put a breakpoint and run app in debug mode. What problem are you having? Please add some details.

If i have a spring boot web object as app , and the app integration some zip plugin . In this case, the idea can not link the zip plugin java source , when app call some ExtensionPoint method, how to hit some breakpoints in the zip plugins?

**Comment by QcoderWho** [comment]
I found the way to hit some breakpoint in idea, we need open the menu `Files ->  Project Structure -> Libraries`, and click
 the plus(+) button , choose `java` option , add xxx.jar and xxx-source.jar for plugins, the last right click the libraries and choose `Add to Modules` option. After complete all the steps above, you can see the plugin dependency in idea `External Libraries`.
