### ISSUE TITLE
When plugin use serviceloader(spi)?

### ISSUE THREAD

**Issue by ForinMH** [pf4j/pf4j#588]
When my main application contains a SPI (Service Provider Interface) service and within a plugin there exists a ServiceLoader, but the Thread.currentThread().getContextClassLoader() is returning the application's class loader (ApplicationClassLoader), there are specific points in the application's lifecycle where you can use Thread.currentThread().setContextClassLoader(classLoader) to set it to the PluginClassLoader.

**Comment by decebals** [comment]
https://github.com/pf4j/pf4j/issues/474#issuecomment-968052131

**Comment by ForinMH** [comment]
> [#474（评论）](https://github.com/pf4j/pf4j/issues/474#issuecomment-968052131)

thank, but when my main application has a spi service,and the plugin doesn't exists,and it will load the main application spi service impl class,how can i doesn't load the main application's spi service impl?

**Comment by decebals** [comment]
To be honest it's not clear for me what you try to achieve.
From what I understood you have a service interface (SI) defined in your application and probably you have some implementation of this service (S1, S2, S3) -> I don't know where (application or plugins).
In a plugin (P1) you try to load all services (S1, S2, S3) via java.util.ServiceLoader.load(Class_Of_SI).

And now, if the context described by me above is correct, please try to explain the result and what you want.
As a aditional information, as I explained in https://github.com/pf4j/pf4j/issues/474#issuecomment-968052131 you can call (if you want) the `SericeLoader#load` method with what `ClassLoader` you want.

**Comment by decebals** [comment]
@ForinMH What is the status here? Do you still need help?

**Comment by decebals** [comment]
If you still need help, reopen it and add the requested information.
