### ISSUE TITLE
How to use development mode?

### ISSUE THREAD

**Issue by lihengcn** [pf4j/pf4j#596]
I clone the pf4j-spring project and then I wanted to use developer mode. but I don't know how to use plugin1 and plugin2 in the app module.

I saw the introduction of's official website, https://pf4j.org/doc/development-mode.html, simply introduces the principle and debugging information will print more, I don't know how to use.

please help me, thanks

**Comment by decebals** [comment]
I apologize for the delay in replying.
If you look in the code and follow where method [PluginManager#isDevelopment](https://github.com/pf4j/pf4j/blob/215d64a73c707dd66cd9b56e44eca2398888299c/pf4j/src/main/java/org/pf4j/PluginManager.java#L182) is used you can identify that some components of PF4J are registered conditionally.

For example in [JarPluginManager](https://github.com/pf4j/pf4j/blob/master/pf4j/src/main/java/org/pf4j/JarPluginManager.java) you can see that in `dev` mode (short name for development) `DevelopmentPluginRepository` and `DevelopmentPluginLoader` are registered.
This approach makes the developer's life easier, he can run the application with the related plugins directly from the IDE, without the need to package the plugins and save them in the `root plugins`. 

https://github.com/pf4j/pf4j/issues/446#issuecomment-843917760

**Comment by decebals** [comment]
Reopen the issue if you need more help.
